apiVersion: "helm-expt.confighub.com/v1alpha1"
kind: "InstallerPackageReceipt"
metadata:
  name: "projectcalico-tigera-operator-v3-32-0"
spec:
  chart:
    name: "tigera-operator"
    repository: "projectcalico"
    version: "v3.32.0"
  deterministicBundle:
    byteIdenticalAcrossTwoLocalBundles: true
    command: "cub installer package packages/projectcalico/tigera-operator/v3.32.0 -o <tmp>/projectcalico-tigera-operator-v3-32-0.tgz"
    sha256: "4dc00a5d37c824f654345c0a089c6b8fb55af33540d9be496aed9d47178e0797"
  package:
    name: "projectcalico-tigera-operator"
    path: "packages/projectcalico/tigera-operator/v3.32.0"
    sourceFiles:
      -
        path: "README.md"
        sha256: "fdfc8792bc97f7dc1c562b205b58e6e3972d0aa2fd151265ac91dbd4bbb14fa9"
        bytes: 927
      -
        path: "bases/default/kustomization.yaml"
        sha256: "44d52637f259f73730afd3a41d7350391387456ab7c418f201eec1ef73720153"
        bytes: 99
      -
        path: "bases/default/upstream.yaml"
        sha256: "9ce56a65a1b0ca63aec202cb662a5389fe6a6a55e6d4b9db9920febcc5b2b350"
        bytes: 19893
      -
        path: "collector/target-facts.sh"
        sha256: "e6eaa94e7254f7d5a7223f0643b157810fb8783cba5ecf54ff11aaac80c0e288"
        bytes: 4263
      -
        path: "installer.yaml"
        sha256: "2a1e1f536e98f6e9e40b5df917548616975d1bf471164543c0832c42e3506477"
        bytes: 1319
      -
        path: "prerequisites/tigera-operator-bootstrap/delete-custom-resources.yaml"
        sha256: "352d0290f2236768ebb03f1054af132b8f2f891758d3ca1ec0cac33f88c19c53"
        bytes: 376
      -
        path: "prerequisites/tigera-operator-bootstrap/kustomization.yaml"
        sha256: "4a1ffce0d962ca1c2c2efdc80930e367a0ccf6dca6af238e2f97352dbb356b0a"
        bytes: 147
      -
        path: "records/README.md"
        sha256: "191c9799224aa0ae46420a9b1ba6a00c10b487f90aec9d8d63fca2ee37ec9758"
        bytes: 997
      -
        path: "records/default/helm-render-intent.yaml"
        sha256: "37f62a2eceb1aab8be10dd50a5e7eaa1ec510949aa53244a910e40fd06def0d8"
        bytes: 16498
      -
        path: "records/default/source-and-intent.yaml"
        sha256: "7b0c1761b93df8cbe0ff050dd50b948ebdf29ff1c3c5082b96293895dafd66a0"
        bytes: 18856
      -
        path: "records/index.yaml"
        sha256: "0a979c8c9c84c639a40941a8a702ccd7946a1cf30cc2fef40acb17643c71a586"
        bytes: 644
    version: "v3.32.0"
  setupChecks:
    -
      allowedCubOnlyObjects:
        - "v1|Namespace||default"
      base: "default"
      command: "cub installer setup --pull packages/projectcalico/tigera-operator/v3.32.0 --base default --work-dir <tmp> --non-interactive --namespace default"
      cubInstallObjectCountIncludingSupport: 11
      helmReleaseObjectCount: 10
      semanticObjectMatches: "10/10"
      separatedSecretCount: 0
      targetFactMode: "collector-facts"
      targetFactsBound: true
      variant: "default"
