#!/usr/bin/env bash
# jetstack/trust-manager v0.22.1 - base variant: default
# Path: pull the package, render this base variant locally, read the objects,
# then apply them with kubectl. No ConfigHub account is needed.
# Generated by scripts/generate-public-site.mjs from the committed package
# data for this base variant. Chart page: https://confighub.github.io/helm-expt/site/charts/jetstack-trust-manager-v0-22-1.html
set -euo pipefail

say() { printf '\n>> %s\n' "$*"; }

if ! command -v cub >/dev/null 2>&1; then
  printf 'cub is not installed. Install the cub CLI with:\n  curl -fsSL https://hub.confighub.com/cub/install.sh | bash\nthen add ~/.confighub/bin to your PATH and re-run this script.\n' >&2
  exit 1
fi

# Installer is a cub plugin. Check it before this script does any work.
if ! cub installer --help >/dev/null 2>&1; then
  printf 'The cub installer plugin is missing. Follow https://confighub.github.io/helm-expt/site/try.html#install-cub, then re-run this script.\n' >&2
  exit 1
fi

if ! command -v kustomize >/dev/null 2>&1; then
  printf 'kustomize is missing. Follow https://confighub.github.io/helm-expt/site/try.html#install-cub, then re-run this script.\n' >&2
  exit 1
fi

if ! command -v kubectl >/dev/null 2>&1; then
  printf 'kubectl is required for the apply step.\n' >&2
  exit 1
fi

say "Pull the package and render the default base variant into ./jetstack-trust-manager-v0-22-1-default"
cub installer setup --pull oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/jetstack-trust-manager:v0.22.1@sha256:dbdd2e3fbce82f520467f23eb6e0f10d745fd608b3f3a1e117f3238ea41f104e --base default --work-dir ./jetstack-trust-manager-v0-22-1-default --non-interactive --namespace default

say "Read what was rendered; nothing has touched the cluster yet"
ls ./jetstack-trust-manager-v0-22-1-default/out/manifests

wait_for_crd() {
  crd_name="$1"
  deadline=$(( $(date +%s) + 180 ))
  until kubectl get "crd/${crd_name}" >/dev/null 2>&1; do
    if [ "$(date +%s)" -ge "$deadline" ]; then
      printf "CRD %s did not appear within 180 seconds.\n" "$crd_name" >&2
      return 1
    fi
    sleep 2
  done
  kubectl wait --for=condition=Established --timeout=120s "crd/${crd_name}"
}

say "Ensure the default namespace exists"
kubectl create namespace default --dry-run=client -o yaml | kubectl apply -f -

say "Ensure the cert-manager namespace exists"
kubectl create namespace cert-manager --dry-run=client -o yaml | kubectl apply -f -

say "Check 2 CRDs included with this package"
missing_crds=0
if ! kubectl get crd/certificates.cert-manager.io >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/issuers.cert-manager.io >/dev/null 2>&1; then
  missing_crds=1
fi
if [ "$missing_crds" -eq 1 ]; then
  kubectl apply --server-side -f ./jetstack-trust-manager-v0-22-1-default/package/prerequisites/target-facts/default-crds.yaml
else
  say "The required CRDs already exist; leave them under their current owner"
fi
wait_for_crd certificates.cert-manager.io
wait_for_crd issuers.cert-manager.io

if [ "${REQUIREMENTS_READY:-0}" != "1" ]; then
  cat >&2 <<'EOF_REQUIREMENTS'
This base variant needs resources you must create with your own values first:
  - Secret default/trust-manager-tls keys tls.crt,tls.key
    kubectl -n default create secret generic trust-manager-tls --from-literal=tls.crt=<value> --from-literal=tls.key=<value>
Complete these prerequisites before applying the rendered objects.
Replace any <...> placeholders with values or files for your environment.
When the resources exist, re-run with:
  REQUIREMENTS_READY=1 bash try.sh
EOF_REQUIREMENTS
  exit 1
fi

if [ -d ./jetstack-trust-manager-v0-22-1-default/out/secrets ]; then
  say "Apply rendered Secrets first"
  kubectl apply -f ./jetstack-trust-manager-v0-22-1-default/out/secrets
fi

say "Apply the rendered objects"
kubectl apply -f ./jetstack-trust-manager-v0-22-1-default/out/manifests

say "Done. The cluster received exactly the files in ./jetstack-trust-manager-v0-22-1-default/out."
