apiVersion: "helm-expt.confighub.com/v1alpha1"
kind: "InstallerPackageReceipt"
metadata:
  name: "bitnami-postgresql-18.6.10"
spec:
  chart:
    name: "postgresql"
    repository: "bitnami"
    version: "18.6.10"
  deterministicBundle:
    byteIdenticalAcrossTwoLocalBundles: true
    command: "cub installer package packages/bitnami/postgresql/18.6.10 -o <tmp>/postgresql-18.6.10.tgz"
    sha256: "eae758b19e059573f217ba55bd8355a3be5c1d2e6107a1a2087cbe92c3ae60d9"
  package:
    name: "bitnami-postgresql"
    path: "packages/bitnami/postgresql/18.6.10"
    sourceFiles:
      -
        path: "README.md"
        sha256: "98b60eafac8fcbe5489e2a60628983db51fe1c9144be26822fa9a8219210407d"
        bytes: 192
      -
        path: "bases/existing-secret/kustomization.yaml"
        sha256: "44d52637f259f73730afd3a41d7350391387456ab7c418f201eec1ef73720153"
        bytes: 99
      -
        path: "bases/existing-secret/upstream.yaml"
        sha256: "dfbd333f2a1842ca8af06c501cf0b9719fd1b121fc5ee87b78a1cd3253f9497a"
        bytes: 9112
      -
        path: "bases/generated-passwords/kustomization.yaml"
        sha256: "44d52637f259f73730afd3a41d7350391387456ab7c418f201eec1ef73720153"
        bytes: 99
      -
        path: "bases/generated-passwords/upstream.yaml"
        sha256: "3813cd50ce20e68fab8ac09137d36e9164c718df62da7eb0b3df35ede0ce7f69"
        bytes: 9715
      -
        path: "collector/target-facts.sh"
        sha256: "113a7a5b95fffee0fe1058fd922fec35d02aaddbec3aebe2e4edb46c5f71d44a"
        bytes: 1698
      -
        path: "installer.yaml"
        sha256: "5d8acdd9173b83d74530ce940c799ff22fce47943d39f39cf01d4d5f514e5ddb"
        bytes: 1252
    version: "18.6.10"
  setupChecks:
    -
      allowedCubOnlyObjects:
        - "v1|Namespace||postgresql"
      base: "generated-passwords"
      command: "cub installer setup --pull packages/bitnami/postgresql/18.6.10 --base generated-passwords --work-dir <tmp> --non-interactive --namespace postgresql"
      cubInstallObjectCountIncludingSupport: 8
      helmReleaseObjectCount: 7
      semanticObjectMatches: "7/7"
      separatedSecretCount: 1
      targetFactMode: "not-required"
      targetFactsBound: false
      variant: "generated-passwords"
    -
      allowedCubOnlyObjects:
        - "v1|Namespace||postgresql"
      base: "existing-secret"
      command: "cub installer setup --pull packages/bitnami/postgresql/18.6.10 --base existing-secret --work-dir <tmp> --non-interactive --namespace postgresql"
      cubInstallObjectCountIncludingSupport: 7
      helmReleaseObjectCount: 6
      semanticObjectMatches: "6/6"
      separatedSecretCount: 0
      targetFactMode: "collector-facts"
      targetFactsBound: true
      variant: "existing-secret"
