#!/usr/bin/env bash
# dra-driver-nvidia/dra-driver-nvidia-gpu 0.5.0 - base variant: default
# Path: pull the package, render this base variant locally, read the objects,
# then apply them with kubectl. No ConfigHub account is needed.
# Generated by scripts/generate-public-site.mjs from the committed package
# data for this base variant. Chart page: https://confighub.github.io/helm-expt/site/charts/dra-driver-nvidia-dra-driver-nvidia-gpu-0-5-0.html
set -euo pipefail

say() { printf '\n>> %s\n' "$*"; }

if ! command -v cub >/dev/null 2>&1; then
  printf 'cub is not installed. Install the cub CLI with:\n  curl -fsSL https://hub.confighub.com/cub/install.sh | bash\nthen add ~/.confighub/bin to your PATH and re-run this script.\n' >&2
  exit 1
fi

# Installer is a cub plugin. Check it before this script does any work.
if ! cub installer --help >/dev/null 2>&1; then
  printf 'The cub installer plugin is missing. Follow https://confighub.github.io/helm-expt/site/try.html#install-cub, then re-run this script.\n' >&2
  exit 1
fi

if ! command -v kustomize >/dev/null 2>&1; then
  printf 'kustomize is missing. Follow https://confighub.github.io/helm-expt/site/try.html#install-cub, then re-run this script.\n' >&2
  exit 1
fi

if ! command -v kubectl >/dev/null 2>&1; then
  printf 'kubectl is required for the apply step.\n' >&2
  exit 1
fi

say "Pull the package and render the default base variant into ./dra-driver-nvidia-dra-driver-nvidia-gpu-0-5-0-default"
cub installer setup --pull oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/dra-driver-nvidia-dra-driver-nvidia-gpu:0.5.0@sha256:f7e5c5b64875eab480936e1d3845de368e334fd144857b5f5d79b619a63e6a5e --base default --work-dir ./dra-driver-nvidia-dra-driver-nvidia-gpu-0-5-0-default --non-interactive --namespace nvidia-dra-driver

say "Read what was rendered; nothing has touched the cluster yet"
ls ./dra-driver-nvidia-dra-driver-nvidia-gpu-0-5-0-default/out/manifests

wait_for_crd() {
  crd_name="$1"
  deadline=$(( $(date +%s) + 180 ))
  until kubectl get "crd/${crd_name}" >/dev/null 2>&1; do
    if [ "$(date +%s)" -ge "$deadline" ]; then
      printf "CRD %s did not appear within 180 seconds.\n" "$crd_name" >&2
      return 1
    fi
    sleep 2
  done
  kubectl wait --for=condition=Established --timeout=120s "crd/${crd_name}"
}

say "Ensure the nvidia-dra-driver namespace exists"
kubectl create namespace nvidia-dra-driver --dry-run=client -o yaml | kubectl apply -f -

say "Check 2 CRDs included with this package"
missing_crds=0
if ! kubectl get crd/computedomaincliques.resource.nvidia.com >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/computedomains.resource.nvidia.com >/dev/null 2>&1; then
  missing_crds=1
fi
if [ "$missing_crds" -eq 1 ]; then
  kubectl apply --server-side -f ./dra-driver-nvidia-dra-driver-nvidia-gpu-0-5-0-default/package/prerequisites/target-facts/default-crds.yaml
else
  say "The required CRDs already exist; leave them under their current owner"
fi
wait_for_crd computedomaincliques.resource.nvidia.com
wait_for_crd computedomains.resource.nvidia.com

if [ -d ./dra-driver-nvidia-dra-driver-nvidia-gpu-0-5-0-default/out/secrets ]; then
  say "Apply rendered Secrets first"
  kubectl apply -f ./dra-driver-nvidia-dra-driver-nvidia-gpu-0-5-0-default/out/secrets
fi

say "Apply the rendered objects"
kubectl apply -f ./dra-driver-nvidia-dra-driver-nvidia-gpu-0-5-0-default/out/manifests

say "Done. The cluster received exactly the files in ./dra-driver-nvidia-dra-driver-nvidia-gpu-0-5-0-default/out."
