#!/usr/bin/env bash
# bitnami/mysql 14.0.3 - base variant: existing-secret
# Path: render this base variant locally, then upload the objects to your
# ConfigHub Space as Units you can edit, diff, and deliver.
# Needs a ConfigHub account: run cub auth login once before this script.
# Generated by scripts/generate-public-site.mjs from the committed package
# data for this base variant. Chart page: https://confighub.github.io/helm-expt/site/charts/bitnami-mysql-14-0-3.html
set -euo pipefail

say() { printf '\n>> %s\n' "$*"; }

if ! command -v cub >/dev/null 2>&1; then
  printf 'cub is not installed. Install it with:\n  curl -fsSL https://hub.confighub.com/cub/install.sh | bash\nthen add ~/.confighub/bin to your PATH and re-run this script.\n' >&2
  exit 1
fi

SPACE="${CUB_SPACE:-helm-mysql-existing-secret}"

say "Check ConfigHub auth"
if ! cub auth status >/dev/null 2>&1; then
  printf 'Not logged in. Run: cub auth login\nThen re-run this script.\n' >&2
  exit 1
fi

say "Render the existing-secret base variant into ./bitnami-mysql-14-0-3-existing-secret"
cub installer setup --pull oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/bitnami-mysql:14.0.3 --base existing-secret --work-dir ./bitnami-mysql-14-0-3-existing-secret --non-interactive --namespace mysql

say "Upload the rendered objects to Space ${SPACE} (created on first upload)"
cub installer upload --work-dir ./bitnami-mysql-14-0-3-existing-secret --space "${SPACE}"

say "Uploaded. See your Units:"
printf '  cub unit list --space %s\n  or open https://hub.confighub.com and find that Space.\n' "${SPACE}"

say "Next: create an environment variant and promote reviewed changes"
printf '  Walkthrough with the why behind each flag:\n  https://confighub.github.io/helm-expt/site/d/docs/user/variants-after-upload.html\n'

# Before applying this base variant from ConfigHub to a cluster, it still needs:
#   - Secret mysql/mysql-auth keys mysql-root-password,mysql-password,mysql-replication-password (suggested: kubectl -n mysql create secret generic mysql-auth --from-literal=mysql-root-password="$(openssl rand -base64 32)" --from-literal=mysql-password="$(openssl rand -base64 32)" --from-literal=mysql-replication-password="$(openssl rand -base64 32)")
