#!/usr/bin/env bash
# kyverno/kyverno-policies 3.9.0 - base variant: default
# Path: pull the package, render this base variant locally, read the objects,
# then apply them with kubectl. No ConfigHub account is needed.
# Generated by scripts/generate-public-site.mjs from the committed package
# data for this base variant. Chart page: https://confighub.github.io/helm-expt/site/charts/kyverno-kyverno-policies-3-9-0.html
set -euo pipefail

say() { printf '\n>> %s\n' "$*"; }

if ! command -v cub >/dev/null 2>&1; then
  printf 'cub is not installed. Install the cub CLI with:\n  curl -fsSL https://hub.confighub.com/cub/install.sh | bash\nthen add ~/.confighub/bin to your PATH and re-run this script.\n' >&2
  exit 1
fi

# Installer is a cub plugin. Check it before this script does any work.
if ! cub installer --help >/dev/null 2>&1; then
  printf 'The cub installer plugin is missing. Follow https://confighub.github.io/helm-expt/site/try.html#install-cub, then re-run this script.\n' >&2
  exit 1
fi

if ! command -v kustomize >/dev/null 2>&1; then
  printf 'kustomize is missing. Follow https://confighub.github.io/helm-expt/site/try.html#install-cub, then re-run this script.\n' >&2
  exit 1
fi

if ! command -v kubectl >/dev/null 2>&1; then
  printf 'kubectl is required for the apply step.\n' >&2
  exit 1
fi

say "Pull the package and render the default base variant into ./kyverno-kyverno-policies-3-9-0-default"
cub installer setup --pull oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/kyverno-kyverno-policies:3.9.0@sha256:64effafc30ac1a1d0f702bd52ec8acf5b858ee4f2d3eba5978b718adfec55751 --base default --work-dir ./kyverno-kyverno-policies-3-9-0-default --non-interactive --namespace kyverno

say "Read what was rendered; nothing has touched the cluster yet"
ls ./kyverno-kyverno-policies-3-9-0-default/out/manifests

say "Ensure the kyverno namespace exists"
kubectl create namespace kyverno --dry-run=client -o yaml | kubectl apply -f -

if [ -d ./kyverno-kyverno-policies-3-9-0-default/out/secrets ]; then
  say "Apply rendered Secrets first"
  kubectl apply -f ./kyverno-kyverno-policies-3-9-0-default/out/secrets
fi

say "Apply the rendered objects"
kubectl apply -f ./kyverno-kyverno-policies-3-9-0-default/out/manifests

say "Done. The cluster received exactly the files in ./kyverno-kyverno-policies-3-9-0-default/out."
