apiVersion: "catalog.confighub.com/v1alpha1"
kind: "InstallerPackageRecordIndex"
metadata:
  name: "fluent-fluent-bit-0.57.6"
spec:
  package:
    name: "fluent-fluent-bit"
    version: "0.57.6"
    role: "multi-preset-source-package"
  recordsAreDeployable: false
  repository:
    url: "https://github.com/confighub/helm-expt"
    evidenceBaseUrl: "https://github.com/confighub/helm-expt/blob/main/"
  bases:
    -
      name: "default"
      objects: "bases/default/upstream.yaml"
      sourceAndIntent: "records/default/source-and-intent.yaml"
      sourceSpecificIntent: "records/default/helm-render-intent.yaml"
