#!/usr/bin/env bash
# percona/pxc-operator 1.19.1 - base variant: default
# Path: pull the package, render this base variant locally, read the objects,
# then apply them with kubectl. No ConfigHub account is needed.
# Generated by scripts/generate-public-site.mjs from the committed package
# data for this base variant. Chart page: https://confighub.github.io/helm-expt/site/charts/percona-pxc-operator-1-19-1.html
set -euo pipefail

say() { printf '\n>> %s\n' "$*"; }

if ! command -v cub >/dev/null 2>&1; then
  printf 'cub is not installed. Install the cub CLI with:\n  curl -fsSL https://hub.confighub.com/cub/install.sh | bash\nthen add ~/.confighub/bin to your PATH and re-run this script.\n' >&2
  exit 1
fi

# Installer is a cub plugin. Check it before this script does any work.
if ! cub installer --help >/dev/null 2>&1; then
  printf 'The cub installer plugin is missing. Follow https://confighub.github.io/helm-expt/site/try.html#install-cub, then re-run this script.\n' >&2
  exit 1
fi

if ! command -v kustomize >/dev/null 2>&1; then
  printf 'kustomize is missing. Follow https://confighub.github.io/helm-expt/site/try.html#install-cub, then re-run this script.\n' >&2
  exit 1
fi

if ! command -v kubectl >/dev/null 2>&1; then
  printf 'kubectl is required for the apply step.\n' >&2
  exit 1
fi

say "Pull the package and render the default base variant into ./percona-pxc-operator-1-19-1-default"
cub installer setup --pull oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/percona-pxc-operator:1.19.1@sha256:dfd45f6ec4cefd0615535ad7f43273ddb3176f0d1d5fa6edd96a5835d66c0e27 --base default --work-dir ./percona-pxc-operator-1-19-1-default --non-interactive --namespace default

say "Read what was rendered; nothing has touched the cluster yet"
ls ./percona-pxc-operator-1-19-1-default/out/manifests

say "Ensure the default namespace exists"
kubectl create namespace default --dry-run=client -o yaml | kubectl apply -f -

if [ -d ./percona-pxc-operator-1-19-1-default/out/secrets ]; then
  say "Apply rendered Secrets first"
  kubectl apply -f ./percona-pxc-operator-1-19-1-default/out/secrets
fi

say "Apply the rendered objects"
kubectl apply -f ./percona-pxc-operator-1-19-1-default/out/manifests

say "Done. The cluster received exactly the files in ./percona-pxc-operator-1-19-1-default/out."
