apiVersion: "helm-expt.confighub.com/v1alpha1"
kind: "Recipe"
metadata:
  name: "hashicorp-vault"
  version: "0.32.0"
spec:
  chartRef:
    sourceLock: "source-lock.yaml"
    dependencyLock: "dependency-lock.yaml"
  importMode: "render-and-vendor"
  currentExecutableFixture:
    installerPackage: "../../../../packages/hashicorp/vault/0.32.0"
    setupCommand:
      - "cub"
      - "installer"
      - "setup"
      - "--pull"
      - "../../../../packages/hashicorp/vault/0.32.0"
      - "--non-interactive"
      - "--namespace"
      - "vault"
  variants:
    - "variants/dev-mode/variant.yaml"
    - "variants/default/variant.yaml"
    - "variants/ha-raft-ui/variant.yaml"
