#!/usr/bin/env bash
# descheduler/descheduler 0.36.0 - preset: default
# Path: pull the package, render this preset locally, read the objects,
# then apply them with kubectl. No ConfigHub account is needed.
# Generated by scripts/generate-public-site.mjs from the committed package
# data for this preset. Chart page: https://confighub.github.io/helm-expt/site/charts/descheduler-descheduler-0-36-0.html
set -euo pipefail

say() { printf '\n>> %s\n' "$*"; }

if ! command -v cub >/dev/null 2>&1; then
  printf 'cub is not installed. Install it with:\n  curl -fsSL https://hub.confighub.com/cub/install.sh | bash\nthen add ~/.confighub/bin to your PATH and re-run this script.\n' >&2
  exit 1
fi

if ! command -v kubectl >/dev/null 2>&1; then
  printf 'kubectl is required for the apply step.\n' >&2
  exit 1
fi

say "Pull the package and render the default preset into ./descheduler-descheduler-0-36-0-default"
cub installer setup --pull oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/descheduler-descheduler:0.36.0 --base default --work-dir ./descheduler-descheduler-0-36-0-default --non-interactive --namespace default

say "Read what was rendered; nothing has touched the cluster yet"
ls ./descheduler-descheduler-0-36-0-default/out/manifests

say "Ensure the default namespace exists"
kubectl create namespace default --dry-run=client -o yaml | kubectl apply -f -

if [ -d ./descheduler-descheduler-0-36-0-default/out/secrets ]; then
  say "Apply rendered Secrets first"
  kubectl apply -f ./descheduler-descheduler-0-36-0-default/out/secrets
fi

say "Apply the rendered objects"
kubectl apply -f ./descheduler-descheduler-0-36-0-default/out/manifests

say "Done. The cluster received exactly the files in ./descheduler-descheduler-0-36-0-default/out."
