#!/usr/bin/env bash
# hashicorp/consul 2.0.0 - base variant: default-control-plane
# Path: pull the package, render this base variant locally, read the objects,
# then apply them with kubectl. No ConfigHub account is needed.
# Generated by scripts/generate-public-site.mjs from the committed package
# data for this base variant. Chart page: https://confighub.github.io/helm-expt/site/charts/hashicorp-consul-2-0-0.html
set -euo pipefail

say() { printf '\n>> %s\n' "$*"; }

if ! command -v cub >/dev/null 2>&1; then
  printf 'cub is not installed. Install it with:\n  curl -fsSL https://hub.confighub.com/cub/install.sh | bash\nthen add ~/.confighub/bin to your PATH and re-run this script.\n' >&2
  exit 1
fi

if ! command -v kubectl >/dev/null 2>&1; then
  printf 'kubectl is required for the apply step.\n' >&2
  exit 1
fi

say "Pull the package and render the default-control-plane base variant into ./hashicorp-consul-2-0-0-default-control-plane"
cub installer setup --pull oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/hashicorp-consul:2.0.0 --base default-control-plane --work-dir ./hashicorp-consul-2-0-0-default-control-plane --non-interactive --namespace consul

say "Read what was rendered; nothing has touched the cluster yet"
ls ./hashicorp-consul-2-0-0-default-control-plane/out/manifests

say "Ensure the consul namespace exists"
kubectl create namespace consul --dry-run=client -o yaml | kubectl apply -f -

if [ -d ./hashicorp-consul-2-0-0-default-control-plane/out/secrets ]; then
  say "Apply rendered Secrets first"
  kubectl apply -f ./hashicorp-consul-2-0-0-default-control-plane/out/secrets
fi

say "Apply the rendered objects"
kubectl apply -f ./hashicorp-consul-2-0-0-default-control-plane/out/manifests

say "Done. The cluster received exactly the files in ./hashicorp-consul-2-0-0-default-control-plane/out."
