apiVersion: helm-expt.confighub.com/v1alpha1
kind: InstallerPackagePublicationReceipt
metadata:
  name: jaegertracing-jaeger-operator-2.57.0
spec:
  ref: oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/jaegertracing-jaeger-operator:2.57.0
  package:
    path: packages/jaegertracing/jaeger-operator/2.57.0
    sha256: f7cdd7f04e556cc0c8eadd3536ca664e7b2932f562a457b2515aa757e96da0f3
  commands:
    package: "cub installer package packages/jaegertracing/jaeger-operator/2.57.0 -o <tmp>/jaegertracing-jaeger-operator-2.57.0.tgz"
    push: "cub installer push <tmp>/jaegertracing-jaeger-operator-2.57.0.tgz oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/jaegertracing-jaeger-operator:2.57.0"
    inspect: "cub installer inspect oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/jaegertracing-jaeger-operator:2.57.0 --json"
  outputs:
    package: |
      Bundled jaegertracing-jaeger-operator@
        output: /var/folders/4l/8wvwwzxs3xl78749bmmqzzbw0000gp/T/helm-expt-installer-oci-Fjd8DQ/jaegertracing-jaeger-operator-2.57.0.tgz
        files:  9
        size:   136529 bytes
        digest: sha256:f7cdd7f04e556cc0c8eadd3536ca664e7b2932f562a457b2515aa757e96da0f3
    push: |
      Pushed europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/jaegertracing-jaeger-operator:2.57.0
        manifest: sha256:2fb7189103f0f7239b1bd2b27740abe768a90dc7658aac7f1ea01d070ea35e85
        layer:    sha256:f7cdd7f04e556cc0c8eadd3536ca664e7b2932f562a457b2515aa757e96da0f3 (136529 bytes, 9 files)
    inspectJSONSHA256: 407421f9408e7cd1b34a4b05b9546abec3c1db1a0d814ca71ac7232736b58e02
