apiVersion: "helm-expt.confighub.com/v1alpha1"
kind: "EffectiveValues"
metadata:
  name: "dra-driver-nvidia-dra-driver-nvidia-gpu-0.4.1-aicr-eks-training"
spec:
  files:
    -
      path: "effective-values-aicr-eks-training.yaml"
      source: "inline-proof"
      sha256: "69377bd4d16edd23cfb2595d28951b5f2c11622e026ed7aa2410ef09db7e55cb"
  mergedValuesCaptured: false
  values:
    controller:
      affinity:
        nodeAffinity: null
      podAnnotations:
        aicr.run/gpu-operator-chart-version: "v26.3.3"
      priorityClassName: ""
      tolerations:
        -
          operator: "Exists"
    fullnameOverride: "nvidia-dra-driver-gpu"
    gpuResourcesEnabledOverride: false
    kubeletPlugin:
      nodeSelector:
        nvidia.com/gpu.present: "true"
      podAnnotations:
        aicr.run/gpu-operator-chart-version: "v26.3.3"
      priorityClassName: ""
      tolerations:
        -
          operator: "Exists"
    nameOverride: "nvidia-dra-driver-gpu"
    nvidiaDriverRoot: "/run/nvidia/driver"
    resources:
      computeDomains:
        enabled: true
      gpus:
        enabled: false
