#!/usr/bin/env bash
# prometheus-community/prometheus-node-exporter 4.55.0 - base variant: cluster-metrics-readonly
# Path: pull the package, render this base variant locally, read the objects,
# then apply them with kubectl. No ConfigHub account is needed.
# Generated by scripts/generate-public-site.mjs from the committed package
# data for this base variant. Chart page: https://confighub.github.io/helm-expt/site/charts/prometheus-community-prometheus-node-exporter-4-55-0.html
set -euo pipefail

say() { printf '\n>> %s\n' "$*"; }

if ! command -v cub >/dev/null 2>&1; then
  printf 'cub is not installed. Install the cub CLI with:\n  curl -fsSL https://hub.confighub.com/cub/install.sh | bash\nthen add ~/.confighub/bin to your PATH and re-run this script.\n' >&2
  exit 1
fi

# Installer is a cub plugin. Check it before this script does any work.
if ! cub installer --help >/dev/null 2>&1; then
  printf 'The cub installer plugin is missing. Follow https://confighub.github.io/helm-expt/site/try.html#install-cub, then re-run this script.\n' >&2
  exit 1
fi

if ! command -v kustomize >/dev/null 2>&1; then
  printf 'kustomize is missing. Follow https://confighub.github.io/helm-expt/site/try.html#install-cub, then re-run this script.\n' >&2
  exit 1
fi

if ! command -v kubectl >/dev/null 2>&1; then
  printf 'kubectl is required for the apply step.\n' >&2
  exit 1
fi

say "Pull the package and render the cluster-metrics-readonly base variant into ./prometheus-community-prometheus-node-exporter-4-55-0-cluster-metrics-readonly"
cub installer setup --pull oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/prometheus-community-prometheus-node-exporter:4.55.0@sha256:b5365489a899714904a438a5a3ccb2f7a7814f1b41bc16cf8fa41638e4ffa9cd --base cluster-metrics-readonly --work-dir ./prometheus-community-prometheus-node-exporter-4-55-0-cluster-metrics-readonly --non-interactive --namespace default

say "Read what was rendered; nothing has touched the cluster yet"
ls ./prometheus-community-prometheus-node-exporter-4-55-0-cluster-metrics-readonly/out/manifests

wait_for_crd() {
  crd_name="$1"
  deadline=$(( $(date +%s) + 180 ))
  until kubectl get "crd/${crd_name}" >/dev/null 2>&1; do
    if [ "$(date +%s)" -ge "$deadline" ]; then
      printf "CRD %s did not appear within 180 seconds.\n" "$crd_name" >&2
      return 1
    fi
    sleep 2
  done
  kubectl wait --for=condition=Established --timeout=120s "crd/${crd_name}"
}

say "Ensure the default namespace exists"
kubectl create namespace default --dry-run=client -o yaml | kubectl apply -f -

say "Check the servicemonitors.monitoring.coreos.com CRD included with this package"
missing_crds=0
if ! kubectl get crd/servicemonitors.monitoring.coreos.com >/dev/null 2>&1; then
  missing_crds=1
fi
if [ "$missing_crds" -eq 1 ]; then
  kubectl apply --server-side -f ./prometheus-community-prometheus-node-exporter-4-55-0-cluster-metrics-readonly/package/prerequisites/target-facts/cluster-metrics-readonly-crds.yaml
else
  say "The required CRDs already exist; leave them under their current owner"
fi
wait_for_crd servicemonitors.monitoring.coreos.com

if [ -d ./prometheus-community-prometheus-node-exporter-4-55-0-cluster-metrics-readonly/out/secrets ]; then
  say "Apply rendered Secrets first"
  kubectl apply -f ./prometheus-community-prometheus-node-exporter-4-55-0-cluster-metrics-readonly/out/secrets
fi

say "Apply the rendered objects"
kubectl apply -f ./prometheus-community-prometheus-node-exporter-4-55-0-cluster-metrics-readonly/out/manifests

say "Done. The cluster received exactly the files in ./prometheus-community-prometheus-node-exporter-4-55-0-cluster-metrics-readonly/out."
