apiVersion: helm-expt.confighub.com/v1alpha1
kind: InstallerPackagePublicationReceipt
metadata:
  name: grafana-alloy-1.8.2
spec:
  ref: oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/grafana-alloy:1.8.2
  observedAt: "2026-08-08T20:47:14.876Z"
  package:
    path: packages/grafana/alloy/1.8.2
    sha256: ca3141104f9da7a56a4b5ac332ea2018dd73309c7bf448e99221fd2b4c92a725
  commands:
    package: "cub installer package packages/grafana/alloy/1.8.2 -o <tmp>/grafana-alloy-1.8.2.tgz"
    push: "cub installer push <tmp>/grafana-alloy-1.8.2.tgz oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/grafana-alloy:1.8.2"
    inspect: "cub installer inspect oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/grafana-alloy:1.8.2 --json"
  outputs:
    package: |
      Bundled grafana-alloy@
        output: /var/folders/4l/8wvwwzxs3xl78749bmmqzzbw0000gp/T/helm-expt-installer-oci-F71RMS/grafana-alloy-1.8.2.tgz
        files:  6
        size:   3911 bytes
        digest: sha256:ca3141104f9da7a56a4b5ac332ea2018dd73309c7bf448e99221fd2b4c92a725
    push: |
      Pushed europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/grafana-alloy:1.8.2
        manifest: sha256:c5eca0ff80f0977757f107963b12510ff9a6105f1d02036e3954833e81bd2425
        layer:    sha256:ca3141104f9da7a56a4b5ac332ea2018dd73309c7bf448e99221fd2b4c92a725 (3911 bytes, 6 files)
    inspectJSONSHA256: 687345b11c9353cf86c24ef5f6a08f4d1efbc436954811fe86353890a2d2d05b
