#!/usr/bin/env bash
# hashicorp/terraform 1.1.2 - preset: no-crds
# Path: pull the package, render this preset locally, read the objects,
# then apply them with kubectl. No ConfigHub account is needed.
# Generated by scripts/generate-public-site.mjs from the committed package
# data for this preset. Chart page: https://confighub.github.io/helm-expt/site/charts/hashicorp-terraform-1-1-2.html
set -euo pipefail

say() { printf '\n>> %s\n' "$*"; }

if ! command -v cub >/dev/null 2>&1; then
  printf 'cub is not installed. Install it with:\n  curl -fsSL https://hub.confighub.com/cub/install.sh | bash\nthen add ~/.confighub/bin to your PATH and re-run this script.\n' >&2
  exit 1
fi

if ! command -v kubectl >/dev/null 2>&1; then
  printf 'kubectl is required for the apply step.\n' >&2
  exit 1
fi

say "Pull the package and render the no-crds preset into ./hashicorp-terraform-1-1-2-no-crds"
cub installer setup --pull oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/hashicorp-terraform:1.1.2 --base no-crds --work-dir ./hashicorp-terraform-1-1-2-no-crds --non-interactive --namespace default

say "Read what was rendered; nothing has touched the cluster yet"
ls ./hashicorp-terraform-1-1-2-no-crds/out/manifests

say "Ensure the default namespace exists"
kubectl create namespace default --dry-run=client -o yaml | kubectl apply -f -

if [ -d ./hashicorp-terraform-1-1-2-no-crds/out/secrets ]; then
  say "Apply rendered Secrets first"
  kubectl apply -f ./hashicorp-terraform-1-1-2-no-crds/out/secrets
fi

say "Apply the rendered objects"
kubectl apply -f ./hashicorp-terraform-1-1-2-no-crds/out/manifests

say "Done. The cluster received exactly the files in ./hashicorp-terraform-1-1-2-no-crds/out."
