#!/usr/bin/env bash
# kedacore/keda 2.19.0 - base variant: no-crds
# Path: pull the package, render this base variant locally, read the objects,
# then apply them with kubectl. No ConfigHub account is needed.
# Generated by scripts/generate-public-site.mjs from the committed package
# data for this base variant. Chart page: https://confighub.github.io/helm-expt/site/charts/kedacore-keda-2-19-0.html
set -euo pipefail

say() { printf '\n>> %s\n' "$*"; }

if ! command -v cub >/dev/null 2>&1; then
  printf 'cub is not installed. Install the cub CLI with:\n  curl -fsSL https://hub.confighub.com/cub/install.sh | bash\nthen add ~/.confighub/bin to your PATH and re-run this script.\n' >&2
  exit 1
fi

# Installer is a cub plugin. Check it before this script does any work.
if ! cub installer --help >/dev/null 2>&1; then
  printf 'The cub installer plugin is missing. Follow https://confighub.github.io/helm-expt/site/try.html#install-cub, then re-run this script.\n' >&2
  exit 1
fi

if ! command -v kustomize >/dev/null 2>&1; then
  printf 'kustomize is missing. Follow https://confighub.github.io/helm-expt/site/try.html#install-cub, then re-run this script.\n' >&2
  exit 1
fi

if ! command -v kubectl >/dev/null 2>&1; then
  printf 'kubectl is required for the apply step.\n' >&2
  exit 1
fi

say "Pull the package and render the no-crds base variant into ./kedacore-keda-2-19-0-no-crds"
cub installer setup --pull oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/kedacore-keda:2.19.0 --base no-crds --work-dir ./kedacore-keda-2-19-0-no-crds --non-interactive --namespace default

say "Read what was rendered; nothing has touched the cluster yet"
ls ./kedacore-keda-2-19-0-no-crds/out/manifests

wait_for_crd() {
  crd_name="$1"
  deadline=$(( $(date +%s) + 180 ))
  until kubectl get "crd/${crd_name}" >/dev/null 2>&1; do
    if [ "$(date +%s)" -ge "$deadline" ]; then
      printf "CRD %s did not appear within 180 seconds.\n" "$crd_name" >&2
      return 1
    fi
    sleep 2
  done
  kubectl wait --for=condition=Established --timeout=120s "crd/${crd_name}"
}

say "Ensure the default namespace exists"
kubectl create namespace default --dry-run=client -o yaml | kubectl apply -f -

say "Check 6 CRDs included with this package"
missing_crds=0
if ! kubectl get crd/cloudeventsources.eventing.keda.sh >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/clustercloudeventsources.eventing.keda.sh >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/clustertriggerauthentications.keda.sh >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/scaledjobs.keda.sh >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/scaledobjects.keda.sh >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/triggerauthentications.keda.sh >/dev/null 2>&1; then
  missing_crds=1
fi
if [ "$missing_crds" -eq 1 ]; then
  kubectl apply --server-side -f ./kedacore-keda-2-19-0-no-crds/package/prerequisites/target-facts/no-crds-crds.yaml
else
  say "The required CRDs already exist; leave them under their current owner"
fi
wait_for_crd cloudeventsources.eventing.keda.sh
wait_for_crd clustercloudeventsources.eventing.keda.sh
wait_for_crd clustertriggerauthentications.keda.sh
wait_for_crd scaledjobs.keda.sh
wait_for_crd scaledobjects.keda.sh
wait_for_crd triggerauthentications.keda.sh

if [ -d ./kedacore-keda-2-19-0-no-crds/out/secrets ]; then
  say "Apply rendered Secrets first"
  kubectl apply -f ./kedacore-keda-2-19-0-no-crds/out/secrets
fi

say "Apply the rendered objects"
kubectl apply -f ./kedacore-keda-2-19-0-no-crds/out/manifests

say "Done. The cluster received exactly the files in ./kedacore-keda-2-19-0-no-crds/out."
