#!/usr/bin/env bash
# hashicorp/consul 2.0.0 - preset: secure-mesh-existing-secrets
# Path: render this preset locally, then upload the objects to your
# ConfigHub Space as Units you can edit, diff, and deliver.
# Needs a ConfigHub account: run cub auth login once before this script.
# Generated by scripts/generate-public-site.mjs from the committed package
# data for this preset. Chart page: https://confighub.github.io/helm-expt/site/charts/hashicorp-consul-2-0-0.html
set -euo pipefail

say() { printf '\n>> %s\n' "$*"; }

if ! command -v cub >/dev/null 2>&1; then
  printf 'cub is not installed. Install it with:\n  curl -fsSL https://hub.confighub.com/cub/install.sh | bash\nthen add ~/.confighub/bin to your PATH and re-run this script.\n' >&2
  exit 1
fi

SPACE="${CUB_SPACE:-helm-consul-secure-mesh-existing-secrets}"

say "Check ConfigHub auth"
if ! cub auth status >/dev/null 2>&1; then
  printf 'Not logged in. Run: cub auth login\nThen re-run this script.\n' >&2
  exit 1
fi

say "Render the secure-mesh-existing-secrets preset into ./hashicorp-consul-2-0-0-secure-mesh-existing-secrets"
cub installer setup --pull oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/hashicorp-consul:2.0.0 --base secure-mesh-existing-secrets --work-dir ./hashicorp-consul-2-0-0-secure-mesh-existing-secrets --non-interactive --namespace consul

say "Upload the rendered objects to Space ${SPACE} (created on first upload)"
cub installer upload --work-dir ./hashicorp-consul-2-0-0-secure-mesh-existing-secrets --space "${SPACE}"

say "Uploaded. See your Units:"
printf '  cub unit list --space %s\n  or open https://hub.confighub.com and find that Space.\n' "${SPACE}"

say "Next: create an environment variant and promote reviewed changes"
printf '  Walkthrough with the why behind each flag:\n  https://confighub.github.io/helm-expt/site/d/docs/user/variants-after-upload.html\n'

# Before applying this preset from ConfigHub to a cluster, it still needs:
#   - Secret consul/consul-ca-cert key tls.crt (suggested: kubectl -n consul create secret generic consul-ca-cert --from-literal=tls.crt=<value>)
#   - Secret consul/consul-server-cert keys tls.crt,tls.key (suggested: kubectl -n consul create secret generic consul-server-cert --from-literal=tls.crt=<value> --from-literal=tls.key=<value>)
#   - Secret consul/consul-gossip-encryption-key key key (suggested: kubectl -n consul create secret generic consul-gossip-encryption-key --from-literal=key=<value>)
#   - Secret consul/consul-bootstrap-acl-token key token (suggested: kubectl -n consul create secret generic consul-bootstrap-acl-token --from-literal=token=<value>)
#   - minimum schedulable nodes 3 (suggested: use a target with at least 3 schedulable nodes before applying this base)
