#!/usr/bin/env bash
# hashicorp/consul 2.0.0 - preset: secure-mesh-existing-secrets
# Path: pull the package, render this preset locally, read the objects,
# then apply them with kubectl. No ConfigHub account is needed.
# Generated by scripts/generate-public-site.mjs from the committed package
# data for this preset. Chart page: https://confighub.github.io/helm-expt/site/charts/hashicorp-consul-2-0-0.html
set -euo pipefail

say() { printf '\n>> %s\n' "$*"; }

if ! command -v cub >/dev/null 2>&1; then
  printf 'cub is not installed. Install it with:\n  curl -fsSL https://hub.confighub.com/cub/install.sh | bash\nthen add ~/.confighub/bin to your PATH and re-run this script.\n' >&2
  exit 1
fi

if ! command -v kubectl >/dev/null 2>&1; then
  printf 'kubectl is required for the apply step.\n' >&2
  exit 1
fi

say "Pull the package and render the secure-mesh-existing-secrets preset into ./hashicorp-consul-2-0-0-secure-mesh-existing-secrets"
cub installer setup --pull oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/hashicorp-consul:2.0.0 --base secure-mesh-existing-secrets --work-dir ./hashicorp-consul-2-0-0-secure-mesh-existing-secrets --non-interactive --namespace consul

say "Read what was rendered; nothing has touched the cluster yet"
ls ./hashicorp-consul-2-0-0-secure-mesh-existing-secrets/out/manifests

say "Ensure the consul namespace exists"
kubectl create namespace consul --dry-run=client -o yaml | kubectl apply -f -

say "Requirement before apply: minimum schedulable nodes 3"
if ! use a target with at least 3 schedulable nodes before applying this base; then
  printf '!! The requirement command failed. If the resource already exists, review it and re-run; otherwise fix the error above.\n' >&2
  exit 1
fi

if [ "${REQUIREMENTS_READY:-0}" != "1" ]; then
  cat >&2 <<'EOF_REQUIREMENTS'
This preset needs resources you must create with your own values first:
  - Secret consul/consul-ca-cert key tls.crt
    kubectl -n consul create secret generic consul-ca-cert --from-literal=tls.crt=<value>
  - Secret consul/consul-server-cert keys tls.crt,tls.key
    kubectl -n consul create secret generic consul-server-cert --from-literal=tls.crt=<value> --from-literal=tls.key=<value>
  - Secret consul/consul-gossip-encryption-key key key
    kubectl -n consul create secret generic consul-gossip-encryption-key --from-literal=key=<value>
  - Secret consul/consul-bootstrap-acl-token key token
    kubectl -n consul create secret generic consul-bootstrap-acl-token --from-literal=token=<value>
Substitute the <...> placeholders and create these, then re-run with:
  REQUIREMENTS_READY=1 bash try.sh
EOF_REQUIREMENTS
  exit 1
fi

if [ -d ./hashicorp-consul-2-0-0-secure-mesh-existing-secrets/out/secrets ]; then
  say "Apply rendered Secrets first"
  kubectl apply -f ./hashicorp-consul-2-0-0-secure-mesh-existing-secrets/out/secrets
fi

say "Apply the rendered objects"
kubectl apply -f ./hashicorp-consul-2-0-0-secure-mesh-existing-secrets/out/manifests

say "Done. The cluster received exactly the files in ./hashicorp-consul-2-0-0-secure-mesh-existing-secrets/out."
