apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "6"
    name: prometheus-operator-crds
    namespace: argocd
spec:
    destination:
        namespace: monitoring
        server: https://kubernetes.default.svc
    project: default
    source:
        chart: prometheus-operator-crds
        helm:
            values: |-
                {{- $static := (.Files.Get "static/prometheus-operator-crds.yaml") | fromYaml | default dict -}}
                {{- $dynamic := index .Values "prometheusoperatorcrds" | default dict -}}
                {{- mustMergeOverwrite $static $dynamic | toYaml | nindent 16 }}
        repoURL: https://prometheus-community.github.io/helm-charts
        targetRevision: 28.0.1
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - CreateNamespace=true
            - ServerSideApply=true
