apiVersion: "helm-expt.confighub.com/v1alpha1"
kind: "EffectiveValues"
metadata:
  name: "node-feature-discovery-node-feature-discovery-0.19.0-aicr-eks-training-v0-20-0"
spec:
  files:
    -
      path: "effective-values-aicr-eks-training-v0-20-0.yaml"
      source: "inline-proof"
      sha256: "2da5c78a5cff5e7348237ce22af0bf7c9b71a3cd1134bd17c38c94823a8e64d0"
  mergedValuesCaptured: false
  values:
    gc:
      enable: true
      tolerations:
        -
          operator: "Exists"
    master:
      enable: true
      tolerations:
        -
          operator: "Exists"
    topologyUpdater:
      createCRDs: true
      enable: true
      kubeletStateDir: ""
      resources:
        limits:
          memory: "256Mi"
        requests:
          cpu: "50m"
          memory: "128Mi"
      tolerations:
        -
          operator: "Exists"
    worker:
      enable: true
      tolerations:
        -
          operator: "Exists"
