#!/usr/bin/env bash
# kai-scheduler/kai-scheduler v0.16.9 - base variant: aicr-eks-training
# Path: pull the package, render this base variant locally, read the objects,
# then apply them with kubectl. No ConfigHub account is needed.
# Generated by scripts/generate-public-site.mjs from the committed package
# data for this base variant. Chart page: https://confighub.github.io/helm-expt/site/charts/kai-scheduler-kai-scheduler-v0-16-9.html
set -euo pipefail

say() { printf '\n>> %s\n' "$*"; }

if ! command -v cub >/dev/null 2>&1; then
  printf 'cub is not installed. Install the cub CLI with:\n  curl -fsSL https://hub.confighub.com/cub/install.sh | bash\nthen add ~/.confighub/bin to your PATH and re-run this script.\n' >&2
  exit 1
fi

# Installer is a cub plugin. Check it before this script does any work.
if ! cub installer --help >/dev/null 2>&1; then
  printf 'The cub installer plugin is missing. Follow https://confighub.github.io/helm-expt/site/try.html#install-cub, then re-run this script.\n' >&2
  exit 1
fi

if ! command -v kustomize >/dev/null 2>&1; then
  printf 'kustomize is missing. Follow https://confighub.github.io/helm-expt/site/try.html#install-cub, then re-run this script.\n' >&2
  exit 1
fi

if ! command -v kubectl >/dev/null 2>&1; then
  printf 'kubectl is required for the apply step.\n' >&2
  exit 1
fi

say "Pull the package and render the aicr-eks-training base variant into ./kai-scheduler-kai-scheduler-v0-16-9-aicr-eks-training"
cub installer setup --pull oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/kai-scheduler-kai-scheduler:v0.16.9@sha256:7d360f97ada7c492e506acdd433c9212d21f5a6d26d8d8cbf1f0b68a268e94ab --base aicr-eks-training --work-dir ./kai-scheduler-kai-scheduler-v0-16-9-aicr-eks-training --non-interactive --namespace kai-scheduler

say "Read what was rendered; nothing has touched the cluster yet"
ls ./kai-scheduler-kai-scheduler-v0-16-9-aicr-eks-training/out/manifests

wait_for_crd() {
  crd_name="$1"
  deadline=$(( $(date +%s) + 180 ))
  until kubectl get "crd/${crd_name}" >/dev/null 2>&1; do
    if [ "$(date +%s)" -ge "$deadline" ]; then
      printf "CRD %s did not appear within 180 seconds.\n" "$crd_name" >&2
      return 1
    fi
    sleep 2
  done
  kubectl wait --for=condition=Established --timeout=120s "crd/${crd_name}"
}

say "Ensure the kai-scheduler namespace exists"
kubectl create namespace kai-scheduler --dry-run=client -o yaml | kubectl apply -f -

say "Check 6 CRDs included with this package"
missing_crds=0
if ! kubectl get crd/bindrequests.scheduling.run.ai >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/configs.kai.scheduler >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/podgroups.scheduling.run.ai >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/queues.scheduling.run.ai >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/schedulingshards.kai.scheduler >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/topologies.kai.scheduler >/dev/null 2>&1; then
  missing_crds=1
fi
if [ "$missing_crds" -eq 1 ]; then
  kubectl apply --server-side -f ./kai-scheduler-kai-scheduler-v0-16-9-aicr-eks-training/package/prerequisites/target-facts/aicr-eks-training-crds.yaml
else
  say "The required CRDs already exist; leave them under their current owner"
fi
wait_for_crd bindrequests.scheduling.run.ai
wait_for_crd configs.kai.scheduler
wait_for_crd podgroups.scheduling.run.ai
wait_for_crd queues.scheduling.run.ai
wait_for_crd schedulingshards.kai.scheduler
wait_for_crd topologies.kai.scheduler

if [ -d ./kai-scheduler-kai-scheduler-v0-16-9-aicr-eks-training/out/secrets ]; then
  say "Apply rendered Secrets first"
  kubectl apply -f ./kai-scheduler-kai-scheduler-v0-16-9-aicr-eks-training/out/secrets
fi

say "Apply the rendered objects"
kubectl apply -f ./kai-scheduler-kai-scheduler-v0-16-9-aicr-eks-training/out/manifests

say "Done. The cluster received exactly the files in ./kai-scheduler-kai-scheduler-v0-16-9-aicr-eks-training/out, with the packaged lifecycle steps checked."
