apiVersion: "installer.confighub.com/v1alpha1"
kind: "Package"
metadata:
  name: "jaegertracing-jaeger-operator"
  version: "2.57.0"
spec:
  bases:
    -
      name: "default"
      path: "bases/default"
      default: true
      description: "jaegertracing/jaeger-operator default variant rendered from jaegertracing/jaeger-operator@2.57.0"
