#!/usr/bin/env bash
# aqua/trivy-operator 0.32.1 - preset: no-crds
# Path: render this preset locally, then upload the objects to your
# ConfigHub Space as Units you can edit, diff, and deliver.
# Needs a ConfigHub account: run cub auth login once before this script.
# Generated by scripts/generate-public-site.mjs from the committed package
# data for this preset. Chart page: https://confighub.github.io/helm-expt/site/charts/aqua-trivy-operator-0-32-1.html
set -euo pipefail

say() { printf '\n>> %s\n' "$*"; }

if ! command -v cub >/dev/null 2>&1; then
  printf 'cub is not installed. Install it with:\n  curl -fsSL https://hub.confighub.com/cub/install.sh | bash\nthen add ~/.confighub/bin to your PATH and re-run this script.\n' >&2
  exit 1
fi

SPACE="${CUB_SPACE:-helm-trivy-operator-no-crds}"

say "Check ConfigHub auth"
if ! cub auth status >/dev/null 2>&1; then
  printf 'Not logged in. Run: cub auth login\nThen re-run this script.\n' >&2
  exit 1
fi

say "Render the no-crds preset into ./aqua-trivy-operator-0-32-1-no-crds"
cub installer setup --pull oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/aqua-trivy-operator:0.32.1 --base no-crds --work-dir ./aqua-trivy-operator-0-32-1-no-crds --non-interactive --namespace default

say "Upload the rendered objects to Space ${SPACE} (created on first upload)"
cub installer upload --work-dir ./aqua-trivy-operator-0-32-1-no-crds --space "${SPACE}"

say "Uploaded. See your Units:"
printf '  cub unit list --space %s\n  or open https://hub.confighub.com and find that Space.\n' "${SPACE}"

say "Next: create an environment variant and promote reviewed changes"
printf '  Walkthrough with the why behind each flag:\n  https://confighub.github.io/helm-expt/site/d/docs/user/variants-after-upload.html\n'

# Before applying this preset from ConfigHub to a cluster, it still needs:
#   - CRD clustercompliancereports.aquasecurity.github.io (suggested: kubectl apply -f <crd-manifest.yaml>)
#   - CRD clusterconfigauditreports.aquasecurity.github.io (suggested: kubectl apply -f <crd-manifest.yaml>)
#   - CRD clusterinfraassessmentreports.aquasecurity.github.io (suggested: kubectl apply -f <crd-manifest.yaml>)
#   - CRD clusterrbacassessmentreports.aquasecurity.github.io (suggested: kubectl apply -f <crd-manifest.yaml>)
#   - CRD clustersbomreports.aquasecurity.github.io (suggested: kubectl apply -f <crd-manifest.yaml>)
#   - CRD clustervulnerabilityreports.aquasecurity.github.io (suggested: kubectl apply -f <crd-manifest.yaml>)
#   - CRD configauditreports.aquasecurity.github.io (suggested: kubectl apply -f <crd-manifest.yaml>)
#   - CRD exposedsecretreports.aquasecurity.github.io (suggested: kubectl apply -f <crd-manifest.yaml>)
#   - CRD infraassessmentreports.aquasecurity.github.io (suggested: kubectl apply -f <crd-manifest.yaml>)
#   - CRD rbacassessmentreports.aquasecurity.github.io (suggested: kubectl apply -f <crd-manifest.yaml>)
#   - CRD sbomreports.aquasecurity.github.io (suggested: kubectl apply -f <crd-manifest.yaml>)
#   - CRD vulnerabilityreports.aquasecurity.github.io (suggested: kubectl apply -f <crd-manifest.yaml>)
