#!/usr/bin/env bash
# aqua/trivy-operator 0.32.1 - base variant: no-crds
# Path: pull the package, render this base variant locally, read the objects,
# then apply them with kubectl. No ConfigHub account is needed.
# Generated by scripts/generate-public-site.mjs from the committed package
# data for this base variant. Chart page: https://confighub.github.io/helm-expt/site/charts/aqua-trivy-operator-0-32-1.html
set -euo pipefail

say() { printf '\n>> %s\n' "$*"; }

if ! command -v cub >/dev/null 2>&1; then
  printf 'cub is not installed. Install the cub CLI with:\n  curl -fsSL https://hub.confighub.com/cub/install.sh | bash\nthen add ~/.confighub/bin to your PATH and re-run this script.\n' >&2
  exit 1
fi

# Installer is a cub plugin. Check it before this script does any work.
if ! cub installer --help >/dev/null 2>&1; then
  printf 'The cub installer plugin is missing. Follow https://confighub.github.io/helm-expt/site/try.html#install-cub, then re-run this script.\n' >&2
  exit 1
fi

if ! command -v kustomize >/dev/null 2>&1; then
  printf 'kustomize is missing. Follow https://confighub.github.io/helm-expt/site/try.html#install-cub, then re-run this script.\n' >&2
  exit 1
fi

if ! command -v kubectl >/dev/null 2>&1; then
  printf 'kubectl is required for the apply step.\n' >&2
  exit 1
fi

say "Pull the package and render the no-crds base variant into ./aqua-trivy-operator-0-32-1-no-crds"
cub installer setup --pull oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/aqua-trivy-operator:0.32.1 --base no-crds --work-dir ./aqua-trivy-operator-0-32-1-no-crds --non-interactive --namespace default

say "Read what was rendered; nothing has touched the cluster yet"
ls ./aqua-trivy-operator-0-32-1-no-crds/out/manifests

wait_for_crd() {
  crd_name="$1"
  deadline=$(( $(date +%s) + 180 ))
  until kubectl get "crd/${crd_name}" >/dev/null 2>&1; do
    if [ "$(date +%s)" -ge "$deadline" ]; then
      printf "CRD %s did not appear within 180 seconds.\n" "$crd_name" >&2
      return 1
    fi
    sleep 2
  done
  kubectl wait --for=condition=Established --timeout=120s "crd/${crd_name}"
}

say "Ensure the default namespace exists"
kubectl create namespace default --dry-run=client -o yaml | kubectl apply -f -

say "Check 12 CRDs included with this package"
missing_crds=0
if ! kubectl get crd/clustercompliancereports.aquasecurity.github.io >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/clusterconfigauditreports.aquasecurity.github.io >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/clusterinfraassessmentreports.aquasecurity.github.io >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/clusterrbacassessmentreports.aquasecurity.github.io >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/clustersbomreports.aquasecurity.github.io >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/clustervulnerabilityreports.aquasecurity.github.io >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/configauditreports.aquasecurity.github.io >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/exposedsecretreports.aquasecurity.github.io >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/infraassessmentreports.aquasecurity.github.io >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/rbacassessmentreports.aquasecurity.github.io >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/sbomreports.aquasecurity.github.io >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/vulnerabilityreports.aquasecurity.github.io >/dev/null 2>&1; then
  missing_crds=1
fi
if [ "$missing_crds" -eq 1 ]; then
  kubectl apply --server-side -f ./aqua-trivy-operator-0-32-1-no-crds/package/prerequisites/target-facts/no-crds-crds.yaml
else
  say "The required CRDs already exist; leave them under their current owner"
fi
wait_for_crd clustercompliancereports.aquasecurity.github.io
wait_for_crd clusterconfigauditreports.aquasecurity.github.io
wait_for_crd clusterinfraassessmentreports.aquasecurity.github.io
wait_for_crd clusterrbacassessmentreports.aquasecurity.github.io
wait_for_crd clustersbomreports.aquasecurity.github.io
wait_for_crd clustervulnerabilityreports.aquasecurity.github.io
wait_for_crd configauditreports.aquasecurity.github.io
wait_for_crd exposedsecretreports.aquasecurity.github.io
wait_for_crd infraassessmentreports.aquasecurity.github.io
wait_for_crd rbacassessmentreports.aquasecurity.github.io
wait_for_crd sbomreports.aquasecurity.github.io
wait_for_crd vulnerabilityreports.aquasecurity.github.io

if [ -d ./aqua-trivy-operator-0-32-1-no-crds/out/secrets ]; then
  say "Apply rendered Secrets first"
  kubectl apply -f ./aqua-trivy-operator-0-32-1-no-crds/out/secrets
fi

say "Apply the rendered objects"
kubectl apply -f ./aqua-trivy-operator-0-32-1-no-crds/out/manifests

say "Done. The cluster received exactly the files in ./aqua-trivy-operator-0-32-1-no-crds/out."
