#!/usr/bin/env bash
# aqua/trivy-operator 0.32.1 - base variant: no-crds
# Path: pull the package, render this base variant locally, read the objects,
# then apply them with kubectl. No ConfigHub account is needed.
# Generated by scripts/generate-public-site.mjs from the committed package
# data for this base variant. Chart page: https://confighub.github.io/helm-expt/site/charts/aqua-trivy-operator-0-32-1.html
set -euo pipefail

say() { printf '\n>> %s\n' "$*"; }

if ! command -v cub >/dev/null 2>&1; then
  printf 'cub is not installed. Install it with:\n  curl -fsSL https://hub.confighub.com/cub/install.sh | bash\nthen add ~/.confighub/bin to your PATH and re-run this script.\n' >&2
  exit 1
fi

# The installer subcommand is a plugin and is not in the public cub build
# yet. Stop here, before this script touches any cluster.
if ! cub installer --help >/dev/null 2>&1; then
  printf 'The cub installer command is a plugin that ships separately from the cub CLI and is not yet publicly available. The standard cub install script does not include it.\nThis cub build does not have it, so this script stops now, before any cluster work.\n' >&2
  exit 1
fi

if ! command -v kubectl >/dev/null 2>&1; then
  printf 'kubectl is required for the apply step.\n' >&2
  exit 1
fi

say "Pull the package and render the no-crds base variant into ./aqua-trivy-operator-0-32-1-no-crds"
cub installer setup --pull oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/aqua-trivy-operator:0.32.1 --base no-crds --work-dir ./aqua-trivy-operator-0-32-1-no-crds --non-interactive --namespace default

say "Read what was rendered; nothing has touched the cluster yet"
ls ./aqua-trivy-operator-0-32-1-no-crds/out/manifests

say "Ensure the default namespace exists"
kubectl create namespace default --dry-run=client -o yaml | kubectl apply -f -

if [ "${REQUIREMENTS_READY:-0}" != "1" ]; then
  cat >&2 <<'EOF_REQUIREMENTS'
This base variant needs resources you must create with your own values first:
  - CRD clustercompliancereports.aquasecurity.github.io
    kubectl apply -f <crd-manifest.yaml>
  - CRD clusterconfigauditreports.aquasecurity.github.io
    kubectl apply -f <crd-manifest.yaml>
  - CRD clusterinfraassessmentreports.aquasecurity.github.io
    kubectl apply -f <crd-manifest.yaml>
  - CRD clusterrbacassessmentreports.aquasecurity.github.io
    kubectl apply -f <crd-manifest.yaml>
  - CRD clustersbomreports.aquasecurity.github.io
    kubectl apply -f <crd-manifest.yaml>
  - CRD clustervulnerabilityreports.aquasecurity.github.io
    kubectl apply -f <crd-manifest.yaml>
  - CRD configauditreports.aquasecurity.github.io
    kubectl apply -f <crd-manifest.yaml>
  - CRD exposedsecretreports.aquasecurity.github.io
    kubectl apply -f <crd-manifest.yaml>
  - CRD infraassessmentreports.aquasecurity.github.io
    kubectl apply -f <crd-manifest.yaml>
  - CRD rbacassessmentreports.aquasecurity.github.io
    kubectl apply -f <crd-manifest.yaml>
  - CRD sbomreports.aquasecurity.github.io
    kubectl apply -f <crd-manifest.yaml>
  - CRD vulnerabilityreports.aquasecurity.github.io
    kubectl apply -f <crd-manifest.yaml>
Substitute the <...> placeholders and create these, then re-run with:
  REQUIREMENTS_READY=1 bash try.sh
EOF_REQUIREMENTS
  exit 1
fi

if [ -d ./aqua-trivy-operator-0-32-1-no-crds/out/secrets ]; then
  say "Apply rendered Secrets first"
  kubectl apply -f ./aqua-trivy-operator-0-32-1-no-crds/out/secrets
fi

say "Apply the rendered objects"
kubectl apply -f ./aqua-trivy-operator-0-32-1-no-crds/out/manifests

say "Done. The cluster received exactly the files in ./aqua-trivy-operator-0-32-1-no-crds/out."
