#!/usr/bin/env bash
# argo-cd/argo-cd 9.5.15 - preset: default
# Path: render this preset locally, then upload the objects to your
# ConfigHub Space as Units you can edit, diff, and deliver.
# Needs a ConfigHub account: run cub auth login once before this script.
# Generated by scripts/generate-public-site.mjs from the committed package
# data for this preset. Chart page: https://confighub.github.io/helm-expt/site/charts/argo-cd-argo-cd-9-5-15.html
set -euo pipefail

say() { printf '\n>> %s\n' "$*"; }

if ! command -v cub >/dev/null 2>&1; then
  printf 'cub is not installed. Install it with:\n  curl -fsSL https://hub.confighub.com/cub/install.sh | bash\nthen add ~/.confighub/bin to your PATH and re-run this script.\n' >&2
  exit 1
fi

SPACE="${CUB_SPACE:-helm-argo-cd-default}"

say "Check ConfigHub auth"
if ! cub auth status >/dev/null 2>&1; then
  printf 'Not logged in. Run: cub auth login\nThen re-run this script.\n' >&2
  exit 1
fi

say "Render the default preset into ./argo-cd-argo-cd-9-5-15-default"
cub installer setup --pull oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/argo-cd-argo-cd:9.5.15 --base default --work-dir ./argo-cd-argo-cd-9-5-15-default --non-interactive --namespace argocd

say "Upload the rendered objects to Space ${SPACE} (created on first upload)"
cub installer upload --work-dir ./argo-cd-argo-cd-9-5-15-default --space "${SPACE}"

say "Uploaded. See your Units:"
printf '  cub unit list --space %s\n  or open https://hub.confighub.com and find that Space.\n' "${SPACE}"

# Before applying this preset from ConfigHub to a cluster, it still needs:
#   - Secret argocd/argocd-redis key auth (suggested: kubectl -n argocd create secret generic argocd-redis --from-literal=auth=<value>)
