#!/usr/bin/env bash
# argo-cd/argo-cd 9.5.15 - base variant: default
# Path: pull the package, render this base variant locally, read the objects,
# then apply them with kubectl. No ConfigHub account is needed.
# Generated by scripts/generate-public-site.mjs from the committed package
# data for this base variant. Chart page: https://confighub.github.io/helm-expt/site/charts/argo-cd-argo-cd-9-5-15.html
set -euo pipefail

say() { printf '\n>> %s\n' "$*"; }

if ! command -v cub >/dev/null 2>&1; then
  printf 'cub is not installed. Install the cub CLI with:\n  curl -fsSL https://hub.confighub.com/cub/install.sh | bash\nthen add ~/.confighub/bin to your PATH and re-run this script.\n' >&2
  exit 1
fi

# Installer is a cub plugin. Check it before this script does any work.
if ! cub installer --help >/dev/null 2>&1; then
  printf 'The cub installer plugin is missing. Follow https://confighub.github.io/helm-expt/site/try.html#install-cub, then re-run this script.\n' >&2
  exit 1
fi

if ! command -v kustomize >/dev/null 2>&1; then
  printf 'kustomize is missing. Follow https://confighub.github.io/helm-expt/site/try.html#install-cub, then re-run this script.\n' >&2
  exit 1
fi

if ! command -v kubectl >/dev/null 2>&1; then
  printf 'kubectl is required for the apply step.\n' >&2
  exit 1
fi

say "Pull the package and render the default base variant into ./argo-cd-argo-cd-9-5-15-default"
cub installer setup --pull oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/argo-cd-argo-cd:9.5.15@sha256:9ec6bd1950e4b8b300ac61a62b85943a462dd7fc80d64e5bc79995f054c2ce4d --base default --work-dir ./argo-cd-argo-cd-9-5-15-default --non-interactive --namespace argocd

say "Read what was rendered; nothing has touched the cluster yet"
ls ./argo-cd-argo-cd-9-5-15-default/out/manifests

say "Ensure the argocd namespace exists"
kubectl create namespace argocd --dry-run=client -o yaml | kubectl apply -f -

if [ "${REQUIREMENTS_READY:-0}" != "1" ]; then
  cat >&2 <<'EOF_REQUIREMENTS'
This base variant needs resources you must create with your own values first:
  - Secret argocd/argocd-redis key auth
    kubectl -n argocd create secret generic argocd-redis --from-literal=auth=<value>
Complete these prerequisites before applying the rendered objects.
Replace any <...> placeholders with values or files for your environment.
When the resources exist, re-run with:
  REQUIREMENTS_READY=1 bash try.sh
EOF_REQUIREMENTS
  exit 1
fi

if [ -d ./argo-cd-argo-cd-9-5-15-default/out/secrets ]; then
  say "Apply rendered Secrets first"
  kubectl apply -f ./argo-cd-argo-cd-9-5-15-default/out/secrets
fi

say "Apply the rendered objects"
kubectl apply -f ./argo-cd-argo-cd-9-5-15-default/out/manifests

say "Done. The cluster received exactly the files in ./argo-cd-argo-cd-9-5-15-default/out."
