apiVersion: "helm-expt.confighub.com/v1alpha1"
kind: "InstallerPackageReceipt"
metadata:
  name: "grafana-alloy-1-8-2"
spec:
  chart:
    repository: "grafana"
    name: "alloy"
    version: "1.8.2"
  deterministicBundle:
    command: "cub installer package packages/grafana/alloy/1.8.2 -o <tmp>/grafana-alloy-1.8.2.tgz"
    sha256: "ca3141104f9da7a56a4b5ac332ea2018dd73309c7bf448e99221fd2b4c92a725"
    byteIdenticalAcrossTwoLocalBundles: true
  package:
    path: "packages/grafana/alloy/1.8.2"
    name: "grafana-alloy"
    version: "1.8.2"
    sourceFiles:
      -
        path: "README.md"
        sha256: "7780de4574a0aa72b84460ac68b3908d3b2d62b9b8c2246ceeb19d7c15156b2c"
        bytes: 193
      -
        path: "bases/default/kustomization.yaml"
        sha256: "44d52637f259f73730afd3a41d7350391387456ab7c418f201eec1ef73720153"
        bytes: 99
      -
        path: "bases/default/upstream.yaml"
        sha256: "984319325f620b099f091df4c45ef851f0dd7593526f146d5271dbf477f7f37b"
        bytes: 16691
      -
        path: "bases/no-crds/kustomization.yaml"
        sha256: "44d52637f259f73730afd3a41d7350391387456ab7c418f201eec1ef73720153"
        bytes: 99
      -
        path: "bases/no-crds/upstream.yaml"
        sha256: "3284915e4cee6101e8279e10a5ef11937e6d860b01b95549079d809f64a17e22"
        bytes: 6922
      -
        path: "installer.yaml"
        sha256: "7285a00edeb31d962ce88a9fefcb459f216f469d2bafc407293524dd35c4a4bb"
        bytes: 433
  setupChecks:
    -
      allowedCubOnlyObjects:
        - "v1|Namespace||default"
      base: "default"
      command: "cub installer setup --pull packages/grafana/alloy/1.8.2 --base default --work-dir <tmp> --non-interactive --namespace default"
      cubInstallObjectCountIncludingSupport: 8
      helmReleaseObjectCount: 7
      semanticObjectMatches: "7/7"
      separatedSecretCount: 0
      variant: "default"
    -
      variant: "no-crds"
      base: "no-crds"
      command: "cub installer setup --pull packages/grafana/alloy/1.8.2 --base no-crds --work-dir <tmp> --non-interactive --namespace default"
      helmReleaseObjectCount: 6
      cubInstallObjectCountIncludingSupport: 7
      semanticObjectMatches: "6/6"
      separatedSecretCount: 0
      allowedCubOnlyObjects:
        - "v1|Namespace||default"
