apiVersion: "helm-expt.confighub.com/v1alpha1"
kind: "Variant"
metadata:
  name: "default"
  labels:
    confighub.io/chart-ref: "argo-cd/argocd-image-updater"
    confighub.io/chart-version: "1.2.2"
    confighub.io/proof-tier: "next80-full"
    confighub.io/variant: "default"
spec:
  recipe: "../../recipe.yaml"
  namespace: "default"
  releaseName: "argocd-image-updater"
  valuesProfile: "../../effective-values.yaml"
  capabilityProfile:
    kubeVersion: "1.30.0"
    apiVersions:
      []
  hookPolicy: "no-hooks"
