#!/usr/bin/env bash
# elastic/filebeat 8.5.1 - base variant: node-or-cluster-collector
# Path: pull the package, render this base variant locally, read the objects,
# then apply them with kubectl. No ConfigHub account is needed.
# Generated by scripts/generate-public-site.mjs from the committed package
# data for this base variant. Chart page: https://confighub.github.io/helm-expt/site/charts/elastic-filebeat-8-5-1.html
set -euo pipefail

say() { printf '\n>> %s\n' "$*"; }

if ! command -v cub >/dev/null 2>&1; then
  printf 'cub is not installed. Install it with:\n  curl -fsSL https://hub.confighub.com/cub/install.sh | bash\nthen add ~/.confighub/bin to your PATH and re-run this script.\n' >&2
  exit 1
fi

if ! command -v kubectl >/dev/null 2>&1; then
  printf 'kubectl is required for the apply step.\n' >&2
  exit 1
fi

say "Pull the package and render the node-or-cluster-collector base variant into ./elastic-filebeat-8-5-1-node-or-cluster-collector"
cub installer setup --pull oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/elastic-filebeat:8.5.1 --base node-or-cluster-collector --work-dir ./elastic-filebeat-8-5-1-node-or-cluster-collector --non-interactive --namespace default

say "Read what was rendered; nothing has touched the cluster yet"
ls ./elastic-filebeat-8-5-1-node-or-cluster-collector/out/manifests

say "Ensure the default namespace exists"
kubectl create namespace default --dry-run=client -o yaml | kubectl apply -f -

if [ -d ./elastic-filebeat-8-5-1-node-or-cluster-collector/out/secrets ]; then
  say "Apply rendered Secrets first"
  kubectl apply -f ./elastic-filebeat-8-5-1-node-or-cluster-collector/out/secrets
fi

say "Apply the rendered objects"
kubectl apply -f ./elastic-filebeat-8-5-1-node-or-cluster-collector/out/manifests

say "Done. The cluster received exactly the files in ./elastic-filebeat-8-5-1-node-or-cluster-collector/out."
