#!/usr/bin/env bash
# metrics-server/metrics-server 3.13.0 - base variant: external-tls-ca
# Path: pull the package, render this base variant locally, read the objects,
# then apply them with kubectl. No ConfigHub account is needed.
# Generated by scripts/generate-public-site.mjs from the committed package
# data for this base variant. Chart page: https://confighub.github.io/helm-expt/site/charts/metrics-server-metrics-server-3-13-0.html
set -euo pipefail

say() { printf '\n>> %s\n' "$*"; }

if ! command -v cub >/dev/null 2>&1; then
  printf 'cub is not installed. Install it with:\n  curl -fsSL https://hub.confighub.com/cub/install.sh | bash\nthen add ~/.confighub/bin to your PATH and re-run this script.\n' >&2
  exit 1
fi

if ! cub installer --help >/dev/null 2>&1; then
  printf '%s\n' 'The cub installer command is not available. It is a cub plugin that is not yet publicly released. Watch https://github.com/confighub/installer for the public plugin release. This script stops before it touches your cluster.' >&2
  exit 1
fi

if ! command -v kubectl >/dev/null 2>&1; then
  printf 'kubectl is required for the apply step.\n' >&2
  exit 1
fi

say "Pull the package and render the external-tls-ca base variant into ./metrics-server-metrics-server-3-13-0-external-tls-ca"
cub installer setup --pull oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/metrics-server-metrics-server:3.13.0 --base external-tls-ca --work-dir ./metrics-server-metrics-server-3-13-0-external-tls-ca --non-interactive --namespace kube-system

say "Read what was rendered; nothing has touched the cluster yet"
ls ./metrics-server-metrics-server-3-13-0-external-tls-ca/out/manifests

say "Ensure the kube-system namespace exists"
kubectl create namespace kube-system --dry-run=client -o yaml | kubectl apply -f -

if [ "${REQUIREMENTS_READY:-0}" != "1" ]; then
  cat >&2 <<'EOF_REQUIREMENTS'
This base variant needs resources you must create with your own values first:
  - Secret kube-system/metrics-server-tls keys tls.crt,tls.key
    kubectl -n kube-system create secret generic metrics-server-tls --from-literal=tls.crt=<value> --from-literal=tls.key=<value>
Substitute the <...> placeholders and create these, then re-run with:
  REQUIREMENTS_READY=1 bash try.sh
EOF_REQUIREMENTS
  exit 1
fi

if [ -d ./metrics-server-metrics-server-3-13-0-external-tls-ca/out/secrets ]; then
  say "Apply rendered Secrets first"
  kubectl apply -f ./metrics-server-metrics-server-3-13-0-external-tls-ca/out/secrets
fi

say "Apply the rendered objects"
kubectl apply -f ./metrics-server-metrics-server-3-13-0-external-tls-ca/out/manifests

say "Done. The cluster received exactly the files in ./metrics-server-metrics-server-3-13-0-external-tls-ca/out."
