apiVersion: helm-expt.confighub.com/v1alpha1
kind: InstallerPackagePublicationReceipt
metadata:
  name: prometheus-community-alertmanager-1.37.0
spec:
  ref: oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/prometheus-community-alertmanager:1.37.0
  observedAt: "2026-08-26T07:02:32.690Z"
  package:
    path: packages/prometheus-community/alertmanager/1.37.0
    sha256: 6f7e5817f60ede7b313f99b32f58026f2b9fd181404006d5ffcf2bcd06b0fec6
    sourceTreeSHA256: b0908461fa6dfbe468592365a4200c15ea76769f37842e2b355036dc018e8eb8
  publicationAction: pushed-new
  commands:
    package: "cub installer package packages/prometheus-community/alertmanager/1.37.0 -o <tmp>/prometheus-community-alertmanager-1.37.0.tgz"
    push: "cub installer push <tmp>/prometheus-community-alertmanager-1.37.0.tgz oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/prometheus-community-alertmanager:1.37.0"
    inspect: "cub installer inspect oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/prometheus-community-alertmanager:1.37.0 --json"
  outputs:
    manifestDigest: sha256:f499807405ceea0ca49d34c4978dd905cfb5fcce36b53fbcb0f521260e78f04e
    layerDigest: sha256:6f7e5817f60ede7b313f99b32f58026f2b9fd181404006d5ffcf2bcd06b0fec6
    package: |
      Bundled prometheus-community-alertmanager@1.37.0
        output: <tmp>
        files:  12
        size:   6299 bytes
        digest: sha256:6f7e5817f60ede7b313f99b32f58026f2b9fd181404006d5ffcf2bcd06b0fec6
    push: |
      Pushed europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/prometheus-community-alertmanager:1.37.0
        manifest: sha256:f499807405ceea0ca49d34c4978dd905cfb5fcce36b53fbcb0f521260e78f04e
        layer:    sha256:6f7e5817f60ede7b313f99b32f58026f2b9fd181404006d5ffcf2bcd06b0fec6 (6299 bytes, 12 files)
    inspectJSONSHA256: 5ac451e889a451590f004cbd995d1da2a93aec6b53cba012d80de0427d532b93
    inspectJSONCanonicalSHA256: fd6156b4399bcb4c6b74147c6d1628bdb6d98107a7ebdd61d5973d0715d2485c
