apiVersion: "installer.confighub.com/v1alpha1"
kind: "Package"
metadata:
  name: "elastic-metricbeat"
  version: "8.5.1"
spec:
  bases:
    -
      name: "default"
      path: "bases/default"
      default: true
      description: "elastic/metricbeat default variant rendered from elastic/metricbeat@8.5.1"
