#!/usr/bin/env bash
# grafana/grafana 10.5.15 - base variant: existing-secret-ingress
# Path: pull the package, render this base variant locally, read the objects,
# then apply them with kubectl. No ConfigHub account is needed.
# Generated by scripts/generate-public-site.mjs from the committed package
# data for this base variant. Chart page: https://confighub.github.io/helm-expt/site/charts/grafana-grafana-10-5-15.html
set -euo pipefail

say() { printf '\n>> %s\n' "$*"; }

if ! command -v cub >/dev/null 2>&1; then
  printf 'cub is not installed. Install it with:\n  curl -fsSL https://hub.confighub.com/cub/install.sh | bash\nthen add ~/.confighub/bin to your PATH and re-run this script.\n' >&2
  exit 1
fi

if ! command -v kubectl >/dev/null 2>&1; then
  printf 'kubectl is required for the apply step.\n' >&2
  exit 1
fi

say "Pull the package and render the existing-secret-ingress base variant into ./grafana-grafana-10-5-15-existing-secret-ingress"
cub installer setup --pull oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/grafana-grafana:10.5.15 --base existing-secret-ingress --work-dir ./grafana-grafana-10-5-15-existing-secret-ingress --non-interactive --namespace grafana

say "Read what was rendered; nothing has touched the cluster yet"
ls ./grafana-grafana-10-5-15-existing-secret-ingress/out/manifests

say "Ensure the grafana namespace exists"
kubectl create namespace grafana --dry-run=client -o yaml | kubectl apply -f -

say "Requirement before apply: Secret grafana/grafana-admin keys admin-user,admin-password"
if ! kubectl -n grafana create secret generic grafana-admin --from-literal=admin-user=admin --from-literal=admin-password="$(openssl rand -base64 32)"; then
  printf '!! The requirement command failed. If the resource already exists, review it and re-run; otherwise fix the error above.\n' >&2
  exit 1
fi

if [ -d ./grafana-grafana-10-5-15-existing-secret-ingress/out/secrets ]; then
  say "Apply rendered Secrets first"
  kubectl apply -f ./grafana-grafana-10-5-15-existing-secret-ingress/out/secrets
fi

say "Apply the rendered objects"
kubectl apply -f ./grafana-grafana-10-5-15-existing-secret-ingress/out/manifests

say "Done. The cluster received exactly the files in ./grafana-grafana-10-5-15-existing-secret-ingress/out."
