apiVersion: "helm-expt.confighub.com/v1alpha1"
kind: "InstallerPackageReceipt"
metadata:
  name: "external-secrets-external-secrets-2.10.0"
spec:
  chart:
    name: "external-secrets"
    repository: "external-secrets"
    version: "2.10.0"
  deterministicBundle:
    byteIdenticalAcrossTwoLocalBundles: true
    command: "cub installer package packages/external-secrets/external-secrets/2.10.0 -o <tmp>/external-secrets-2.10.0.tgz"
    sha256: "c026ff36c6339e6f32fcb583fff9c63775057c9631e9af366bdc4bb7dd984664"
  package:
    name: "external-secrets-external-secrets"
    path: "packages/external-secrets/external-secrets/2.10.0"
    sourceFiles:
      -
        path: "README.md"
        sha256: "d219ef72e18b35d0227b37ca294af601979835aaf1fa35b619064f9bc56cacda"
        bytes: 335
      -
        path: "bases/default/kustomization.yaml"
        sha256: "44d52637f259f73730afd3a41d7350391387456ab7c418f201eec1ef73720153"
        bytes: 99
      -
        path: "bases/default/upstream.yaml"
        sha256: "5836924e6c7df634a86ae7fb6b35de5133778dab0afe1d0a25f9adde2187ee2e"
        bytes: 1995351
      -
        path: "bases/no-crds/kustomization.yaml"
        sha256: "44d52637f259f73730afd3a41d7350391387456ab7c418f201eec1ef73720153"
        bytes: 99
      -
        path: "bases/no-crds/upstream.yaml"
        sha256: "5bee43e3c91bccbe93e20fc0f9bd47fb08e5564cb0c1f932049039d7998d24f2"
        bytes: 22493
      -
        path: "collector/target-facts.sh"
        sha256: "911ab799552867c3b67c9ec924183ae5beccabb1f4034513ebcfe052b8406f4f"
        bytes: 11707
      -
        path: "installer.yaml"
        sha256: "7ebe729ed4296f22d855000a6bdd34c68d20e8ced3cf60da734c1873675c3db0"
        bytes: 8057
      -
        path: "prerequisites/target-facts/no-crds-crds.yaml"
        sha256: "4482df019b69cbbe8344f5e624ed5a284437b86844b056b56eaea653126e6f1a"
        bytes: 1828335
    version: "2.10.0"
  setupChecks:
    -
      allowedCubOnlyObjects:
        - "v1|Namespace||external-secrets"
      base: "default"
      command: "cub installer setup --pull packages/external-secrets/external-secrets/2.10.0 --base default --work-dir <tmp> --non-interactive --namespace external-secrets"
      cubInstallObjectCountIncludingSupport: 45
      helmReleaseObjectCount: 44
      semanticObjectMatches: "44/44"
      separatedSecretCount: 1
      targetFactMode: "collector-facts"
      targetFactsBound: true
      variant: "default"
    -
      allowedCubOnlyObjects:
        - "v1|Namespace||external-secrets"
      base: "no-crds"
      command: "cub installer setup --pull packages/external-secrets/external-secrets/2.10.0 --base no-crds --work-dir <tmp> --non-interactive --namespace external-secrets"
      cubInstallObjectCountIncludingSupport: 20
      helmReleaseObjectCount: 19
      semanticObjectMatches: "19/19"
      separatedSecretCount: 1
      targetFactMode: "collector-facts"
      targetFactsBound: true
      variant: "no-crds"
