#!/usr/bin/env bash
# bitnami/mongodb 19.0.7 - base variant: existing-secret-replicaset
# Path: pull the package, render this base variant locally, read the objects,
# then apply them with kubectl. No ConfigHub account is needed.
# Generated by scripts/generate-public-site.mjs from the committed package
# data for this base variant. Chart page: https://confighub.github.io/helm-expt/site/charts/bitnami-mongodb-19-0-7.html
set -euo pipefail

say() { printf '\n>> %s\n' "$*"; }

if ! command -v cub >/dev/null 2>&1; then
  printf 'cub is not installed. Install the cub CLI with:\n  curl -fsSL https://hub.confighub.com/cub/install.sh | bash\nthen add ~/.confighub/bin to your PATH and re-run this script.\n' >&2
  exit 1
fi

# Public cub releases include the installer command. This guard catches
# an older or incomplete CLI before this script does any work.
if ! cub installer --help >/dev/null 2>&1; then
  printf 'This cub build does not include cub installer. Install or upgrade the cub CLI with:\n  curl -fsSL https://hub.confighub.com/cub/install.sh | bash\nthen add ~/.confighub/bin to your PATH and re-run this script.\n' >&2
  exit 1
fi

if ! command -v kubectl >/dev/null 2>&1; then
  printf 'kubectl is required for the apply step.\n' >&2
  exit 1
fi

say "Pull the package and render the existing-secret-replicaset base variant into ./bitnami-mongodb-19-0-7-existing-secret-replicaset"
cub installer setup --pull oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/bitnami-mongodb:19.0.7 --base existing-secret-replicaset --work-dir ./bitnami-mongodb-19-0-7-existing-secret-replicaset --non-interactive --namespace mongodb

say "Read what was rendered; nothing has touched the cluster yet"
ls ./bitnami-mongodb-19-0-7-existing-secret-replicaset/out/manifests

say "Ensure the mongodb namespace exists"
kubectl create namespace mongodb --dry-run=client -o yaml | kubectl apply -f -

say "Requirement before apply: Secret mongodb/mongodb-auth keys mongodb-root-password,mongodb-replica-set-key"
if ! kubectl -n mongodb create secret generic mongodb-auth --from-literal=mongodb-root-password="$(openssl rand -base64 32)" --from-literal=mongodb-replica-set-key="$(openssl rand -base64 48)"; then
  printf '!! The requirement command failed. If the resource already exists, review it and re-run; otherwise fix the error above.\n' >&2
  exit 1
fi

if [ -d ./bitnami-mongodb-19-0-7-existing-secret-replicaset/out/secrets ]; then
  say "Apply rendered Secrets first"
  kubectl apply -f ./bitnami-mongodb-19-0-7-existing-secret-replicaset/out/secrets
fi

say "Apply the rendered objects"
kubectl apply -f ./bitnami-mongodb-19-0-7-existing-secret-replicaset/out/manifests

say "Done. The cluster received exactly the files in ./bitnami-mongodb-19-0-7-existing-secret-replicaset/out."
