apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2026-06-11T03:46:28Z"
  labels:
    kubernetes.io/metadata.name: gatekeeper-lifecycle-check-upgrade
  name: gatekeeper-lifecycle-check-upgrade
  uid: e00ba1b6-671c-4d8c-a2c4-d4fddc14a7ca
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
