apiVersion: "installer.confighub.com/v1alpha1"
kind: "Package"
metadata:
  name: "bitnami-mysql"
  version: "14.0.3"
spec:
  bases:
    -
      name: "generated-passwords"
      path: "bases/generated-passwords"
      default: true
      description: "mysql generated passwords variant rendered from bitnami/mysql@14.0.3"
    -
      name: "existing-secret"
      path: "bases/existing-secret"
      description: "mysql existing Secret variant rendered from bitnami/mysql@14.0.3"
