#!/usr/bin/env bash
# bitnami/rabbitmq 16.0.14 - preset: existing-secret
# Path: render this preset locally, then upload the objects to your
# ConfigHub Space as Units you can edit, diff, and deliver.
# Needs a ConfigHub account: run cub auth login once before this script.
# Generated by scripts/generate-public-site.mjs from the committed package
# data for this preset. Chart page: https://confighub.github.io/helm-expt/site/charts/bitnami-rabbitmq-16-0-14.html
set -euo pipefail

say() { printf '\n>> %s\n' "$*"; }

if ! command -v cub >/dev/null 2>&1; then
  printf 'cub is not installed. Install it with:\n  curl -fsSL https://hub.confighub.com/cub/install.sh | bash\nthen add ~/.confighub/bin to your PATH and re-run this script.\n' >&2
  exit 1
fi

SPACE="${CUB_SPACE:-helm-rabbitmq-existing-secret}"

say "Check ConfigHub auth"
if ! cub auth status >/dev/null 2>&1; then
  printf 'Not logged in. Run: cub auth login\nThen re-run this script.\n' >&2
  exit 1
fi

say "Render the existing-secret preset into ./bitnami-rabbitmq-16-0-14-existing-secret"
cub installer setup --pull oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/bitnami-rabbitmq:16.0.14 --base existing-secret --work-dir ./bitnami-rabbitmq-16-0-14-existing-secret --non-interactive --namespace rabbitmq

say "Upload the rendered objects to Space ${SPACE} (created on first upload)"
cub installer upload --work-dir ./bitnami-rabbitmq-16-0-14-existing-secret --space "${SPACE}"

say "Uploaded. See your Units:"
printf '  cub unit list --space %s\n  or open https://hub.confighub.com and find that Space.\n' "${SPACE}"

say "Next: create an environment variant and promote reviewed changes"
printf '  Walkthrough with the why behind each flag:\n  https://confighub.github.io/helm-expt/site/d/docs/user/variants-after-upload.html\n'

# Before applying this preset from ConfigHub to a cluster, it still needs:
#   - Secret rabbitmq/rabbitmq-auth key rabbitmq-password (suggested: kubectl -n rabbitmq create secret generic rabbitmq-auth --from-literal=rabbitmq-password="$(openssl rand -base64 32)")
#   - Secret rabbitmq/rabbitmq-erlang-cookie key rabbitmq-erlang-cookie (suggested: kubectl -n rabbitmq create secret generic rabbitmq-erlang-cookie --from-literal=rabbitmq-erlang-cookie="$(openssl rand -base64 48)")
