#!/usr/bin/env bash
# karpenter/karpenter 1.14.0 - base variant: crds-managed
# Path: render this base variant locally, then upload the objects to your
# ConfigHub Space as Units you can edit, diff, and deliver.
# Needs a ConfigHub account: run cub auth login once before this script.
# Generated by scripts/generate-public-site.mjs from the committed package
# data for this base variant. Chart page: https://confighub.github.io/helm-expt/site/charts/karpenter-karpenter-1-14-0.html
set -euo pipefail

say() { printf '\n>> %s\n' "$*"; }

if ! command -v cub >/dev/null 2>&1; then
  printf 'cub is not installed. Install the cub CLI with:\n  curl -fsSL https://hub.confighub.com/cub/install.sh | bash\nthen add ~/.confighub/bin to your PATH and re-run this script.\n' >&2
  exit 1
fi

# Installer is a cub plugin. Check it before this script does any work.
if ! cub installer --help >/dev/null 2>&1; then
  printf 'The cub installer plugin is missing. Follow https://confighub.github.io/helm-expt/site/try.html#install-cub, then re-run this script.\n' >&2
  exit 1
fi

if ! command -v kustomize >/dev/null 2>&1; then
  printf 'kustomize is missing. Follow https://confighub.github.io/helm-expt/site/try.html#install-cub, then re-run this script.\n' >&2
  exit 1
fi

SPACE="${CUB_SPACE:-helm-karpenter-crds-managed}"

say "Check ConfigHub auth"
if ! cub auth status >/dev/null 2>&1; then
  printf 'Not logged in. Run: cub auth login\nThen re-run this script.\n' >&2
  exit 1
fi

say "Render the crds-managed base variant into ./karpenter-karpenter-1-14-0-crds-managed"
cub installer setup --pull oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/karpenter-karpenter:1.14.0@sha256:9df71774cdd0dec1b03d8f417d28176833a14f1bb3d094e01502f46101e777cc --base crds-managed --work-dir ./karpenter-karpenter-1-14-0-crds-managed --non-interactive --namespace kube-system

say "Upload the rendered objects to Space ${SPACE} (created on first upload)"
cub installer upload --work-dir ./karpenter-karpenter-1-14-0-crds-managed --space "${SPACE}"

say "Uploaded. See your Units:"
printf '  cub unit list --space %s\n  or open https://hub.confighub.com and find that Space.\n' "${SPACE}"

say "Next: create an environment variant and promote reviewed changes"
printf '  Walkthrough with the why behind each flag:\n  https://confighub.github.io/helm-expt/site/d/docs/user/variants-after-upload.html\n'

# Before applying this base variant from ConfigHub to a cluster, it still needs:
#   - CRD capacitybuffers.autoscaling.x-k8s.io (included in the package as prerequisites/target-facts/crds-managed-crds.yaml)
#   - CRD ec2nodeclasses.karpenter.k8s.aws (included in the package as prerequisites/target-facts/crds-managed-crds.yaml)
#   - CRD nodeclaims.karpenter.sh (included in the package as prerequisites/target-facts/crds-managed-crds.yaml)
#   - CRD nodeoverlays.karpenter.sh (included in the package as prerequisites/target-facts/crds-managed-crds.yaml)
#   - CRD nodepools.karpenter.sh (included in the package as prerequisites/target-facts/crds-managed-crds.yaml)
#   - minimum schedulable nodes 1 (suggested: use a target with at least 1 schedulable nodes before applying this base)
