#!/usr/bin/env bash
# ingress-nginx/ingress-nginx 4.15.1 - preset: default
# Path: render this preset locally, then upload the objects to your
# ConfigHub Space as Units you can edit, diff, and deliver.
# Needs a ConfigHub account: run cub auth login once before this script.
# Generated by scripts/generate-public-site.mjs from the committed package
# data for this preset. Chart page: https://confighub.github.io/helm-expt/site/charts/ingress-nginx-ingress-nginx-4-15-1.html
set -euo pipefail

say() { printf '\n>> %s\n' "$*"; }

if ! command -v cub >/dev/null 2>&1; then
  printf 'cub is not installed. Install it with:\n  curl -fsSL https://hub.confighub.com/cub/install.sh | bash\nthen add ~/.confighub/bin to your PATH and re-run this script.\n' >&2
  exit 1
fi

SPACE="${CUB_SPACE:-helm-ingress-nginx-default}"

say "Check ConfigHub auth"
if ! cub auth status >/dev/null 2>&1; then
  printf 'Not logged in. Run: cub auth login\nThen re-run this script.\n' >&2
  exit 1
fi

say "Render the default preset into ./ingress-nginx-ingress-nginx-4-15-1-default"
cub installer setup --pull oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/ingress-nginx-ingress-nginx:4.15.1 --base default --work-dir ./ingress-nginx-ingress-nginx-4-15-1-default --non-interactive --namespace ingress-nginx

say "Upload the rendered objects to Space ${SPACE} (created on first upload)"
cub installer upload --work-dir ./ingress-nginx-ingress-nginx-4-15-1-default --space "${SPACE}"

say "Uploaded. See your Units:"
printf '  cub unit list --space %s\n  or open https://hub.confighub.com and find that Space.\n' "${SPACE}"

# Before applying this preset from ConfigHub to a cluster, it still needs:
#   - Secret ingress-nginx/ingress-nginx-admission keys cert,key,ca (suggested: kubectl -n ingress-nginx create secret generic ingress-nginx-admission --from-literal=cert=<value> --from-literal=key=<value> --from-literal=ca=<value>)
