apiVersion: "helm-expt.confighub.com/v1alpha1"
kind: "EffectiveValues"
metadata:
  name: "aws-controllers-k8s-iam-chart-1.7.3-eks-inference"
spec:
  files:
    -
      path: "effective-values-eks-inference.yaml"
      source: "inline-proof"
      sha256: "67260e5272fe60b5341dc37b6633b2b3b1713ad63028b18649e27ddc04f0ed2d"
  mergedValuesCaptured: false
  values:
    aws:
      credentials:
        profile: "default"
        secretKey: "credentials"
        secretName: "aws-creds"
      region: "confighubplaceholder"
    deletionPolicy: "retain"
    installScope: "cluster"
    log:
      level: "info"
    metrics:
      service:
        create: false
