#!/usr/bin/env bash
# prometheus-community/kube-prometheus-stack 85.3.3 - base variant: no-crds
# Path: pull the package, render this base variant locally, read the objects,
# then apply them with kubectl. No ConfigHub account is needed.
# Generated by scripts/generate-public-site.mjs from the committed package
# data for this base variant. Chart page: https://confighub.github.io/helm-expt/site/charts/prometheus-community-kube-prometheus-stack-85-3-3.html
set -euo pipefail

say() { printf '\n>> %s\n' "$*"; }

if ! command -v cub >/dev/null 2>&1; then
  printf 'cub is not installed. Install the cub CLI with:\n  curl -fsSL https://hub.confighub.com/cub/install.sh | bash\nthen add ~/.confighub/bin to your PATH and re-run this script.\n' >&2
  exit 1
fi

# Installer is a cub plugin. Check it before this script does any work.
if ! cub installer --help >/dev/null 2>&1; then
  printf 'The cub installer plugin is missing. Follow https://confighub.github.io/helm-expt/site/try.html#install-cub, then re-run this script.\n' >&2
  exit 1
fi

if ! command -v kustomize >/dev/null 2>&1; then
  printf 'kustomize is missing. Follow https://confighub.github.io/helm-expt/site/try.html#install-cub, then re-run this script.\n' >&2
  exit 1
fi

if ! command -v kubectl >/dev/null 2>&1; then
  printf 'kubectl is required for the apply step.\n' >&2
  exit 1
fi

say "Pull the package and render the no-crds base variant into ./prometheus-community-kube-prometheus-stack-85-3-3-no-crds"
cub installer setup --pull oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/prometheus-community-kube-prometheus-stack:85.3.3 --base no-crds --work-dir ./prometheus-community-kube-prometheus-stack-85-3-3-no-crds --non-interactive --namespace monitoring

say "Read what was rendered; nothing has touched the cluster yet"
ls ./prometheus-community-kube-prometheus-stack-85-3-3-no-crds/out/manifests

say "Ensure the monitoring namespace exists"
kubectl create namespace monitoring --dry-run=client -o yaml | kubectl apply -f -

say "Check 10 CRDs included with this package"
missing_crds=0
if ! kubectl get crd/alertmanagerconfigs.monitoring.coreos.com >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/alertmanagers.monitoring.coreos.com >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/podmonitors.monitoring.coreos.com >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/probes.monitoring.coreos.com >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/prometheusagents.monitoring.coreos.com >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/prometheuses.monitoring.coreos.com >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/prometheusrules.monitoring.coreos.com >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/scrapeconfigs.monitoring.coreos.com >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/servicemonitors.monitoring.coreos.com >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/thanosrulers.monitoring.coreos.com >/dev/null 2>&1; then
  missing_crds=1
fi
if [ "$missing_crds" -eq 1 ]; then
  kubectl apply --server-side -f ./prometheus-community-kube-prometheus-stack-85-3-3-no-crds/package/prerequisites/target-facts/no-crds-crds.yaml
else
  say "The required CRDs already exist; leave them under their current owner"
fi
kubectl wait --for=condition=Established --timeout=120s crd/alertmanagerconfigs.monitoring.coreos.com
kubectl wait --for=condition=Established --timeout=120s crd/alertmanagers.monitoring.coreos.com
kubectl wait --for=condition=Established --timeout=120s crd/podmonitors.monitoring.coreos.com
kubectl wait --for=condition=Established --timeout=120s crd/probes.monitoring.coreos.com
kubectl wait --for=condition=Established --timeout=120s crd/prometheusagents.monitoring.coreos.com
kubectl wait --for=condition=Established --timeout=120s crd/prometheuses.monitoring.coreos.com
kubectl wait --for=condition=Established --timeout=120s crd/prometheusrules.monitoring.coreos.com
kubectl wait --for=condition=Established --timeout=120s crd/scrapeconfigs.monitoring.coreos.com
kubectl wait --for=condition=Established --timeout=120s crd/servicemonitors.monitoring.coreos.com
kubectl wait --for=condition=Established --timeout=120s crd/thanosrulers.monitoring.coreos.com

if [ "${REQUIREMENTS_READY:-0}" != "1" ]; then
  cat >&2 <<'EOF_REQUIREMENTS'
This base variant needs resources you must create with your own values first:
  - Secret monitoring/kube-prometheus-stack-admission keys cert,key
    kubectl -n monitoring create secret generic kube-prometheus-stack-admission --from-literal=cert=<value> --from-literal=key=<value>
Complete these prerequisites before applying the rendered objects.
Replace any <...> placeholders with values or files for your environment.
When the resources exist, re-run with:
  REQUIREMENTS_READY=1 bash try.sh
EOF_REQUIREMENTS
  exit 1
fi

if [ -d ./prometheus-community-kube-prometheus-stack-85-3-3-no-crds/out/secrets ]; then
  say "Apply rendered Secrets first"
  kubectl apply -f ./prometheus-community-kube-prometheus-stack-85-3-3-no-crds/out/secrets
fi

say "Apply the rendered objects"
kubectl apply -f ./prometheus-community-kube-prometheus-stack-85-3-3-no-crds/out/manifests

say "Done. The cluster received exactly the files in ./prometheus-community-kube-prometheus-stack-85-3-3-no-crds/out."
