#!/usr/bin/env bash
# external-secrets/external-secrets 2.5.0 - base variant: no-crds
# Path: pull the package, render this base variant locally, read the objects,
# then apply them with kubectl. No ConfigHub account is needed.
# Generated by scripts/generate-public-site.mjs from the committed package
# data for this base variant. Chart page: https://confighub.github.io/helm-expt/site/charts/external-secrets-external-secrets-2-5-0.html
set -euo pipefail

say() { printf '\n>> %s\n' "$*"; }

if ! command -v cub >/dev/null 2>&1; then
  printf 'cub is not installed. Install it with:\n  curl -fsSL https://hub.confighub.com/cub/install.sh | bash\nthen add ~/.confighub/bin to your PATH and re-run this script.\n' >&2
  exit 1
fi

# The installer subcommand is a plugin and is not in the public cub build
# yet. Stop here, before this script touches any cluster.
if ! cub installer --help >/dev/null 2>&1; then
  printf 'The cub installer command is a plugin that ships separately from the cub CLI and is not yet publicly available. The standard cub install script does not include it.\nThis cub build does not have it, so this script stops now, before any cluster work.\n' >&2
  exit 1
fi

if ! command -v kubectl >/dev/null 2>&1; then
  printf 'kubectl is required for the apply step.\n' >&2
  exit 1
fi

say "Pull the package and render the no-crds base variant into ./external-secrets-external-secrets-2-5-0-no-crds"
cub installer setup --pull oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/external-secrets-external-secrets:2.5.0 --base no-crds --work-dir ./external-secrets-external-secrets-2-5-0-no-crds --non-interactive --namespace external-secrets

say "Read what was rendered; nothing has touched the cluster yet"
ls ./external-secrets-external-secrets-2-5-0-no-crds/out/manifests

say "Ensure the external-secrets namespace exists"
kubectl create namespace external-secrets --dry-run=client -o yaml | kubectl apply -f -

if [ "${REQUIREMENTS_READY:-0}" != "1" ]; then
  cat >&2 <<'EOF_REQUIREMENTS'
This base variant needs resources you must create with your own values first:
  - Secret external-secrets/external-secrets-webhook
    kubectl -n external-secrets apply -f <work-dir>/out/secrets/secret-external-secrets-external-secrets-webhook.yaml
  - CRD acraccesstokens.generators.external-secrets.io
    kubectl apply -f <crd-manifest.yaml>
  - CRD cloudsmithaccesstokens.generators.external-secrets.io
    kubectl apply -f <crd-manifest.yaml>
  - CRD clusterexternalsecrets.external-secrets.io
    kubectl apply -f <crd-manifest.yaml>
  - CRD clustergenerators.generators.external-secrets.io
    kubectl apply -f <crd-manifest.yaml>
  - CRD clusterpushsecrets.external-secrets.io
    kubectl apply -f <crd-manifest.yaml>
  - CRD clustersecretstores.external-secrets.io
    kubectl apply -f <crd-manifest.yaml>
  - CRD ecrauthorizationtokens.generators.external-secrets.io
    kubectl apply -f <crd-manifest.yaml>
  - CRD externalsecrets.external-secrets.io
    kubectl apply -f <crd-manifest.yaml>
  - CRD fakes.generators.external-secrets.io
    kubectl apply -f <crd-manifest.yaml>
  - CRD gcraccesstokens.generators.external-secrets.io
    kubectl apply -f <crd-manifest.yaml>
  - CRD generatorstates.generators.external-secrets.io
    kubectl apply -f <crd-manifest.yaml>
  - CRD githubaccesstokens.generators.external-secrets.io
    kubectl apply -f <crd-manifest.yaml>
  - CRD grafanas.generators.external-secrets.io
    kubectl apply -f <crd-manifest.yaml>
  - CRD mfas.generators.external-secrets.io
    kubectl apply -f <crd-manifest.yaml>
  - CRD passwords.generators.external-secrets.io
    kubectl apply -f <crd-manifest.yaml>
  - CRD pushsecrets.external-secrets.io
    kubectl apply -f <crd-manifest.yaml>
  - CRD quayaccesstokens.generators.external-secrets.io
    kubectl apply -f <crd-manifest.yaml>
  - CRD secretstores.external-secrets.io
    kubectl apply -f <crd-manifest.yaml>
  - CRD sshkeys.generators.external-secrets.io
    kubectl apply -f <crd-manifest.yaml>
  - CRD stssessiontokens.generators.external-secrets.io
    kubectl apply -f <crd-manifest.yaml>
  - CRD uuids.generators.external-secrets.io
    kubectl apply -f <crd-manifest.yaml>
  - CRD vaultdynamicsecrets.generators.external-secrets.io
    kubectl apply -f <crd-manifest.yaml>
  - CRD webhooks.generators.external-secrets.io
    kubectl apply -f <crd-manifest.yaml>
Substitute the <...> placeholders and create these, then re-run with:
  REQUIREMENTS_READY=1 bash try.sh
EOF_REQUIREMENTS
  exit 1
fi

if [ -d ./external-secrets-external-secrets-2-5-0-no-crds/out/secrets ]; then
  say "Apply rendered Secrets first"
  kubectl apply -f ./external-secrets-external-secrets-2-5-0-no-crds/out/secrets
fi

say "Apply the rendered objects"
kubectl apply -f ./external-secrets-external-secrets-2-5-0-no-crds/out/manifests

say "Done. The cluster received exactly the files in ./external-secrets-external-secrets-2-5-0-no-crds/out."
