apiVersion: "helm-expt.confighub.com/v1alpha1"
kind: "HelmEquivalenceReceipt"
metadata:
  name: "ha-r001"
  labels:
    confighub.io/chart: "bitnami/opensearch"
    confighub.io/version: "2.0.10"
    confighub.io/variant: "ha"
spec:
  result: "pass"
  regularHelm:
    renderedSHA256: "c419606d1875905b2e84126b7b1d5d33c18f7cf34c0dd8048ba6e9221db36564"
    objectCount: 18
  cubInstall:
    objectCountIncludingSupport: 19
    semanticObjectMatches: "18/18"
    allowedCubOnlyObjects:
      - "v1|Namespace||default"
