#!/usr/bin/env bash
# kyverno/kyverno 3.8.1 - base variant: no-crds
# Path: pull the package, render this base variant locally, read the objects,
# then apply them with kubectl. No ConfigHub account is needed.
# Generated by scripts/generate-public-site.mjs from the committed package
# data for this base variant. Chart page: https://confighub.github.io/helm-expt/site/charts/kyverno-kyverno-3-8-1.html
set -euo pipefail

say() { printf '\n>> %s\n' "$*"; }

if ! command -v cub >/dev/null 2>&1; then
  printf 'cub is not installed. Install the cub CLI with:\n  curl -fsSL https://hub.confighub.com/cub/install.sh | bash\nthen add ~/.confighub/bin to your PATH and re-run this script.\n' >&2
  exit 1
fi

# Installer is a cub plugin. Check it before this script does any work.
if ! cub installer --help >/dev/null 2>&1; then
  printf 'The cub installer plugin is missing. Follow https://confighub.github.io/helm-expt/site/try.html#install-cub, then re-run this script.\n' >&2
  exit 1
fi

if ! command -v kustomize >/dev/null 2>&1; then
  printf 'kustomize is missing. Follow https://confighub.github.io/helm-expt/site/try.html#install-cub, then re-run this script.\n' >&2
  exit 1
fi

if ! command -v kubectl >/dev/null 2>&1; then
  printf 'kubectl is required for the apply step.\n' >&2
  exit 1
fi

say "Pull the package and render the no-crds base variant into ./kyverno-kyverno-3-8-1-no-crds"
cub installer setup --pull oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/kyverno-kyverno:3.8.1 --base no-crds --work-dir ./kyverno-kyverno-3-8-1-no-crds --non-interactive --namespace default

say "Read what was rendered; nothing has touched the cluster yet"
ls ./kyverno-kyverno-3-8-1-no-crds/out/manifests

say "Ensure the default namespace exists"
kubectl create namespace default --dry-run=client -o yaml | kubectl apply -f -

if [ "${REQUIREMENTS_READY:-0}" != "1" ]; then
  cat >&2 <<'EOF_REQUIREMENTS'
This base variant needs resources you must create with your own values first:
  - CRD cleanuppolicies.kyverno.io
    kubectl apply -f <crd-manifest.yaml>
  - CRD clustercleanuppolicies.kyverno.io
    kubectl apply -f <crd-manifest.yaml>
  - CRD clusterpolicies.kyverno.io
    kubectl apply -f <crd-manifest.yaml>
  - CRD globalcontextentries.kyverno.io
    kubectl apply -f <crd-manifest.yaml>
  - CRD policies.kyverno.io
    kubectl apply -f <crd-manifest.yaml>
  - CRD policyexceptions.kyverno.io
    kubectl apply -f <crd-manifest.yaml>
  - CRD updaterequests.kyverno.io
    kubectl apply -f <crd-manifest.yaml>
  - CRD clusterephemeralreports.reports.kyverno.io
    kubectl apply -f <crd-manifest.yaml>
  - CRD ephemeralreports.reports.kyverno.io
    kubectl apply -f <crd-manifest.yaml>
  - CRD clusterpolicyreports.wgpolicyk8s.io
    kubectl apply -f <crd-manifest.yaml>
  - CRD policyreports.wgpolicyk8s.io
    kubectl apply -f <crd-manifest.yaml>
  - CRD deletingpolicies.policies.kyverno.io
    kubectl apply -f <crd-manifest.yaml>
  - CRD generatingpolicies.policies.kyverno.io
    kubectl apply -f <crd-manifest.yaml>
  - CRD imagevalidatingpolicies.policies.kyverno.io
    kubectl apply -f <crd-manifest.yaml>
  - CRD mutatingpolicies.policies.kyverno.io
    kubectl apply -f <crd-manifest.yaml>
  - CRD namespaceddeletingpolicies.policies.kyverno.io
    kubectl apply -f <crd-manifest.yaml>
  - CRD namespacedgeneratingpolicies.policies.kyverno.io
    kubectl apply -f <crd-manifest.yaml>
  - CRD namespacedimagevalidatingpolicies.policies.kyverno.io
    kubectl apply -f <crd-manifest.yaml>
  - CRD namespacedmutatingpolicies.policies.kyverno.io
    kubectl apply -f <crd-manifest.yaml>
  - CRD namespacedvalidatingpolicies.policies.kyverno.io
    kubectl apply -f <crd-manifest.yaml>
  - CRD policyexceptions.policies.kyverno.io
    kubectl apply -f <crd-manifest.yaml>
  - CRD validatingpolicies.policies.kyverno.io
    kubectl apply -f <crd-manifest.yaml>
Substitute the <...> placeholders and create these, then re-run with:
  REQUIREMENTS_READY=1 bash try.sh
EOF_REQUIREMENTS
  exit 1
fi

if [ -d ./kyverno-kyverno-3-8-1-no-crds/out/secrets ]; then
  say "Apply rendered Secrets first"
  kubectl apply -f ./kyverno-kyverno-3-8-1-no-crds/out/secrets
fi

say "Apply the rendered objects"
kubectl apply -f ./kyverno-kyverno-3-8-1-no-crds/out/manifests

say "Done. The cluster received exactly the files in ./kyverno-kyverno-3-8-1-no-crds/out."
