#!/usr/bin/env bash
# kyverno/kyverno 3.8.1 - base variant: no-crds
# Path: pull the package, render this base variant locally, read the objects,
# then apply them with kubectl. No ConfigHub account is needed.
# Generated by scripts/generate-public-site.mjs from the committed package
# data for this base variant. Chart page: https://confighub.github.io/helm-expt/site/charts/kyverno-kyverno-3-8-1.html
set -euo pipefail

say() { printf '\n>> %s\n' "$*"; }

if ! command -v cub >/dev/null 2>&1; then
  printf 'cub is not installed. Install the cub CLI with:\n  curl -fsSL https://hub.confighub.com/cub/install.sh | bash\nthen add ~/.confighub/bin to your PATH and re-run this script.\n' >&2
  exit 1
fi

# Installer is a cub plugin. Check it before this script does any work.
if ! cub installer --help >/dev/null 2>&1; then
  printf 'The cub installer plugin is missing. Follow https://confighub.github.io/helm-expt/site/try.html#install-cub, then re-run this script.\n' >&2
  exit 1
fi

if ! command -v kustomize >/dev/null 2>&1; then
  printf 'kustomize is missing. Follow https://confighub.github.io/helm-expt/site/try.html#install-cub, then re-run this script.\n' >&2
  exit 1
fi

if ! command -v kubectl >/dev/null 2>&1; then
  printf 'kubectl is required for the apply step.\n' >&2
  exit 1
fi

say "Pull the package and render the no-crds base variant into ./kyverno-kyverno-3-8-1-no-crds"
cub installer setup --pull oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/kyverno-kyverno:3.8.1 --base no-crds --work-dir ./kyverno-kyverno-3-8-1-no-crds --non-interactive --namespace default

say "Read what was rendered; nothing has touched the cluster yet"
ls ./kyverno-kyverno-3-8-1-no-crds/out/manifests

say "Ensure the default namespace exists"
kubectl create namespace default --dry-run=client -o yaml | kubectl apply -f -

say "Check 22 CRDs included with this package"
missing_crds=0
if ! kubectl get crd/cleanuppolicies.kyverno.io >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/clustercleanuppolicies.kyverno.io >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/clusterpolicies.kyverno.io >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/globalcontextentries.kyverno.io >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/policies.kyverno.io >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/policyexceptions.kyverno.io >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/updaterequests.kyverno.io >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/clusterephemeralreports.reports.kyverno.io >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/ephemeralreports.reports.kyverno.io >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/clusterpolicyreports.wgpolicyk8s.io >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/policyreports.wgpolicyk8s.io >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/deletingpolicies.policies.kyverno.io >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/generatingpolicies.policies.kyverno.io >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/imagevalidatingpolicies.policies.kyverno.io >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/mutatingpolicies.policies.kyverno.io >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/namespaceddeletingpolicies.policies.kyverno.io >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/namespacedgeneratingpolicies.policies.kyverno.io >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/namespacedimagevalidatingpolicies.policies.kyverno.io >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/namespacedmutatingpolicies.policies.kyverno.io >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/namespacedvalidatingpolicies.policies.kyverno.io >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/policyexceptions.policies.kyverno.io >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/validatingpolicies.policies.kyverno.io >/dev/null 2>&1; then
  missing_crds=1
fi
if [ "$missing_crds" -eq 1 ]; then
  kubectl apply --server-side -f ./kyverno-kyverno-3-8-1-no-crds/package/prerequisites/target-facts/no-crds-crds.yaml
else
  say "The required CRDs already exist; leave them under their current owner"
fi
kubectl wait --for=condition=Established --timeout=120s crd/cleanuppolicies.kyverno.io
kubectl wait --for=condition=Established --timeout=120s crd/clustercleanuppolicies.kyverno.io
kubectl wait --for=condition=Established --timeout=120s crd/clusterpolicies.kyverno.io
kubectl wait --for=condition=Established --timeout=120s crd/globalcontextentries.kyverno.io
kubectl wait --for=condition=Established --timeout=120s crd/policies.kyverno.io
kubectl wait --for=condition=Established --timeout=120s crd/policyexceptions.kyverno.io
kubectl wait --for=condition=Established --timeout=120s crd/updaterequests.kyverno.io
kubectl wait --for=condition=Established --timeout=120s crd/clusterephemeralreports.reports.kyverno.io
kubectl wait --for=condition=Established --timeout=120s crd/ephemeralreports.reports.kyverno.io
kubectl wait --for=condition=Established --timeout=120s crd/clusterpolicyreports.wgpolicyk8s.io
kubectl wait --for=condition=Established --timeout=120s crd/policyreports.wgpolicyk8s.io
kubectl wait --for=condition=Established --timeout=120s crd/deletingpolicies.policies.kyverno.io
kubectl wait --for=condition=Established --timeout=120s crd/generatingpolicies.policies.kyverno.io
kubectl wait --for=condition=Established --timeout=120s crd/imagevalidatingpolicies.policies.kyverno.io
kubectl wait --for=condition=Established --timeout=120s crd/mutatingpolicies.policies.kyverno.io
kubectl wait --for=condition=Established --timeout=120s crd/namespaceddeletingpolicies.policies.kyverno.io
kubectl wait --for=condition=Established --timeout=120s crd/namespacedgeneratingpolicies.policies.kyverno.io
kubectl wait --for=condition=Established --timeout=120s crd/namespacedimagevalidatingpolicies.policies.kyverno.io
kubectl wait --for=condition=Established --timeout=120s crd/namespacedmutatingpolicies.policies.kyverno.io
kubectl wait --for=condition=Established --timeout=120s crd/namespacedvalidatingpolicies.policies.kyverno.io
kubectl wait --for=condition=Established --timeout=120s crd/policyexceptions.policies.kyverno.io
kubectl wait --for=condition=Established --timeout=120s crd/validatingpolicies.policies.kyverno.io

if [ -d ./kyverno-kyverno-3-8-1-no-crds/out/secrets ]; then
  say "Apply rendered Secrets first"
  kubectl apply -f ./kyverno-kyverno-3-8-1-no-crds/out/secrets
fi

say "Apply the rendered objects"
kubectl apply -f ./kyverno-kyverno-3-8-1-no-crds/out/manifests

say "Done. The cluster received exactly the files in ./kyverno-kyverno-3-8-1-no-crds/out."
