apiVersion: "helm-expt.confighub.com/v1alpha1"
kind: "EffectiveValues"
metadata:
  name: "argo-cd-argo-events-2-4-21-default"
  labels:
    confighub.io/chart-ref: "argo-cd/argo-events"
    confighub.io/chart-version: "2.4.21"
    confighub.io/proof-tier: "next80-full"
    confighub.io/variant: "default"
spec:
  profile: "chart-defaults"
  defaultValuesSHA256: "594a61d774d6a6d7b3115bf52dda03dbd607ccd9e4e418f56a1e05156ee28941"
  mergedValuesCaptured: false
  values:
    {}
