apiVersion: "helm-expt.confighub.com/v1alpha1"
kind: "InstallerPackageReceipt"
metadata:
  name: "gitlab-gitlab-runner-0-89-0"
spec:
  chart:
    name: "gitlab-runner"
    repository: "gitlab"
    version: "0.89.0"
  deterministicBundle:
    byteIdenticalAcrossTwoLocalBundles: true
    command: "cub installer package packages/gitlab/gitlab-runner/0.89.0 -o <tmp>/gitlab-gitlab-runner-0-89-0.tgz"
    sha256: "bb44b4b6fcaea031eba98a6be699cac7c0969df3c3d697aa740439d48c9dc370"
  package:
    name: "gitlab-gitlab-runner"
    path: "packages/gitlab/gitlab-runner/0.89.0"
    sourceFiles:
      -
        path: "README.md"
        sha256: "9b2868e16df3782cc1fb7c528a0b7766b26e93a6e9cbeb9edad599ac282ae43f"
        bytes: 201
      -
        path: "bases/default/kustomization.yaml"
        sha256: "44d52637f259f73730afd3a41d7350391387456ab7c418f201eec1ef73720153"
        bytes: 99
      -
        path: "bases/default/upstream.yaml"
        sha256: "ad0d78b72ba8c9c6d896ee2faf620db82e9c52d2794f3dbbcbe6f3705c43d95e"
        bytes: 6970
      -
        path: "installer.yaml"
        sha256: "ae5eb793e1e9a2fee203816266476a628c6b39ad5674f53b1ee6b55b9f75b2e1"
        bytes: 315
      -
        path: "records/README.md"
        sha256: "191c9799224aa0ae46420a9b1ba6a00c10b487f90aec9d8d63fca2ee37ec9758"
        bytes: 997
      -
        path: "records/default/helm-render-intent.yaml"
        sha256: "ce9ee6972c4902ae98a50c10620e27d8671a0438ad2ad612b275ecc3e82a9c0f"
        bytes: 7090
      -
        path: "records/default/source-and-intent.yaml"
        sha256: "68b53d9c6ed4a8183fd17aeec9cb7ccd6cba1429a6c2f2e9e1d191ddb57b33d2"
        bytes: 8843
      -
        path: "records/index.yaml"
        sha256: "6e81e0585c6da402ec21f5685a41a82b33e35908c8aca76eea3accec05911c66"
        bytes: 624
    version: "0.89.0"
  setupChecks:
    -
      allowedCubOnlyObjects:
        - "v1|Namespace||default"
      base: "default"
      command: "cub installer setup --pull packages/gitlab/gitlab-runner/0.89.0 --base default --work-dir <tmp> --non-interactive --namespace default"
      cubInstallObjectCountIncludingSupport: 3
      helmReleaseObjectCount: 2
      semanticObjectMatches: "2/2"
      separatedSecretCount: 0
      variant: "default"
