#!/usr/bin/env bash
# cloudnative-pg/cloudnative-pg 0.28.2 - base variant: no-crds
# Path: pull the package, render this base variant locally, read the objects,
# then apply them with kubectl. No ConfigHub account is needed.
# Generated by scripts/generate-public-site.mjs from the committed package
# data for this base variant. Chart page: https://confighub.github.io/helm-expt/site/charts/cloudnative-pg-cloudnative-pg-0-28-2.html
set -euo pipefail

say() { printf '\n>> %s\n' "$*"; }

if ! command -v cub >/dev/null 2>&1; then
  printf 'cub is not installed. Install the cub CLI with:\n  curl -fsSL https://hub.confighub.com/cub/install.sh | bash\nthen add ~/.confighub/bin to your PATH and re-run this script.\n' >&2
  exit 1
fi

# Installer is a cub plugin. Check it before this script does any work.
if ! cub installer --help >/dev/null 2>&1; then
  printf 'The cub installer plugin is missing. Follow https://confighub.github.io/helm-expt/site/try.html#install-cub, then re-run this script.\n' >&2
  exit 1
fi

if ! command -v kustomize >/dev/null 2>&1; then
  printf 'kustomize is missing. Follow https://confighub.github.io/helm-expt/site/try.html#install-cub, then re-run this script.\n' >&2
  exit 1
fi

if ! command -v kubectl >/dev/null 2>&1; then
  printf 'kubectl is required for the apply step.\n' >&2
  exit 1
fi

say "Pull the package and render the no-crds base variant into ./cloudnative-pg-cloudnative-pg-0-28-2-no-crds"
cub installer setup --pull oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/cloudnative-pg-cloudnative-pg:0.28.2@sha256:30cfcee4ff1d5467c4df45d8223d2b98e9a8d316fa5ec9978533d9ffdcff8dc2 --base no-crds --work-dir ./cloudnative-pg-cloudnative-pg-0-28-2-no-crds --non-interactive --namespace default

say "Read what was rendered; nothing has touched the cluster yet"
ls ./cloudnative-pg-cloudnative-pg-0-28-2-no-crds/out/manifests

wait_for_crd() {
  crd_name="$1"
  deadline=$(( $(date +%s) + 180 ))
  until kubectl get "crd/${crd_name}" >/dev/null 2>&1; do
    if [ "$(date +%s)" -ge "$deadline" ]; then
      printf "CRD %s did not appear within 180 seconds.\n" "$crd_name" >&2
      return 1
    fi
    sleep 2
  done
  kubectl wait --for=condition=Established --timeout=120s "crd/${crd_name}"
}

say "Ensure the default namespace exists"
kubectl create namespace default --dry-run=client -o yaml | kubectl apply -f -

say "Check 10 CRDs included with this package"
missing_crds=0
if ! kubectl get crd/backups.postgresql.cnpg.io >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/clusterimagecatalogs.postgresql.cnpg.io >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/clusters.postgresql.cnpg.io >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/databases.postgresql.cnpg.io >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/failoverquorums.postgresql.cnpg.io >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/imagecatalogs.postgresql.cnpg.io >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/poolers.postgresql.cnpg.io >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/publications.postgresql.cnpg.io >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/scheduledbackups.postgresql.cnpg.io >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/subscriptions.postgresql.cnpg.io >/dev/null 2>&1; then
  missing_crds=1
fi
if [ "$missing_crds" -eq 1 ]; then
  kubectl apply --server-side -f ./cloudnative-pg-cloudnative-pg-0-28-2-no-crds/package/prerequisites/target-facts/no-crds-crds.yaml
else
  say "The required CRDs already exist; leave them under their current owner"
fi
wait_for_crd backups.postgresql.cnpg.io
wait_for_crd clusterimagecatalogs.postgresql.cnpg.io
wait_for_crd clusters.postgresql.cnpg.io
wait_for_crd databases.postgresql.cnpg.io
wait_for_crd failoverquorums.postgresql.cnpg.io
wait_for_crd imagecatalogs.postgresql.cnpg.io
wait_for_crd poolers.postgresql.cnpg.io
wait_for_crd publications.postgresql.cnpg.io
wait_for_crd scheduledbackups.postgresql.cnpg.io
wait_for_crd subscriptions.postgresql.cnpg.io

if [ "${REQUIREMENTS_READY:-0}" != "1" ]; then
  cat >&2 <<'EOF_REQUIREMENTS'
This base variant needs resources you must create with your own values first:
  - Secret default/cnpg-webhook-cert keys tls.crt,tls.key
    kubectl -n default create secret generic cnpg-webhook-cert --from-literal=tls.crt=<value> --from-literal=tls.key=<value>
Complete these prerequisites before applying the rendered objects.
Replace any <...> placeholders with values or files for your environment.
When the resources exist, re-run with:
  REQUIREMENTS_READY=1 bash try.sh
EOF_REQUIREMENTS
  exit 1
fi

if [ -d ./cloudnative-pg-cloudnative-pg-0-28-2-no-crds/out/secrets ]; then
  say "Apply rendered Secrets first"
  kubectl apply -f ./cloudnative-pg-cloudnative-pg-0-28-2-no-crds/out/secrets
fi

say "Apply the rendered objects"
kubectl apply -f ./cloudnative-pg-cloudnative-pg-0-28-2-no-crds/out/manifests

say "Done. The cluster received exactly the files in ./cloudnative-pg-cloudnative-pg-0-28-2-no-crds/out."
