#!/usr/bin/env bash
# grafana/tempo 1.24.4 - preset: local-persistent
# Path: pull the package, render this preset locally, read the objects,
# then apply them with kubectl. No ConfigHub account is needed.
# Generated by scripts/generate-public-site.mjs from the committed package
# data for this preset. Chart page: https://confighub.github.io/helm-expt/site/charts/grafana-tempo-1-24-4.html
set -euo pipefail

say() { printf '\n>> %s\n' "$*"; }

if ! command -v cub >/dev/null 2>&1; then
  printf 'cub is not installed. Install it with:\n  curl -fsSL https://hub.confighub.com/cub/install.sh | bash\nthen add ~/.confighub/bin to your PATH and re-run this script.\n' >&2
  exit 1
fi

if ! command -v kubectl >/dev/null 2>&1; then
  printf 'kubectl is required for the apply step.\n' >&2
  exit 1
fi

say "Pull the package and render the local-persistent preset into ./grafana-tempo-1-24-4-local-persistent"
cub installer setup --pull oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/grafana-tempo:1.24.4 --base local-persistent --work-dir ./grafana-tempo-1-24-4-local-persistent --non-interactive --namespace tempo

say "Read what was rendered; nothing has touched the cluster yet"
ls ./grafana-tempo-1-24-4-local-persistent/out/manifests

say "Ensure the tempo namespace exists"
kubectl create namespace tempo --dry-run=client -o yaml | kubectl apply -f -

if [ -d ./grafana-tempo-1-24-4-local-persistent/out/secrets ]; then
  say "Apply rendered Secrets first"
  kubectl apply -f ./grafana-tempo-1-24-4-local-persistent/out/secrets
fi

say "Apply the rendered objects"
kubectl apply -f ./grafana-tempo-1-24-4-local-persistent/out/manifests

say "Done. The cluster received exactly the files in ./grafana-tempo-1-24-4-local-persistent/out."
