apiVersion: "helm-expt.confighub.com/v1alpha1"
kind: "InstallerPackageReceipt"
metadata:
  name: "kyverno-kyverno-policies-3.8.2"
spec:
  chart:
    name: "kyverno-policies"
    repository: "kyverno"
    version: "3.8.2"
  deterministicBundle:
    byteIdenticalAcrossTwoLocalBundles: true
    command: "cub installer package packages/kyverno/kyverno-policies/3.8.2 -o <tmp>/kyverno-policies-3.8.2.tgz"
    sha256: "1253acd9011bc57c1a996904e4bb161cf1f7865a5f3de5878dd40aa5c998d164"
  package:
    name: "kyverno-kyverno-policies"
    path: "packages/kyverno/kyverno-policies/3.8.2"
    sourceFiles:
      -
        path: "README.md"
        sha256: "da4211020624372a0a19913d6cc9abe1e9a6e640270ca24aab5710fdca1de0e5"
        bytes: 405
      -
        path: "bases/default/kustomization.yaml"
        sha256: "44d52637f259f73730afd3a41d7350391387456ab7c418f201eec1ef73720153"
        bytes: 99
      -
        path: "bases/default/upstream.yaml"
        sha256: "5049b2e9cb54b8d2fa8e70cdf606a3be6ce9d13f081354067ff877c3174454f1"
        bytes: 23932
      -
        path: "installer.yaml"
        sha256: "c0b9140b11c843f9c352c68f2d1847bfb522569e4d522eb31e4c5b0b4ad43e5d"
        bytes: 324
      -
        path: "records/README.md"
        sha256: "191c9799224aa0ae46420a9b1ba6a00c10b487f90aec9d8d63fca2ee37ec9758"
        bytes: 997
      -
        path: "records/default/helm-render-intent.yaml"
        sha256: "5ecce2477047c80f332d1519b7fae17549b962310c35d6987dcb05a5c900e10c"
        bytes: 5416
      -
        path: "records/default/source-and-intent.yaml"
        sha256: "139503947e7f22bc1793ae45a001312a26a0c4e835d466dc5db3b5b686c62e3c"
        bytes: 8858
      -
        path: "records/index.yaml"
        sha256: "544028d9c31e30043799a7c9e3668063f685292297d2140a40c15ec19f21c7b9"
        bytes: 630
    version: "3.8.2"
  setupChecks:
    -
      allowedCubOnlyObjects:
        - "v1|Namespace||kyverno"
      base: "default"
      command: "cub installer setup --pull packages/kyverno/kyverno-policies/3.8.2 --base default --work-dir <tmp> --non-interactive --namespace kyverno"
      cubInstallObjectCountIncludingSupport: 12
      helmReleaseObjectCount: 11
      semanticObjectMatches: "11/11"
      separatedSecretCount: 0
      targetFactMode: "not-required"
      targetFactsBound: false
      variant: "default"
