apiVersion: "helm-expt.confighub.com/v1alpha1"
kind: "RenderReceipt"
metadata:
  labels:
    confighub.io/chart-ref: "prometheus-community/prometheus-adapter"
    confighub.io/chart-version: "5.3.0"
    confighub.io/proof-tier: "next80-full"
    confighub.io/variant: "cluster-metrics-readonly"
  name: "prometheus-community-prometheus-adapter-5-3-0-cluster-metrics-readonly-r001"
spec:
  inputs:
    dependencyLockSHA256: "b3cedb4d0d78e0b20c57569b96668a1d1cfd781b37ecf9d2e6a2615364855200"
    effectiveValuesSHA256: "d7c8d6edeb00db3a677ef87e5084558ea3ac10a7f8ba4efd71779f985f632371"
    sourceLockSHA256: "ed8662d4c8b0690ed6cf08e4ae441b9d6694b204945690c5a8b301f633b3e0b1"
  outputs:
    deterministicAcrossTwoLocalRenders: true
    objectCount: 11
    renderedObjectInventorySHA256: "2f6adae88c9365b67d3c13bf58475fbd953e325e6ac35b48a500dad6ebc97e72"
    renderedObjectSetSHA256: "50e586691867cf7be3f14a7c3e71839f3f8b6cae32b64a10f01362d68add983a"
    renderedSecretCount: 0
    secretCountSeparatedByCubInstall: 0
  renderer:
    flags:
      - "--include-crds"
      - "--skip-tests"
      - "--no-hooks"
    kubeVersion: "1.30.0"
    name: "helm"
    version: "v4.1.4+g05fa379"
  variantRevision: "../variant-revision.yaml"
  usefulBaseAlias:
    sourceBase: "default"
    realizationStrategy: "alias-of-default-render"
