#!/usr/bin/env bash
# ingress-nginx/ingress-nginx 4.15.1 - base variant: admission-disabled
# Path: pull the package, render this base variant locally, read the objects,
# then apply them with kubectl. No ConfigHub account is needed.
# Generated by scripts/generate-public-site.mjs from the committed package
# data for this base variant. Chart page: https://confighub.github.io/helm-expt/site/charts/ingress-nginx-ingress-nginx-4-15-1.html
set -euo pipefail

say() { printf '\n>> %s\n' "$*"; }

if ! command -v cub >/dev/null 2>&1; then
  printf 'cub is not installed. Install the cub CLI with:\n  curl -fsSL https://hub.confighub.com/cub/install.sh | bash\nthen add ~/.confighub/bin to your PATH and re-run this script.\n' >&2
  exit 1
fi

# Public cub releases include the installer command. This guard catches
# an older or incomplete CLI before this script does any work.
if ! cub installer --help >/dev/null 2>&1; then
  printf 'This cub build does not include cub installer. Install or upgrade the cub CLI with:\n  curl -fsSL https://hub.confighub.com/cub/install.sh | bash\nthen add ~/.confighub/bin to your PATH and re-run this script.\n' >&2
  exit 1
fi

if ! command -v kubectl >/dev/null 2>&1; then
  printf 'kubectl is required for the apply step.\n' >&2
  exit 1
fi

say "Pull the package and render the admission-disabled base variant into ./ingress-nginx-ingress-nginx-4-15-1-admission-disabled"
cub installer setup --pull oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/ingress-nginx-ingress-nginx:4.15.1 --base admission-disabled --work-dir ./ingress-nginx-ingress-nginx-4-15-1-admission-disabled --non-interactive --namespace ingress-nginx

say "Read what was rendered; nothing has touched the cluster yet"
ls ./ingress-nginx-ingress-nginx-4-15-1-admission-disabled/out/manifests

say "Ensure the ingress-nginx namespace exists"
kubectl create namespace ingress-nginx --dry-run=client -o yaml | kubectl apply -f -

if [ -d ./ingress-nginx-ingress-nginx-4-15-1-admission-disabled/out/secrets ]; then
  say "Apply rendered Secrets first"
  kubectl apply -f ./ingress-nginx-ingress-nginx-4-15-1-admission-disabled/out/secrets
fi

say "Apply the rendered objects"
kubectl apply -f ./ingress-nginx-ingress-nginx-4-15-1-admission-disabled/out/manifests

say "Done. The cluster received exactly the files in ./ingress-nginx-ingress-nginx-4-15-1-admission-disabled/out."
