#!/usr/bin/env bash
# open-telemetry/opentelemetry-operator 0.114.0 - base variant: no-crds
# Path: pull the package, render this base variant locally, read the objects,
# then apply them with kubectl. No ConfigHub account is needed.
# Generated by scripts/generate-public-site.mjs from the committed package
# data for this base variant. Chart page: https://confighub.github.io/helm-expt/site/charts/open-telemetry-opentelemetry-operator-0-114-0.html
set -euo pipefail

say() { printf '\n>> %s\n' "$*"; }

if ! command -v cub >/dev/null 2>&1; then
  printf 'cub is not installed. Install it with:\n  curl -fsSL https://hub.confighub.com/cub/install.sh | bash\nthen add ~/.confighub/bin to your PATH and re-run this script.\n' >&2
  exit 1
fi

if ! cub installer --help >/dev/null 2>&1; then
  printf '%s\n' 'The cub installer command is not available. It is a cub plugin that is not yet publicly released. Watch https://github.com/confighub/installer for the public plugin release. This script stops before it touches your cluster.' >&2
  exit 1
fi

if ! command -v kubectl >/dev/null 2>&1; then
  printf 'kubectl is required for the apply step.\n' >&2
  exit 1
fi

say "Pull the package and render the no-crds base variant into ./open-telemetry-opentelemetry-operator-0-114-0-no-crds"
cub installer setup --pull oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/open-telemetry-opentelemetry-operator:0.114.0 --base no-crds --work-dir ./open-telemetry-opentelemetry-operator-0-114-0-no-crds --non-interactive --namespace default

say "Read what was rendered; nothing has touched the cluster yet"
ls ./open-telemetry-opentelemetry-operator-0-114-0-no-crds/out/manifests

say "Ensure the default namespace exists"
kubectl create namespace default --dry-run=client -o yaml | kubectl apply -f -

say "Requirement before apply: Secret default/opentelemetry-operator-controller-manager-service-cert keys tls.crt,tls.key"
if ! Run cert-manager controller to satisfy the chart-rendered Certificate, or stage a valid TLS Secret before waiting for the operator; then
  printf '!! The requirement command failed. If the resource already exists, review it and re-run; otherwise fix the error above.\n' >&2
  exit 1
fi

if [ "${REQUIREMENTS_READY:-0}" != "1" ]; then
  cat >&2 <<'EOF_REQUIREMENTS'
This base variant needs resources you must create with your own values first:
  - CRD certificates.cert-manager.io
    kubectl apply -f <crd-manifest.yaml>
  - CRD issuers.cert-manager.io
    kubectl apply -f <crd-manifest.yaml>
  - CRD instrumentations.opentelemetry.io
    kubectl apply -f <crd-manifest.yaml>
  - CRD opampbridges.opentelemetry.io
    kubectl apply -f <crd-manifest.yaml>
  - CRD opentelemetrycollectors.opentelemetry.io
    kubectl apply -f <crd-manifest.yaml>
  - CRD targetallocators.opentelemetry.io
    kubectl apply -f <crd-manifest.yaml>
Substitute the <...> placeholders and create these, then re-run with:
  REQUIREMENTS_READY=1 bash try.sh
EOF_REQUIREMENTS
  exit 1
fi

if [ -d ./open-telemetry-opentelemetry-operator-0-114-0-no-crds/out/secrets ]; then
  say "Apply rendered Secrets first"
  kubectl apply -f ./open-telemetry-opentelemetry-operator-0-114-0-no-crds/out/secrets
fi

say "Apply the rendered objects"
kubectl apply -f ./open-telemetry-opentelemetry-operator-0-114-0-no-crds/out/manifests

say "Done. The cluster received exactly the files in ./open-telemetry-opentelemetry-operator-0-114-0-no-crds/out."
