#!/usr/bin/env bash
# mysql/mysql-operator 2.3.0 - base variant: default
# Path: pull the package, render this base variant locally, read the objects,
# then apply them with kubectl. No ConfigHub account is needed.
# Generated by scripts/generate-public-site.mjs from the committed package
# data for this base variant. Chart page: https://confighub.github.io/helm-expt/site/charts/mysql-mysql-operator-2-3-0.html
set -euo pipefail

say() { printf '\n>> %s\n' "$*"; }

if ! command -v cub >/dev/null 2>&1; then
  printf 'cub is not installed. Install the cub CLI with:\n  curl -fsSL https://hub.confighub.com/cub/install.sh | bash\nthen add ~/.confighub/bin to your PATH and re-run this script.\n' >&2
  exit 1
fi

# Installer is a cub plugin. Check it before this script does any work.
if ! cub installer --help >/dev/null 2>&1; then
  printf 'The cub installer plugin is missing. Follow https://confighub.github.io/helm-expt/site/try.html#install-cub, then re-run this script.\n' >&2
  exit 1
fi

if ! command -v kustomize >/dev/null 2>&1; then
  printf 'kustomize is missing. Follow https://confighub.github.io/helm-expt/site/try.html#install-cub, then re-run this script.\n' >&2
  exit 1
fi

if ! command -v kubectl >/dev/null 2>&1; then
  printf 'kubectl is required for the apply step.\n' >&2
  exit 1
fi

say "Pull the package and render the default base variant into ./mysql-mysql-operator-2-3-0-default"
cub installer setup --pull oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/mysql-mysql-operator:2.3.0@sha256:59116d8ebabcf485c7d0f38b659c3ec93e8aacb0a35db02a4f2e3226c7c8a6c5 --base default --work-dir ./mysql-mysql-operator-2-3-0-default --non-interactive --namespace mysql-operator

say "Read what was rendered; nothing has touched the cluster yet"
ls ./mysql-mysql-operator-2-3-0-default/out/manifests

say "Ensure the mysql-operator namespace exists"
kubectl create namespace mysql-operator --dry-run=client -o yaml | kubectl apply -f -

if [ -d ./mysql-mysql-operator-2-3-0-default/out/secrets ]; then
  say "Apply rendered Secrets first"
  kubectl apply -f ./mysql-mysql-operator-2-3-0-default/out/secrets
fi

say "Apply the rendered objects"
kubectl apply -f ./mysql-mysql-operator-2-3-0-default/out/manifests

say "Done. The cluster received exactly the files in ./mysql-mysql-operator-2-3-0-default/out."
