apiVersion: "helm-expt.confighub.com/v1alpha1"
kind: "Variant"
metadata:
  name: "eks-inference"
spec:
  recipe: "../../recipe.yaml"
  namespace: "gpu-operator"
  releaseName: "nvidia-device-plugin"
  valuesProfile: "../../effective-values-eks-inference.yaml"
  capabilityProfile:
    kubeVersion: "1.31.0"
    apiVersions:
      []
  hookPolicy: "hooks-rendered-visible"
