apiVersion: "installer.confighub.com/v1alpha1"
kind: "Package"
metadata:
  name: "bitnami-zookeeper"
  version: "13.8.7"
spec:
  bases:
    -
      default: true
      description: "bitnami/zookeeper default variant rendered from bitnami/zookeeper@13.8.7"
      name: "default"
      path: "bases/default"
    -
      name: "ha"
      path: "bases/ha"
      description: "bitnami/zookeeper ha variant rendered from bitnami/zookeeper@13.8.7"
