apiVersion: "helm-expt.confighub.com/v1alpha1"
kind: "EffectiveValues"
metadata:
  name: "bitnami-mysql-14.0.3-existing-secret"
spec:
  files:
    -
      path: "effective-values-existing-secret.yaml"
      source: "inline-proof"
      sha256: "82a7a603b3d9a4d666017d51f24d352b7d39ce6d91b2adec7474381307f6f7a3"
  mergedValuesCaptured: false
  values:
    auth:
      existingSecret: "mysql-auth"
    global:
      security:
        allowInsecureImages: true
    image:
      repository: "bitnamilegacy/mysql"
