#!/usr/bin/env bash
# bitnami/nginx 24.0.2 - preset: existing-tls-ingress
# Path: render this preset locally, then upload the objects to your
# ConfigHub Space as Units you can edit, diff, and deliver.
# Needs a ConfigHub account: run cub auth login once before this script.
# Generated by scripts/generate-public-site.mjs from the committed package
# data for this preset. Chart page: https://confighub.github.io/helm-expt/site/charts/bitnami-nginx-24-0-2.html
set -euo pipefail

say() { printf '\n>> %s\n' "$*"; }

if ! command -v cub >/dev/null 2>&1; then
  printf 'cub is not installed. Install it with:\n  curl -fsSL https://hub.confighub.com/cub/install.sh | bash\nthen add ~/.confighub/bin to your PATH and re-run this script.\n' >&2
  exit 1
fi

SPACE="${CUB_SPACE:-helm-nginx-existing-tls-ingress}"

say "Check ConfigHub auth"
if ! cub auth status >/dev/null 2>&1; then
  printf 'Not logged in. Run: cub auth login\nThen re-run this script.\n' >&2
  exit 1
fi

say "Render the existing-tls-ingress preset into ./bitnami-nginx-24-0-2-existing-tls-ingress"
cub installer setup --pull oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/bitnami-nginx:24.0.2 --base existing-tls-ingress --work-dir ./bitnami-nginx-24-0-2-existing-tls-ingress --non-interactive --namespace nginx

say "Upload the rendered objects to Space ${SPACE} (created on first upload)"
cub installer upload --work-dir ./bitnami-nginx-24-0-2-existing-tls-ingress --space "${SPACE}"

say "Uploaded. See your Units:"
printf '  cub unit list --space %s\n  or open https://hub.confighub.com and find that Space.\n' "${SPACE}"

# Before applying this preset from ConfigHub to a cluster, it still needs:
#   - Secret nginx/nginx-backend-tls keys tls.crt,tls.key,ca.crt (suggested: kubectl -n nginx create secret generic nginx-backend-tls --from-literal=tls.crt=<value> --from-literal=tls.key=<value> --from-literal=ca.crt=<value>)
#   - Secret nginx/nginx-ingress-tls keys tls.crt,tls.key (suggested: kubectl -n nginx create secret generic nginx-ingress-tls --from-literal=tls.crt=<value> --from-literal=tls.key=<value>)
