#!/usr/bin/env bash
# bitnami/nginx 24.0.2 - base variant: existing-tls-ingress
# Path: pull the package, render this base variant locally, read the objects,
# then apply them with kubectl. No ConfigHub account is needed.
# Generated by scripts/generate-public-site.mjs from the committed package
# data for this base variant. Chart page: https://confighub.github.io/helm-expt/site/charts/bitnami-nginx-24-0-2.html
set -euo pipefail

say() { printf '\n>> %s\n' "$*"; }

if ! command -v cub >/dev/null 2>&1; then
  printf 'cub is not installed. Install the cub CLI with:\n  curl -fsSL https://hub.confighub.com/cub/install.sh | bash\nthen add ~/.confighub/bin to your PATH and re-run this script.\n' >&2
  exit 1
fi

# Installer is a cub plugin. Check it before this script does any work.
if ! cub installer --help >/dev/null 2>&1; then
  printf 'The cub installer plugin is missing. Follow https://confighub.github.io/helm-expt/site/try.html#install-cub, then re-run this script.\n' >&2
  exit 1
fi

if ! command -v kustomize >/dev/null 2>&1; then
  printf 'kustomize is missing. Follow https://confighub.github.io/helm-expt/site/try.html#install-cub, then re-run this script.\n' >&2
  exit 1
fi

if ! command -v kubectl >/dev/null 2>&1; then
  printf 'kubectl is required for the apply step.\n' >&2
  exit 1
fi

say "Pull the package and render the existing-tls-ingress base variant into ./bitnami-nginx-24-0-2-existing-tls-ingress"
cub installer setup --pull oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/bitnami-nginx:24.0.2 --base existing-tls-ingress --work-dir ./bitnami-nginx-24-0-2-existing-tls-ingress --non-interactive --namespace nginx

say "Read what was rendered; nothing has touched the cluster yet"
ls ./bitnami-nginx-24-0-2-existing-tls-ingress/out/manifests

say "Ensure the nginx namespace exists"
kubectl create namespace nginx --dry-run=client -o yaml | kubectl apply -f -

if [ "${REQUIREMENTS_READY:-0}" != "1" ]; then
  cat >&2 <<'EOF_REQUIREMENTS'
This base variant needs resources you must create with your own values first:
  - Secret nginx/nginx-backend-tls keys tls.crt,tls.key,ca.crt
    kubectl -n nginx create secret generic nginx-backend-tls --from-literal=tls.crt=<value> --from-literal=tls.key=<value> --from-literal=ca.crt=<value>
  - Secret nginx/nginx-ingress-tls keys tls.crt,tls.key
    kubectl -n nginx create secret generic nginx-ingress-tls --from-literal=tls.crt=<value> --from-literal=tls.key=<value>
Substitute the <...> placeholders and create these, then re-run with:
  REQUIREMENTS_READY=1 bash try.sh
EOF_REQUIREMENTS
  exit 1
fi

if [ -d ./bitnami-nginx-24-0-2-existing-tls-ingress/out/secrets ]; then
  say "Apply rendered Secrets first"
  kubectl apply -f ./bitnami-nginx-24-0-2-existing-tls-ingress/out/secrets
fi

say "Apply the rendered objects"
kubectl apply -f ./bitnami-nginx-24-0-2-existing-tls-ingress/out/manifests

say "Done. The cluster received exactly the files in ./bitnami-nginx-24-0-2-existing-tls-ingress/out."
