#!/usr/bin/env bash
# elastic/logstash 8.5.1 - preset: ha
# Path: pull the package, render this preset locally, read the objects,
# then apply them with kubectl. No ConfigHub account is needed.
# Generated by scripts/generate-public-site.mjs from the committed package
# data for this preset. Chart page: https://confighub.github.io/helm-expt/site/charts/elastic-logstash-8-5-1.html
set -euo pipefail

say() { printf '\n>> %s\n' "$*"; }

if ! command -v cub >/dev/null 2>&1; then
  printf 'cub is not installed. Install it with:\n  curl -fsSL https://hub.confighub.com/cub/install.sh | bash\nthen add ~/.confighub/bin to your PATH and re-run this script.\n' >&2
  exit 1
fi

if ! command -v kubectl >/dev/null 2>&1; then
  printf 'kubectl is required for the apply step.\n' >&2
  exit 1
fi

say "Pull the package and render the ha preset into ./elastic-logstash-8-5-1-ha"
cub installer setup --pull oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/elastic-logstash:8.5.1 --base ha --work-dir ./elastic-logstash-8-5-1-ha --non-interactive --namespace default

say "Read what was rendered; nothing has touched the cluster yet"
ls ./elastic-logstash-8-5-1-ha/out/manifests

say "Ensure the default namespace exists"
kubectl create namespace default --dry-run=client -o yaml | kubectl apply -f -

say "Requirement before apply: minimum schedulable nodes 3"
if ! use a target with at least 3 schedulable nodes before applying this base; then
  printf '!! The requirement command failed. If the resource already exists, review it and re-run; otherwise fix the error above.\n' >&2
  exit 1
fi

if [ -d ./elastic-logstash-8-5-1-ha/out/secrets ]; then
  say "Apply rendered Secrets first"
  kubectl apply -f ./elastic-logstash-8-5-1-ha/out/secrets
fi

say "Apply the rendered objects"
kubectl apply -f ./elastic-logstash-8-5-1-ha/out/manifests

say "Done. The cluster received exactly the files in ./elastic-logstash-8-5-1-ha/out."
