#!/usr/bin/env bash
# gatekeeper/gatekeeper 3.22.2 - base variant: no-crds
# Path: render this base variant locally, then upload the objects to your
# ConfigHub Space as Units you can edit, diff, and deliver.
# Needs a ConfigHub account: run cub auth login once before this script.
# Generated by scripts/generate-public-site.mjs from the committed package
# data for this base variant. Chart page: https://confighub.github.io/helm-expt/site/charts/gatekeeper-gatekeeper-3-22-2.html
set -euo pipefail

say() { printf '\n>> %s\n' "$*"; }

if ! command -v cub >/dev/null 2>&1; then
  printf 'cub is not installed. Install the cub CLI with:\n  curl -fsSL https://hub.confighub.com/cub/install.sh | bash\nthen add ~/.confighub/bin to your PATH and re-run this script.\n' >&2
  exit 1
fi

# Installer is a cub plugin. Check it before this script does any work.
if ! cub installer --help >/dev/null 2>&1; then
  printf 'The cub installer plugin is missing. Follow https://confighub.github.io/helm-expt/site/try.html#install-cub, then re-run this script.\n' >&2
  exit 1
fi

if ! command -v kustomize >/dev/null 2>&1; then
  printf 'kustomize is missing. Follow https://confighub.github.io/helm-expt/site/try.html#install-cub, then re-run this script.\n' >&2
  exit 1
fi

SPACE="${CUB_SPACE:-helm-gatekeeper-no-crds}"

say "Check ConfigHub auth"
if ! cub auth status >/dev/null 2>&1; then
  printf 'Not logged in. Run: cub auth login\nThen re-run this script.\n' >&2
  exit 1
fi

say "Render the no-crds base variant into ./gatekeeper-gatekeeper-3-22-2-no-crds"
cub installer setup --pull oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/gatekeeper-gatekeeper:3.22.2@sha256:ce4877c260225419e22d820f9d15652ad48ed5f205117099e88abb3f590241a5 --base no-crds --work-dir ./gatekeeper-gatekeeper-3-22-2-no-crds --non-interactive --namespace default

say "Upload the rendered objects to Space ${SPACE} (created on first upload)"
cub installer upload --work-dir ./gatekeeper-gatekeeper-3-22-2-no-crds --space "${SPACE}"

say "Uploaded. See your Units:"
printf '  cub unit list --space %s\n  or open https://hub.confighub.com and find that Space.\n' "${SPACE}"

say "Next: create an environment variant and promote reviewed changes"
printf '  Walkthrough with the why behind each flag:\n  https://confighub.github.io/helm-expt/site/d/docs/user/variants-after-upload.html\n'

# Before applying this base variant from ConfigHub to a cluster, it still needs:
#   - CRD assign.mutations.gatekeeper.sh (included in the package as prerequisites/target-facts/no-crds-crds.yaml)
#   - CRD assignimage.mutations.gatekeeper.sh (included in the package as prerequisites/target-facts/no-crds-crds.yaml)
#   - CRD assignmetadata.mutations.gatekeeper.sh (included in the package as prerequisites/target-facts/no-crds-crds.yaml)
#   - CRD configs.config.gatekeeper.sh (included in the package as prerequisites/target-facts/no-crds-crds.yaml)
#   - CRD configpodstatuses.status.gatekeeper.sh (included in the package as prerequisites/target-facts/no-crds-crds.yaml)
#   - CRD connections.connection.gatekeeper.sh (included in the package as prerequisites/target-facts/no-crds-crds.yaml)
#   - CRD connectionpodstatuses.status.gatekeeper.sh (included in the package as prerequisites/target-facts/no-crds-crds.yaml)
#   - CRD constraintpodstatuses.status.gatekeeper.sh (included in the package as prerequisites/target-facts/no-crds-crds.yaml)
#   - CRD constrainttemplates.templates.gatekeeper.sh (included in the package as prerequisites/target-facts/no-crds-crds.yaml)
#   - CRD constrainttemplatepodstatuses.status.gatekeeper.sh (included in the package as prerequisites/target-facts/no-crds-crds.yaml)
#   - CRD expansiontemplate.expansion.gatekeeper.sh (included in the package as prerequisites/target-facts/no-crds-crds.yaml)
#   - CRD expansiontemplatepodstatuses.status.gatekeeper.sh (included in the package as prerequisites/target-facts/no-crds-crds.yaml)
#   - CRD modifyset.mutations.gatekeeper.sh (included in the package as prerequisites/target-facts/no-crds-crds.yaml)
#   - CRD mutatorpodstatuses.status.gatekeeper.sh (included in the package as prerequisites/target-facts/no-crds-crds.yaml)
#   - CRD providers.externaldata.gatekeeper.sh (included in the package as prerequisites/target-facts/no-crds-crds.yaml)
#   - CRD providerpodstatuses.status.gatekeeper.sh (included in the package as prerequisites/target-facts/no-crds-crds.yaml)
#   - CRD syncsets.syncset.gatekeeper.sh (included in the package as prerequisites/target-facts/no-crds-crds.yaml)
