#!/usr/bin/env bash
# gatekeeper/gatekeeper 3.22.2 - base variant: no-crds
# Path: pull the package, render this base variant locally, read the objects,
# then apply them with kubectl. No ConfigHub account is needed.
# Generated by scripts/generate-public-site.mjs from the committed package
# data for this base variant. Chart page: https://confighub.github.io/helm-expt/site/charts/gatekeeper-gatekeeper-3-22-2.html
set -euo pipefail

say() { printf '\n>> %s\n' "$*"; }

if ! command -v cub >/dev/null 2>&1; then
  printf 'cub is not installed. Install it with:\n  curl -fsSL https://hub.confighub.com/cub/install.sh | bash\nthen add ~/.confighub/bin to your PATH and re-run this script.\n' >&2
  exit 1
fi

if ! command -v kubectl >/dev/null 2>&1; then
  printf 'kubectl is required for the apply step.\n' >&2
  exit 1
fi

say "Pull the package and render the no-crds base variant into ./gatekeeper-gatekeeper-3-22-2-no-crds"
cub installer setup --pull oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/gatekeeper-gatekeeper:3.22.2 --base no-crds --work-dir ./gatekeeper-gatekeeper-3-22-2-no-crds --non-interactive --namespace default

say "Read what was rendered; nothing has touched the cluster yet"
ls ./gatekeeper-gatekeeper-3-22-2-no-crds/out/manifests

say "Ensure the default namespace exists"
kubectl create namespace default --dry-run=client -o yaml | kubectl apply -f -

if [ "${REQUIREMENTS_READY:-0}" != "1" ]; then
  cat >&2 <<'EOF_REQUIREMENTS'
This base variant needs resources you must create with your own values first:
  - CRD assign.mutations.gatekeeper.sh
    kubectl apply -f <crd-manifest.yaml>
  - CRD assignimage.mutations.gatekeeper.sh
    kubectl apply -f <crd-manifest.yaml>
  - CRD assignmetadata.mutations.gatekeeper.sh
    kubectl apply -f <crd-manifest.yaml>
  - CRD configs.config.gatekeeper.sh
    kubectl apply -f <crd-manifest.yaml>
  - CRD configpodstatuses.status.gatekeeper.sh
    kubectl apply -f <crd-manifest.yaml>
  - CRD connections.connection.gatekeeper.sh
    kubectl apply -f <crd-manifest.yaml>
  - CRD connectionpodstatuses.status.gatekeeper.sh
    kubectl apply -f <crd-manifest.yaml>
  - CRD constraintpodstatuses.status.gatekeeper.sh
    kubectl apply -f <crd-manifest.yaml>
  - CRD constrainttemplates.templates.gatekeeper.sh
    kubectl apply -f <crd-manifest.yaml>
  - CRD constrainttemplatepodstatuses.status.gatekeeper.sh
    kubectl apply -f <crd-manifest.yaml>
  - CRD expansiontemplate.expansion.gatekeeper.sh
    kubectl apply -f <crd-manifest.yaml>
  - CRD expansiontemplatepodstatuses.status.gatekeeper.sh
    kubectl apply -f <crd-manifest.yaml>
  - CRD modifyset.mutations.gatekeeper.sh
    kubectl apply -f <crd-manifest.yaml>
  - CRD mutatorpodstatuses.status.gatekeeper.sh
    kubectl apply -f <crd-manifest.yaml>
  - CRD providers.externaldata.gatekeeper.sh
    kubectl apply -f <crd-manifest.yaml>
  - CRD providerpodstatuses.status.gatekeeper.sh
    kubectl apply -f <crd-manifest.yaml>
  - CRD syncsets.syncset.gatekeeper.sh
    kubectl apply -f <crd-manifest.yaml>
Substitute the <...> placeholders and create these, then re-run with:
  REQUIREMENTS_READY=1 bash try.sh
EOF_REQUIREMENTS
  exit 1
fi

if [ -d ./gatekeeper-gatekeeper-3-22-2-no-crds/out/secrets ]; then
  say "Apply rendered Secrets first"
  kubectl apply -f ./gatekeeper-gatekeeper-3-22-2-no-crds/out/secrets
fi

say "Apply the rendered objects"
kubectl apply -f ./gatekeeper-gatekeeper-3-22-2-no-crds/out/manifests

say "Done. The cluster received exactly the files in ./gatekeeper-gatekeeper-3-22-2-no-crds/out."
