#!/usr/bin/env bash
# gatekeeper/gatekeeper 3.22.2 - base variant: no-crds
# Path: pull the package, render this base variant locally, read the objects,
# then apply them with kubectl. No ConfigHub account is needed.
# Generated by scripts/generate-public-site.mjs from the committed package
# data for this base variant. Chart page: https://confighub.github.io/helm-expt/site/charts/gatekeeper-gatekeeper-3-22-2.html
set -euo pipefail

say() { printf '\n>> %s\n' "$*"; }

if ! command -v cub >/dev/null 2>&1; then
  printf 'cub is not installed. Install the cub CLI with:\n  curl -fsSL https://hub.confighub.com/cub/install.sh | bash\nthen add ~/.confighub/bin to your PATH and re-run this script.\n' >&2
  exit 1
fi

# Installer is a cub plugin. Check it before this script does any work.
if ! cub installer --help >/dev/null 2>&1; then
  printf 'The cub installer plugin is missing. Follow https://confighub.github.io/helm-expt/site/try.html#install-cub, then re-run this script.\n' >&2
  exit 1
fi

if ! command -v kustomize >/dev/null 2>&1; then
  printf 'kustomize is missing. Follow https://confighub.github.io/helm-expt/site/try.html#install-cub, then re-run this script.\n' >&2
  exit 1
fi

if ! command -v kubectl >/dev/null 2>&1; then
  printf 'kubectl is required for the apply step.\n' >&2
  exit 1
fi

say "Pull the package and render the no-crds base variant into ./gatekeeper-gatekeeper-3-22-2-no-crds"
cub installer setup --pull oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/gatekeeper-gatekeeper:3.22.2 --base no-crds --work-dir ./gatekeeper-gatekeeper-3-22-2-no-crds --non-interactive --namespace default

say "Read what was rendered; nothing has touched the cluster yet"
ls ./gatekeeper-gatekeeper-3-22-2-no-crds/out/manifests

say "Ensure the default namespace exists"
kubectl create namespace default --dry-run=client -o yaml | kubectl apply -f -

say "Check 17 CRDs included with this package"
missing_crds=0
if ! kubectl get crd/assign.mutations.gatekeeper.sh >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/assignimage.mutations.gatekeeper.sh >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/assignmetadata.mutations.gatekeeper.sh >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/configs.config.gatekeeper.sh >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/configpodstatuses.status.gatekeeper.sh >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/connections.connection.gatekeeper.sh >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/connectionpodstatuses.status.gatekeeper.sh >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/constraintpodstatuses.status.gatekeeper.sh >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/constrainttemplates.templates.gatekeeper.sh >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/constrainttemplatepodstatuses.status.gatekeeper.sh >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/expansiontemplate.expansion.gatekeeper.sh >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/expansiontemplatepodstatuses.status.gatekeeper.sh >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/modifyset.mutations.gatekeeper.sh >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/mutatorpodstatuses.status.gatekeeper.sh >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/providers.externaldata.gatekeeper.sh >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/providerpodstatuses.status.gatekeeper.sh >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/syncsets.syncset.gatekeeper.sh >/dev/null 2>&1; then
  missing_crds=1
fi
if [ "$missing_crds" -eq 1 ]; then
  kubectl apply --server-side -f ./gatekeeper-gatekeeper-3-22-2-no-crds/package/prerequisites/target-facts/no-crds-crds.yaml
else
  say "The required CRDs already exist; leave them under their current owner"
fi
kubectl wait --for=condition=Established --timeout=120s crd/assign.mutations.gatekeeper.sh
kubectl wait --for=condition=Established --timeout=120s crd/assignimage.mutations.gatekeeper.sh
kubectl wait --for=condition=Established --timeout=120s crd/assignmetadata.mutations.gatekeeper.sh
kubectl wait --for=condition=Established --timeout=120s crd/configs.config.gatekeeper.sh
kubectl wait --for=condition=Established --timeout=120s crd/configpodstatuses.status.gatekeeper.sh
kubectl wait --for=condition=Established --timeout=120s crd/connections.connection.gatekeeper.sh
kubectl wait --for=condition=Established --timeout=120s crd/connectionpodstatuses.status.gatekeeper.sh
kubectl wait --for=condition=Established --timeout=120s crd/constraintpodstatuses.status.gatekeeper.sh
kubectl wait --for=condition=Established --timeout=120s crd/constrainttemplates.templates.gatekeeper.sh
kubectl wait --for=condition=Established --timeout=120s crd/constrainttemplatepodstatuses.status.gatekeeper.sh
kubectl wait --for=condition=Established --timeout=120s crd/expansiontemplate.expansion.gatekeeper.sh
kubectl wait --for=condition=Established --timeout=120s crd/expansiontemplatepodstatuses.status.gatekeeper.sh
kubectl wait --for=condition=Established --timeout=120s crd/modifyset.mutations.gatekeeper.sh
kubectl wait --for=condition=Established --timeout=120s crd/mutatorpodstatuses.status.gatekeeper.sh
kubectl wait --for=condition=Established --timeout=120s crd/providers.externaldata.gatekeeper.sh
kubectl wait --for=condition=Established --timeout=120s crd/providerpodstatuses.status.gatekeeper.sh
kubectl wait --for=condition=Established --timeout=120s crd/syncsets.syncset.gatekeeper.sh

if [ -d ./gatekeeper-gatekeeper-3-22-2-no-crds/out/secrets ]; then
  say "Apply rendered Secrets first"
  kubectl apply -f ./gatekeeper-gatekeeper-3-22-2-no-crds/out/secrets
fi

say "Apply the rendered objects"
kubectl apply -f ./gatekeeper-gatekeeper-3-22-2-no-crds/out/manifests

say "Done. The cluster received exactly the files in ./gatekeeper-gatekeeper-3-22-2-no-crds/out."
