#!/usr/bin/env bash
# bitnami/zookeeper 13.8.7 - base variant: ha
# Path: pull the package, render this base variant locally, read the objects,
# then apply them with kubectl. No ConfigHub account is needed.
# Generated by scripts/generate-public-site.mjs from the committed package
# data for this base variant. Chart page: https://confighub.github.io/helm-expt/site/charts/bitnami-zookeeper-13-8-7.html
set -euo pipefail

say() { printf '\n>> %s\n' "$*"; }

if ! command -v cub >/dev/null 2>&1; then
  printf 'cub is not installed. Install the cub CLI with:\n  curl -fsSL https://hub.confighub.com/cub/install.sh | bash\nthen add ~/.confighub/bin to your PATH and re-run this script.\n' >&2
  exit 1
fi

# Installer is a cub plugin. Check it before this script does any work.
if ! cub installer --help >/dev/null 2>&1; then
  printf 'The cub installer plugin is missing. Follow https://confighub.github.io/helm-expt/site/try.html#install-cub, then re-run this script.\n' >&2
  exit 1
fi

if ! command -v kustomize >/dev/null 2>&1; then
  printf 'kustomize is missing. Follow https://confighub.github.io/helm-expt/site/try.html#install-cub, then re-run this script.\n' >&2
  exit 1
fi

if ! command -v kubectl >/dev/null 2>&1; then
  printf 'kubectl is required for the apply step.\n' >&2
  exit 1
fi

say "Pull the package and render the ha base variant into ./bitnami-zookeeper-13-8-7-ha"
cub installer setup --pull oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/bitnami-zookeeper:13.8.7@sha256:bdae202754e9af6bf276216c3002b4bae869988024ef8db33e792b90fa7bb5c0 --base ha --work-dir ./bitnami-zookeeper-13-8-7-ha --non-interactive --namespace default

say "Read what was rendered; nothing has touched the cluster yet"
ls ./bitnami-zookeeper-13-8-7-ha/out/manifests

say "Ensure the default namespace exists"
kubectl create namespace default --dry-run=client -o yaml | kubectl apply -f -

if [ -d ./bitnami-zookeeper-13-8-7-ha/out/secrets ]; then
  say "Apply rendered Secrets first"
  kubectl apply -f ./bitnami-zookeeper-13-8-7-ha/out/secrets
fi

say "Apply the rendered objects"
kubectl apply -f ./bitnami-zookeeper-13-8-7-ha/out/manifests

say "Done. The cluster received exactly the files in ./bitnami-zookeeper-13-8-7-ha/out."
