#!/usr/bin/env bash
# prometheus-community/kube-prometheus-stack 85.3.3 - base variant: default
# Path: pull the package, render this base variant locally, read the objects,
# then apply them with kubectl. No ConfigHub account is needed.
# Generated by scripts/generate-public-site.mjs from the committed package
# data for this base variant. Chart page: https://confighub.github.io/helm-expt/site/charts/prometheus-community-kube-prometheus-stack-85-3-3.html
set -euo pipefail

say() { printf '\n>> %s\n' "$*"; }

if ! command -v cub >/dev/null 2>&1; then
  printf 'cub is not installed. Install it with:\n  curl -fsSL https://hub.confighub.com/cub/install.sh | bash\nthen add ~/.confighub/bin to your PATH and re-run this script.\n' >&2
  exit 1
fi

if ! command -v kubectl >/dev/null 2>&1; then
  printf 'kubectl is required for the apply step.\n' >&2
  exit 1
fi

say "Pull the package and render the default base variant into ./prometheus-community-kube-prometheus-stack-85-3-3-default"
cub installer setup --pull oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/prometheus-community-kube-prometheus-stack:85.3.3 --base default --work-dir ./prometheus-community-kube-prometheus-stack-85-3-3-default --non-interactive --namespace monitoring

say "Read what was rendered; nothing has touched the cluster yet"
ls ./prometheus-community-kube-prometheus-stack-85-3-3-default/out/manifests

say "Ensure the monitoring namespace exists"
kubectl create namespace monitoring --dry-run=client -o yaml | kubectl apply -f -

if [ "${REQUIREMENTS_READY:-0}" != "1" ]; then
  cat >&2 <<'EOF_REQUIREMENTS'
This base variant needs resources you must create with your own values first:
  - Secret monitoring/kube-prometheus-stack-admission keys cert,key
    kubectl -n monitoring create secret generic kube-prometheus-stack-admission --from-literal=cert=<value> --from-literal=key=<value>
Substitute the <...> placeholders and create these, then re-run with:
  REQUIREMENTS_READY=1 bash try.sh
EOF_REQUIREMENTS
  exit 1
fi

if [ -d ./prometheus-community-kube-prometheus-stack-85-3-3-default/out/secrets ]; then
  say "Apply rendered Secrets first"
  kubectl apply -f ./prometheus-community-kube-prometheus-stack-85-3-3-default/out/secrets
fi

say "Apply the rendered objects"
kubectl apply -f ./prometheus-community-kube-prometheus-stack-85-3-3-default/out/manifests

say "Done. The cluster received exactly the files in ./prometheus-community-kube-prometheus-stack-85-3-3-default/out."
