apiVersion: helm-expt.confighub.com/v1alpha1
kind: InstallerPackagePublicationReceipt
metadata:
  name: prometheus-community-prometheus-blackbox-exporter-11.10.0
spec:
  ref: oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/prometheus-community-prometheus-blackbox-exporter:11.10.0
  observedAt: "2026-08-08T20:47:38.470Z"
  package:
    path: packages/prometheus-community/prometheus-blackbox-exporter/11.10.0
    sha256: 3eb5efd08840b14d24050f793f65e86ea13fbf6ef09986298f9f76e2c142e040
  commands:
    package: "cub installer package packages/prometheus-community/prometheus-blackbox-exporter/11.10.0 -o <tmp>/prometheus-community-prometheus-blackbox-exporter-11.10.0.tgz"
    push: "cub installer push <tmp>/prometheus-community-prometheus-blackbox-exporter-11.10.0.tgz oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/prometheus-community-prometheus-blackbox-exporter:11.10.0"
    inspect: "cub installer inspect oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/prometheus-community-prometheus-blackbox-exporter:11.10.0 --json"
  outputs:
    package: |
      Bundled prometheus-community-prometheus-blackbox-exporter@
        output: /var/folders/4l/8wvwwzxs3xl78749bmmqzzbw0000gp/T/helm-expt-installer-oci-poPjne/prometheus-community-prometheus-blackbox-exporter-11.10.0.tgz
        files:  6
        size:   1540 bytes
        digest: sha256:3eb5efd08840b14d24050f793f65e86ea13fbf6ef09986298f9f76e2c142e040
    push: |
      Pushed europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/prometheus-community-prometheus-blackbox-exporter:11.10.0
        manifest: sha256:8faaeebfabe92e9ddfbc866a2ad14666fe8efc8a4d6aa678eea49ef8bae8111e
        layer:    sha256:3eb5efd08840b14d24050f793f65e86ea13fbf6ef09986298f9f76e2c142e040 (1540 bytes, 6 files)
    inspectJSONSHA256: c92ef766cbe003b66b1a9e470a245e46e8d6b5e0e1952bffe9dc61ec6bb36997
