#!/usr/bin/env bash
# jetstack/cert-manager v1.20.2 - preset: default
# Path: pull the package, render this preset locally, read the objects,
# then apply them with kubectl. No ConfigHub account is needed.
# Generated by scripts/generate-public-site.mjs from the committed package
# data for this preset. Chart page: https://confighub.github.io/helm-expt/site/charts/jetstack-cert-manager-v1-20-2.html
set -euo pipefail

say() { printf '\n>> %s\n' "$*"; }

if ! command -v cub >/dev/null 2>&1; then
  printf 'cub is not installed. Install it with:\n  curl -fsSL https://hub.confighub.com/cub/install.sh | bash\nthen add ~/.confighub/bin to your PATH and re-run this script.\n' >&2
  exit 1
fi

if ! command -v kubectl >/dev/null 2>&1; then
  printf 'kubectl is required for the apply step.\n' >&2
  exit 1
fi

say "Pull the package and render the default preset into ./jetstack-cert-manager-v1-20-2-default"
cub installer setup --pull oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/jetstack-cert-manager:v1.20.2 --base default --work-dir ./jetstack-cert-manager-v1-20-2-default --non-interactive --namespace cert-manager

say "Read what was rendered; nothing has touched the cluster yet"
ls ./jetstack-cert-manager-v1-20-2-default/out/manifests

say "Ensure the cert-manager namespace exists"
kubectl create namespace cert-manager --dry-run=client -o yaml | kubectl apply -f -

if [ "${REQUIREMENTS_READY:-0}" != "1" ]; then
  cat >&2 <<'EOF_REQUIREMENTS'
This preset needs resources you must create with your own values first:
  - CRD challenges.acme.cert-manager.io
    kubectl apply -f <crd-manifest.yaml>
  - CRD orders.acme.cert-manager.io
    kubectl apply -f <crd-manifest.yaml>
  - CRD certificaterequests.cert-manager.io
    kubectl apply -f <crd-manifest.yaml>
  - CRD certificates.cert-manager.io
    kubectl apply -f <crd-manifest.yaml>
  - CRD clusterissuers.cert-manager.io
    kubectl apply -f <crd-manifest.yaml>
  - CRD issuers.cert-manager.io
    kubectl apply -f <crd-manifest.yaml>
Substitute the <...> placeholders and create these, then re-run with:
  REQUIREMENTS_READY=1 bash try.sh
EOF_REQUIREMENTS
  exit 1
fi

if [ -d ./jetstack-cert-manager-v1-20-2-default/out/secrets ]; then
  say "Apply rendered Secrets first"
  kubectl apply -f ./jetstack-cert-manager-v1-20-2-default/out/secrets
fi

say "Apply the rendered objects"
kubectl apply -f ./jetstack-cert-manager-v1-20-2-default/out/manifests

say "Done. The cluster received exactly the files in ./jetstack-cert-manager-v1-20-2-default/out."
