#!/usr/bin/env bash
# hashicorp/vault 0.32.0 - base variant: ha-raft-ui
# Path: pull the package, render this base variant locally, read the objects,
# then apply them with kubectl. No ConfigHub account is needed.
# Generated by scripts/generate-public-site.mjs from the committed package
# data for this base variant. Chart page: https://confighub.github.io/helm-expt/site/charts/hashicorp-vault-0-32-0.html
set -euo pipefail

say() { printf '\n>> %s\n' "$*"; }

if ! command -v cub >/dev/null 2>&1; then
  printf 'cub is not installed. Install the cub CLI with:\n  curl -fsSL https://hub.confighub.com/cub/install.sh | bash\nthen add ~/.confighub/bin to your PATH and re-run this script.\n' >&2
  exit 1
fi

# Public cub releases include the installer command. This guard catches
# an older or incomplete CLI before this script does any work.
if ! cub installer --help >/dev/null 2>&1; then
  printf 'This cub build does not include cub installer. Install or upgrade the cub CLI with:\n  curl -fsSL https://hub.confighub.com/cub/install.sh | bash\nthen add ~/.confighub/bin to your PATH and re-run this script.\n' >&2
  exit 1
fi

if ! command -v kubectl >/dev/null 2>&1; then
  printf 'kubectl is required for the apply step.\n' >&2
  exit 1
fi

say "Pull the package and render the ha-raft-ui base variant into ./hashicorp-vault-0-32-0-ha-raft-ui"
cub installer setup --pull oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/hashicorp-vault:0.32.0 --base ha-raft-ui --work-dir ./hashicorp-vault-0-32-0-ha-raft-ui --non-interactive --namespace vault

say "Read what was rendered; nothing has touched the cluster yet"
ls ./hashicorp-vault-0-32-0-ha-raft-ui/out/manifests

say "Ensure the vault namespace exists"
kubectl create namespace vault --dry-run=client -o yaml | kubectl apply -f -

say "Requirement before apply: minimum schedulable nodes 3"
if ! use a target with at least 3 schedulable nodes before applying this base; then
  printf '!! The requirement command failed. If the resource already exists, review it and re-run; otherwise fix the error above.\n' >&2
  exit 1
fi

if [ -d ./hashicorp-vault-0-32-0-ha-raft-ui/out/secrets ]; then
  say "Apply rendered Secrets first"
  kubectl apply -f ./hashicorp-vault-0-32-0-ha-raft-ui/out/secrets
fi

say "Apply the rendered objects"
kubectl apply -f ./hashicorp-vault-0-32-0-ha-raft-ui/out/manifests

say "Done. The cluster received exactly the files in ./hashicorp-vault-0-32-0-ha-raft-ui/out."
