#!/usr/bin/env bash
# kubeflow/kubeflow-trainer 2.2.0 - base variant: aicr-eks-training-v1-0-0
# Path: pull the package, render this base variant locally, read the objects,
# then apply them with kubectl. No ConfigHub account is needed.
# Generated by scripts/generate-public-site.mjs from the committed package
# data for this base variant. Chart page: https://confighub.github.io/helm-expt/site/charts/kubeflow-kubeflow-trainer-2-2-0.html
set -euo pipefail

say() { printf '\n>> %s\n' "$*"; }

if ! command -v cub >/dev/null 2>&1; then
  printf 'cub is not installed. Install the cub CLI with:\n  curl -fsSL https://hub.confighub.com/cub/install.sh | bash\nthen add ~/.confighub/bin to your PATH and re-run this script.\n' >&2
  exit 1
fi

# Installer is a cub plugin. Check it before this script does any work.
if ! cub installer --help >/dev/null 2>&1; then
  printf 'The cub installer plugin is missing. Follow https://confighub.github.io/helm-expt/site/try.html#install-cub, then re-run this script.\n' >&2
  exit 1
fi

if ! command -v kustomize >/dev/null 2>&1; then
  printf 'kustomize is missing. Follow https://confighub.github.io/helm-expt/site/try.html#install-cub, then re-run this script.\n' >&2
  exit 1
fi

if ! command -v kubectl >/dev/null 2>&1; then
  printf 'kubectl is required for the apply step.\n' >&2
  exit 1
fi

say "Pull the package and render the aicr-eks-training-v1-0-0 base variant into ./kubeflow-kubeflow-trainer-2-2-0-aicr-eks-training-v1-0-0"
cub installer setup --pull oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/kubeflow-kubeflow-trainer:2.2.0@sha256:5bfc86cf6c84e972ffdf41aab3b6c467d6cc0be157066e70bc0440f43dc08df6 --base aicr-eks-training-v1-0-0 --work-dir ./kubeflow-kubeflow-trainer-2-2-0-aicr-eks-training-v1-0-0 --non-interactive --namespace kubeflow

say "Read what was rendered; nothing has touched the cluster yet"
ls ./kubeflow-kubeflow-trainer-2-2-0-aicr-eks-training-v1-0-0/out/manifests

wait_for_crd() {
  crd_name="$1"
  deadline=$(( $(date +%s) + 180 ))
  until kubectl get "crd/${crd_name}" >/dev/null 2>&1; do
    if [ "$(date +%s)" -ge "$deadline" ]; then
      printf "CRD %s did not appear within 180 seconds.\n" "$crd_name" >&2
      return 1
    fi
    sleep 2
  done
  kubectl wait --for=condition=Established --timeout=120s "crd/${crd_name}"
}

say "Ensure the kubeflow namespace exists"
kubectl create namespace kubeflow --dry-run=client -o yaml | kubectl apply -f -

say "Check 4 CRDs included with this package"
missing_crds=0
if ! kubectl get crd/clustertrainingruntimes.trainer.kubeflow.org >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/jobsets.jobset.x-k8s.io >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/trainingruntimes.trainer.kubeflow.org >/dev/null 2>&1; then
  missing_crds=1
fi
if ! kubectl get crd/trainjobs.trainer.kubeflow.org >/dev/null 2>&1; then
  missing_crds=1
fi
if [ "$missing_crds" -eq 1 ]; then
  kubectl apply --server-side -f ./kubeflow-kubeflow-trainer-2-2-0-aicr-eks-training-v1-0-0/package/prerequisites/target-facts/aicr-eks-training-v1-0-0-crds.yaml
else
  say "The required CRDs already exist; leave them under their current owner"
fi
wait_for_crd clustertrainingruntimes.trainer.kubeflow.org
wait_for_crd jobsets.jobset.x-k8s.io
wait_for_crd trainingruntimes.trainer.kubeflow.org
wait_for_crd trainjobs.trainer.kubeflow.org

if [ -d ./kubeflow-kubeflow-trainer-2-2-0-aicr-eks-training-v1-0-0/out/secrets ]; then
  say "Apply rendered Secrets first"
  kubectl apply -f ./kubeflow-kubeflow-trainer-2-2-0-aicr-eks-training-v1-0-0/out/secrets
fi

say "Apply the rendered objects"
kubectl apply -f ./kubeflow-kubeflow-trainer-2-2-0-aicr-eks-training-v1-0-0/out/manifests

say "Done. The cluster received exactly the files in ./kubeflow-kubeflow-trainer-2-2-0-aicr-eks-training-v1-0-0/out."
