apiVersion: "helm-expt.confighub.com/v1alpha1"
kind: "Variant"
metadata:
  name: "admission-disabled"
spec:
  recipe: "../../recipe.yaml"
  namespace: "ingress-nginx"
  releaseName: "ingress-nginx"
  valuesProfile: "../../effective-values-admission-disabled.yaml"
  capabilityProfile:
    kubeVersion: "1.30.0"
    apiVersions:
      []
  hookPolicy: "no-hooks"
