#!/usr/bin/env bash
# bitnami/postgresql 18.6.7 - preset: static-passwords
# Path: pull the package, render this preset locally, read the objects,
# then apply them with kubectl. No ConfigHub account is needed.
# Generated by scripts/generate-public-site.mjs from the committed package
# data for this preset. Chart page: https://confighub.github.io/helm-expt/site/charts/bitnami-postgresql-18-6-7.html
set -euo pipefail

say() { printf '\n>> %s\n' "$*"; }

if ! command -v cub >/dev/null 2>&1; then
  printf 'cub is not installed. Install it with:\n  curl -fsSL https://hub.confighub.com/cub/install.sh | bash\nthen add ~/.confighub/bin to your PATH and re-run this script.\n' >&2
  exit 1
fi

if ! command -v kubectl >/dev/null 2>&1; then
  printf 'kubectl is required for the apply step.\n' >&2
  exit 1
fi

say "Pull the package and render the static-passwords preset into ./bitnami-postgresql-18-6-7-static-passwords"
cub installer setup --pull oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/bitnami-postgresql:18.6.7 --base static-passwords --work-dir ./bitnami-postgresql-18-6-7-static-passwords --non-interactive --namespace postgresql

say "Read what was rendered; nothing has touched the cluster yet"
ls ./bitnami-postgresql-18-6-7-static-passwords/out/manifests

say "Ensure the postgresql namespace exists"
kubectl create namespace postgresql --dry-run=client -o yaml | kubectl apply -f -

if [ -d ./bitnami-postgresql-18-6-7-static-passwords/out/secrets ]; then
  say "Apply rendered Secrets first"
  kubectl apply -f ./bitnami-postgresql-18-6-7-static-passwords/out/secrets
fi

say "Apply the rendered objects"
kubectl apply -f ./bitnami-postgresql-18-6-7-static-passwords/out/manifests

say "Done. The cluster received exactly the files in ./bitnami-postgresql-18-6-7-static-passwords/out."
