apiVersion: "helm-expt.confighub.com/v1alpha1"
kind: "InstallerPackageReceipt"
metadata:
  name: "bitnami-rabbitmq-16.0.14"
spec:
  chart:
    name: "rabbitmq"
    repository: "bitnami"
    version: "16.0.14"
  deterministicBundle:
    byteIdenticalAcrossTwoLocalBundles: true
    command: "cub installer package packages/bitnami/rabbitmq/16.0.14 -o <tmp>/rabbitmq-16.0.14.tgz"
    sha256: "bf046d286d243fe21caa45e150b2a540893840ffb0ac61c6b4cbf4e6cb41961a"
  package:
    name: "bitnami-rabbitmq"
    path: "packages/bitnami/rabbitmq/16.0.14"
    sourceFiles:
      -
        path: "README.md"
        sha256: "6e99090470dc1edc08d8b300173f47f8ce59b5c10d9362931d4459e1b3c0503f"
        bytes: 184
      -
        path: "bases/existing-secret/kustomization.yaml"
        sha256: "44d52637f259f73730afd3a41d7350391387456ab7c418f201eec1ef73720153"
        bytes: 99
      -
        path: "bases/existing-secret/upstream.yaml"
        sha256: "cdff3262264844b099e7f4421f1bbd5027360c2d23ba34667506d85255c4b6f2"
        bytes: 14722
      -
        path: "bases/static-passwords/kustomization.yaml"
        sha256: "44d52637f259f73730afd3a41d7350391387456ab7c418f201eec1ef73720153"
        bytes: 99
      -
        path: "bases/static-passwords/upstream.yaml"
        sha256: "81187ce4367f5196ddbaa35ea55b972698f8a474d78a2cdc2908b12290c89f31"
        bytes: 15265
      -
        path: "collector/target-facts.sh"
        sha256: "ce0d79a9bc43e993c5c634c2cc48751b15ef7d1885fe7b70f53782f6d5631fee"
        bytes: 2538
      -
        path: "installer.yaml"
        sha256: "ba9df7f65a1a8aa2b1ced56599c0f3350c5a0527a15da94bdf71121557e92fc8"
        bytes: 1265
    version: "16.0.14"
  setupChecks:
    -
      allowedCubOnlyObjects:
        - "v1|Namespace||rabbitmq"
      base: "static-passwords"
      command: "cub installer setup --pull packages/bitnami/rabbitmq/16.0.14 --base static-passwords --work-dir <tmp> --non-interactive --namespace rabbitmq"
      cubInstallObjectCountIncludingSupport: 11
      helmReleaseObjectCount: 10
      semanticObjectMatches: "10/10"
      separatedSecretCount: 2
      targetFactMode: "not-required"
      targetFactsBound: false
      variant: "static-passwords"
    -
      allowedCubOnlyObjects:
        - "v1|Namespace||rabbitmq"
      base: "existing-secret"
      command: "cub installer setup --pull packages/bitnami/rabbitmq/16.0.14 --base existing-secret --work-dir <tmp> --non-interactive --namespace rabbitmq"
      cubInstallObjectCountIncludingSupport: 10
      helmReleaseObjectCount: 9
      semanticObjectMatches: "9/9"
      separatedSecretCount: 1
      targetFactMode: "collector-facts"
      targetFactsBound: true
      variant: "existing-secret"
