apiVersion: "helm-expt.confighub.com/v1alpha1"
kind: "VariantRevision"
metadata:
  name: "controller-default-reviewed-r001"
  labels:
    confighub.io/chart-ref: "autoscaler/cluster-autoscaler"
    confighub.io/chart-version: "9.57.0"
    confighub.io/proof-tier: "next80-full"
    confighub.io/variant: "controller-default-reviewed"
spec:
  variant: "../../../variants/controller-default-reviewed/variant.yaml"
  revision: "r001"
  digest: "466d6f9b7670813ecf7a1f20d76b80916bb24abae24f9b768fbd8121f030d9f5"
  digestInputs:
    recipeSHA256: "4a194898d2db2cd9178395bf17c51d0961bd7877387eb03ebd61037a28c19e23"
    variantSHA256: "9751e0a2195bb00b1c83ad5ff1260dc7e20b8d4ee7eca5de7d690d4448e626ea"
    effectiveValuesSHA256: "a70f78049dabe34955091d7b41f532adf2e33e6df9c29265dabfbe16aacb5130"
    rendererSHA256: "9b6872662c8c6700de403a3eed17d1c3883cd491012f7bdc22d5631bd59e456a"
    renderedObjectSetSHA256: "b89d1d1b0acbcfc12528c4aa8b29451000eb5734e04818aeedabf713c958837a"
  rendered:
    releaseObjects: "rendered/release-objects.yaml"
    objectInventory: "rendered/object-inventory.yaml"
    objectCount: 8
