apiVersion: "catalog.confighub.com/v1alpha1"
kind: "InstallerPackageRecordIndex"
metadata:
  name: "bitnami-postgresql-18.6.7"
spec:
  package:
    name: "bitnami-postgresql"
    version: "18.6.7"
    role: "multi-preset-source-package"
  recordsAreDeployable: false
  repository:
    url: "https://github.com/confighub/helm-expt"
    evidenceBaseUrl: "https://github.com/confighub/helm-expt/blob/main/"
  bases:
    -
      name: "existing-secret"
      objects: "bases/existing-secret/upstream.yaml"
      sourceAndIntent: "records/existing-secret/source-and-intent.yaml"
      sourceSpecificIntent: "records/existing-secret/helm-render-intent.yaml"
    -
      name: "static-passwords"
      objects: "bases/static-passwords/upstream.yaml"
      sourceAndIntent: "records/static-passwords/source-and-intent.yaml"
      sourceSpecificIntent: "records/static-passwords/helm-render-intent.yaml"
