apiVersion: "helm-expt.confighub.com/v1alpha1"
kind: "InstallerPackageReceipt"
metadata:
  name: "jaegertracing-jaeger-4-8-0"
spec:
  chart:
    name: "jaeger"
    repository: "jaegertracing"
    version: "4.8.0"
  deterministicBundle:
    byteIdenticalAcrossTwoLocalBundles: true
    command: "cub installer package packages/jaegertracing/jaeger/4.8.0 -o <tmp>/jaegertracing-jaeger-4-8-0.tgz"
    sha256: "14533b519f5a269cd30c8cd5432d05517920fdb1d9c9eb92caf7ef0f912d510b"
  package:
    name: "jaegertracing-jaeger"
    path: "packages/jaegertracing/jaeger/4.8.0"
    sourceFiles:
      -
        path: "README.md"
        sha256: "0c1e0aa3112fc3517e8913608044f90ae5b95a98b53619087c8f712c90e3437a"
        bytes: 200
      -
        path: "bases/default/kustomization.yaml"
        sha256: "44d52637f259f73730afd3a41d7350391387456ab7c418f201eec1ef73720153"
        bytes: 99
      -
        path: "bases/default/upstream.yaml"
        sha256: "da24b2c05d1c43492627f3d01b0d675ea01bb2acb38017a18dec5a70c55b7939"
        bytes: 4685
      -
        path: "installer.yaml"
        sha256: "cbb227533453d98a3f96e827933ef61bc4595a5992156805cbb0e981743df017"
        bytes: 313
      -
        path: "records/README.md"
        sha256: "191c9799224aa0ae46420a9b1ba6a00c10b487f90aec9d8d63fca2ee37ec9758"
        bytes: 997
      -
        path: "records/default/helm-render-intent.yaml"
        sha256: "16ea302f486314958682cc03401d2d1778840a01ed8a1c6dc2a7901da6a3a474"
        bytes: 5309
      -
        path: "records/default/source-and-intent.yaml"
        sha256: "33419ce12b3097847ec27dee316c6d63346dc1b11f0b2f9a1153746a3be3ed2d"
        bytes: 8728
      -
        path: "records/index.yaml"
        sha256: "ec70c56c6e85590d689f50ed6e42456e3f8fdb68f058f45dc5e90c3245d5ed9f"
        bytes: 622
    version: "4.8.0"
  setupChecks:
    -
      allowedCubOnlyObjects:
        - "v1|Namespace||default"
      base: "default"
      command: "cub installer setup --pull packages/jaegertracing/jaeger/4.8.0 --base default --work-dir <tmp> --non-interactive --namespace default"
      cubInstallObjectCountIncludingSupport: 4
      helmReleaseObjectCount: 3
      semanticObjectMatches: "3/3"
      separatedSecretCount: 0
      variant: "default"
