#!/usr/bin/env bash
# bitnami/mongodb 19.0.7 - base variant: static-passwords
# Path: pull the package, render this base variant locally, read the objects,
# then apply them with kubectl. No ConfigHub account is needed.
# Generated by scripts/generate-public-site.mjs from the committed package
# data for this base variant. Chart page: https://confighub.github.io/helm-expt/site/charts/bitnami-mongodb-19-0-7.html
set -euo pipefail

say() { printf '\n>> %s\n' "$*"; }

if ! command -v cub >/dev/null 2>&1; then
  printf 'cub is not installed. Install the cub CLI with:\n  curl -fsSL https://hub.confighub.com/cub/install.sh | bash\nthen add ~/.confighub/bin to your PATH and re-run this script.\n' >&2
  exit 1
fi

# Installer is a cub plugin. Check it before this script does any work.
if ! cub installer --help >/dev/null 2>&1; then
  printf 'The cub installer plugin is missing. Follow https://confighub.github.io/helm-expt/site/try.html#install-cub, then re-run this script.\n' >&2
  exit 1
fi

if ! command -v kustomize >/dev/null 2>&1; then
  printf 'kustomize is missing. Follow https://confighub.github.io/helm-expt/site/try.html#install-cub, then re-run this script.\n' >&2
  exit 1
fi

if ! command -v kubectl >/dev/null 2>&1; then
  printf 'kubectl is required for the apply step.\n' >&2
  exit 1
fi

say "Pull the package and render the static-passwords base variant into ./bitnami-mongodb-19-0-7-static-passwords"
cub installer setup --pull oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/bitnami-mongodb:19.0.7@sha256:1cf506fe86a28ec2fe06badacd29ee69e35747d2a228f040af432ea3c6f65c35 --base static-passwords --work-dir ./bitnami-mongodb-19-0-7-static-passwords --non-interactive --namespace mongodb

say "Read what was rendered; nothing has touched the cluster yet"
ls ./bitnami-mongodb-19-0-7-static-passwords/out/manifests

say "Ensure the mongodb namespace exists"
kubectl create namespace mongodb --dry-run=client -o yaml | kubectl apply -f -

if [ -d ./bitnami-mongodb-19-0-7-static-passwords/out/secrets ]; then
  say "Apply rendered Secrets first"
  kubectl apply -f ./bitnami-mongodb-19-0-7-static-passwords/out/secrets
fi

say "Apply the rendered objects"
kubectl apply -f ./bitnami-mongodb-19-0-7-static-passwords/out/manifests

say "Done. The cluster received exactly the files in ./bitnami-mongodb-19-0-7-static-passwords/out."
