apiVersion: "helm-expt.confighub.com/v1alpha1"
kind: "InstallerPackageReceipt"
metadata:
  name: "haproxytech-kubernetes-ingress-1-52-0"
spec:
  chart:
    name: "kubernetes-ingress"
    repository: "haproxytech"
    version: "1.52.0"
  deterministicBundle:
    byteIdenticalAcrossTwoLocalBundles: true
    command: "cub installer package packages/haproxytech/kubernetes-ingress/1.52.0 -o <tmp>/haproxytech-kubernetes-ingress-1-52-0.tgz"
    sha256: "d5af5579ae1f31270158b65bf1f294b1182e7d673af2e856836e29782d54a00a"
  package:
    name: "haproxytech-kubernetes-ingress"
    path: "packages/haproxytech/kubernetes-ingress/1.52.0"
    sourceFiles:
      -
        path: "README.md"
        sha256: "3ac23d7ba9a6743c27f12126c77a65bb5867ec18ff6be0ce9eb8f9c3d215067a"
        bytes: 211
      -
        path: "bases/default/kustomization.yaml"
        sha256: "44d52637f259f73730afd3a41d7350391387456ab7c418f201eec1ef73720153"
        bytes: 99
      -
        path: "bases/default/upstream.yaml"
        sha256: "d04b79ade525cfe276e761918d319794e8e662ef896ae3418a42e7c781ded544"
        bytes: 8385
      -
        path: "installer.yaml"
        sha256: "01e836bff0b5b9fd8385689e6bca1b0ccb2cf493ef8ce87d766552b56e338de3"
        bytes: 345
      -
        path: "records/README.md"
        sha256: "191c9799224aa0ae46420a9b1ba6a00c10b487f90aec9d8d63fca2ee37ec9758"
        bytes: 997
      -
        path: "records/default/helm-render-intent.yaml"
        sha256: "d535fca6526146b1f11558c2459c04b736b64463c7ab81b20fb564656f8244f6"
        bytes: 5581
      -
        path: "records/default/source-and-intent.yaml"
        sha256: "ebb9a8b097f27162440e16a38c00a53fa89bf52771ca054cf77aa1020fce3533"
        bytes: 9004
      -
        path: "records/index.yaml"
        sha256: "fa67b78f581b7dcfc65ff95094b66c8678f6cd663abbd9f56e475b3e7e2056d0"
        bytes: 644
    version: "1.52.0"
  setupChecks:
    -
      allowedCubOnlyObjects:
        - "v1|Namespace||default"
      base: "default"
      command: "cub installer setup --pull packages/haproxytech/kubernetes-ingress/1.52.0 --base default --work-dir <tmp> --non-interactive --namespace default"
      cubInstallObjectCountIncludingSupport: 8
      helmReleaseObjectCount: 7
      semanticObjectMatches: "7/7"
      separatedSecretCount: 0
      variant: "default"
