#!/usr/bin/env bash
# grafana/alloy 1.12.1 - base variant: default
# Path: pull the package, render this base variant locally, read the objects,
# then apply them with kubectl. No ConfigHub account is needed.
# Generated by scripts/generate-public-site.mjs from the committed package
# data for this base variant. Chart page: https://confighub.github.io/helm-expt/site/charts/grafana-alloy-1-12-1.html
set -euo pipefail

say() { printf '\n>> %s\n' "$*"; }

if ! command -v cub >/dev/null 2>&1; then
  printf 'cub is not installed. Install the cub CLI with:\n  curl -fsSL https://hub.confighub.com/cub/install.sh | bash\nthen add ~/.confighub/bin to your PATH and re-run this script.\n' >&2
  exit 1
fi

# Installer is a cub plugin. Check it before this script does any work.
if ! cub installer --help >/dev/null 2>&1; then
  printf 'The cub installer plugin is missing. Follow https://confighub.github.io/helm-expt/site/try.html#install-cub, then re-run this script.\n' >&2
  exit 1
fi

if ! command -v kustomize >/dev/null 2>&1; then
  printf 'kustomize is missing. Follow https://confighub.github.io/helm-expt/site/try.html#install-cub, then re-run this script.\n' >&2
  exit 1
fi

if ! command -v kubectl >/dev/null 2>&1; then
  printf 'kubectl is required for the apply step.\n' >&2
  exit 1
fi

say "Pull the package and render the default base variant into ./grafana-alloy-1-12-1-default"
cub installer setup --pull oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/grafana-alloy:1.12.1@sha256:ccce74fea2d96aa240eeb109cc8e4d15d8636c16fea3e3eddc0f1571937505f3 --base default --work-dir ./grafana-alloy-1-12-1-default --non-interactive --namespace alloy

say "Read what was rendered; nothing has touched the cluster yet"
ls ./grafana-alloy-1-12-1-default/out/manifests

say "Ensure the alloy namespace exists"
kubectl create namespace alloy --dry-run=client -o yaml | kubectl apply -f -

if [ -d ./grafana-alloy-1-12-1-default/out/secrets ]; then
  say "Apply rendered Secrets first"
  kubectl apply -f ./grafana-alloy-1-12-1-default/out/secrets
fi

say "Apply the rendered objects"
kubectl apply -f ./grafana-alloy-1-12-1-default/out/manifests

say "Done. The cluster received exactly the files in ./grafana-alloy-1-12-1-default/out."
