#!/usr/bin/env bash
# haproxytech/kubernetes-ingress 1.52.0 - base variant: default
# Path: pull the package, render this base variant locally, read the objects,
# then apply them with kubectl. No ConfigHub account is needed.
# Generated by scripts/generate-public-site.mjs from the committed package
# data for this base variant. Chart page: https://confighub.github.io/helm-expt/site/charts/haproxytech-kubernetes-ingress-1-52-0.html
set -euo pipefail

say() { printf '\n>> %s\n' "$*"; }

if ! command -v cub >/dev/null 2>&1; then
  printf 'cub is not installed. Install it with:\n  curl -fsSL https://hub.confighub.com/cub/install.sh | bash\nthen add ~/.confighub/bin to your PATH and re-run this script.\n' >&2
  exit 1
fi

if ! command -v kubectl >/dev/null 2>&1; then
  printf 'kubectl is required for the apply step.\n' >&2
  exit 1
fi

say "Pull the package and render the default base variant into ./haproxytech-kubernetes-ingress-1-52-0-default"
cub installer setup --pull oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/haproxytech-kubernetes-ingress:1.52.0 --base default --work-dir ./haproxytech-kubernetes-ingress-1-52-0-default --non-interactive --namespace default

say "Read what was rendered; nothing has touched the cluster yet"
ls ./haproxytech-kubernetes-ingress-1-52-0-default/out/manifests

say "Ensure the default namespace exists"
kubectl create namespace default --dry-run=client -o yaml | kubectl apply -f -

if [ -d ./haproxytech-kubernetes-ingress-1-52-0-default/out/secrets ]; then
  say "Apply rendered Secrets first"
  kubectl apply -f ./haproxytech-kubernetes-ingress-1-52-0-default/out/secrets
fi

say "Apply the rendered objects"
kubectl apply -f ./haproxytech-kubernetes-ingress-1-52-0-default/out/manifests

say "Done. The cluster received exactly the files in ./haproxytech-kubernetes-ingress-1-52-0-default/out."
