#!/usr/bin/env bash
# grafana/tempo 1.24.4 - preset: s3-query-observability
# Path: render this preset locally, then upload the objects to your
# ConfigHub Space as Units you can edit, diff, and deliver.
# Needs a ConfigHub account: run cub auth login once before this script.
# Generated by scripts/generate-public-site.mjs from the committed package
# data for this preset. Chart page: https://confighub.github.io/helm-expt/site/charts/grafana-tempo-1-24-4.html
set -euo pipefail

say() { printf '\n>> %s\n' "$*"; }

if ! command -v cub >/dev/null 2>&1; then
  printf 'cub is not installed. Install it with:\n  curl -fsSL https://hub.confighub.com/cub/install.sh | bash\nthen add ~/.confighub/bin to your PATH and re-run this script.\n' >&2
  exit 1
fi

SPACE="${CUB_SPACE:-helm-tempo-s3-query-observability}"

say "Check ConfigHub auth"
if ! cub auth status >/dev/null 2>&1; then
  printf 'Not logged in. Run: cub auth login\nThen re-run this script.\n' >&2
  exit 1
fi

say "Render the s3-query-observability preset into ./grafana-tempo-1-24-4-s3-query-observability"
cub installer setup --pull oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/grafana-tempo:1.24.4 --base s3-query-observability --work-dir ./grafana-tempo-1-24-4-s3-query-observability --non-interactive --namespace tempo

say "Upload the rendered objects to Space ${SPACE} (created on first upload)"
cub installer upload --work-dir ./grafana-tempo-1-24-4-s3-query-observability --space "${SPACE}"

say "Uploaded. See your Units:"
printf '  cub unit list --space %s\n  or open https://hub.confighub.com and find that Space.\n' "${SPACE}"

# Before applying this preset from ConfigHub to a cluster, it still needs:
#   - Secret tempo/tempo-s3-credentials keys access_key,secret_key (suggested: kubectl -n tempo create secret generic tempo-s3-credentials --from-literal=access_key=<value> --from-literal=secret_key=<value>)
#   - CRD servicemonitors.monitoring.coreos.com (suggested: kubectl apply -f <crd-manifest.yaml>)
#   - S3-compatible object store tempo/tempo-object-store (suggested: create or bind an S3-compatible endpoint, bucket, and credentials before apply)
