#!/usr/bin/env bash
# grafana/tempo 1.24.4 - base variant: s3-query-observability
# Path: pull the package, render this base variant locally, read the objects,
# then apply them with kubectl. No ConfigHub account is needed.
# Generated by scripts/generate-public-site.mjs from the committed package
# data for this base variant. Chart page: https://confighub.github.io/helm-expt/site/charts/grafana-tempo-1-24-4.html
set -euo pipefail

say() { printf '\n>> %s\n' "$*"; }

if ! command -v cub >/dev/null 2>&1; then
  printf 'cub is not installed. Install it with:\n  curl -fsSL https://hub.confighub.com/cub/install.sh | bash\nthen add ~/.confighub/bin to your PATH and re-run this script.\n' >&2
  exit 1
fi

# The installer subcommand is a plugin and is not in the public cub build
# yet. Stop here, before this script touches any cluster.
if ! cub installer --help >/dev/null 2>&1; then
  printf 'The cub installer command is a plugin that ships separately from the cub CLI and is not yet publicly available. The standard cub install script does not include it.\nThis cub build does not have it, so this script stops now, before any cluster work.\n' >&2
  exit 1
fi

if ! command -v kubectl >/dev/null 2>&1; then
  printf 'kubectl is required for the apply step.\n' >&2
  exit 1
fi

say "Pull the package and render the s3-query-observability base variant into ./grafana-tempo-1-24-4-s3-query-observability"
cub installer setup --pull oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/grafana-tempo:1.24.4 --base s3-query-observability --work-dir ./grafana-tempo-1-24-4-s3-query-observability --non-interactive --namespace tempo

say "Read what was rendered; nothing has touched the cluster yet"
ls ./grafana-tempo-1-24-4-s3-query-observability/out/manifests

say "Ensure the tempo namespace exists"
kubectl create namespace tempo --dry-run=client -o yaml | kubectl apply -f -

say "Requirement before apply: S3-compatible object store tempo/tempo-object-store"
if ! create or bind an S3-compatible endpoint, bucket, and credentials before apply; then
  printf '!! The requirement command failed. If the resource already exists, review it and re-run; otherwise fix the error above.\n' >&2
  exit 1
fi

if [ "${REQUIREMENTS_READY:-0}" != "1" ]; then
  cat >&2 <<'EOF_REQUIREMENTS'
This base variant needs resources you must create with your own values first:
  - Secret tempo/tempo-s3-credentials keys access_key,secret_key
    kubectl -n tempo create secret generic tempo-s3-credentials --from-literal=access_key=<value> --from-literal=secret_key=<value>
  - CRD servicemonitors.monitoring.coreos.com
    kubectl apply -f <crd-manifest.yaml>
Substitute the <...> placeholders and create these, then re-run with:
  REQUIREMENTS_READY=1 bash try.sh
EOF_REQUIREMENTS
  exit 1
fi

if [ -d ./grafana-tempo-1-24-4-s3-query-observability/out/secrets ]; then
  say "Apply rendered Secrets first"
  kubectl apply -f ./grafana-tempo-1-24-4-s3-query-observability/out/secrets
fi

say "Apply the rendered objects"
kubectl apply -f ./grafana-tempo-1-24-4-s3-query-observability/out/manifests

say "Done. The cluster received exactly the files in ./grafana-tempo-1-24-4-s3-query-observability/out."
