apiVersion: installer.confighub.com/v1alpha1
kind: Package
metadata:
  name: "13-gitlab-gitlab"
  version: "10.0.0"
spec:
  bases:
    - name: default
      path: base
      default: true
      description: "Imported Helm render for gitlab/gitlab"
