#!/usr/bin/env bash
# bitnami/redis 25.5.3 - base variant: reuse-existing-secret
# Path: pull the package, render this base variant locally, read the objects,
# then apply them with kubectl. No ConfigHub account is needed.
# Generated by scripts/generate-public-site.mjs from the committed package
# data for this base variant. Chart page: https://confighub.github.io/helm-expt/site/charts/bitnami-redis-25-5-3.html
set -euo pipefail

say() { printf '\n>> %s\n' "$*"; }

if ! command -v cub >/dev/null 2>&1; then
  printf 'cub is not installed. Install the cub CLI with:\n  curl -fsSL https://hub.confighub.com/cub/install.sh | bash\nthen add ~/.confighub/bin to your PATH and re-run this script.\n' >&2
  exit 1
fi

# Installer is a cub plugin. Check it before this script does any work.
if ! cub installer --help >/dev/null 2>&1; then
  printf 'The cub installer plugin is missing. Follow https://confighub.github.io/helm-expt/site/try.html#install-cub, then re-run this script.\n' >&2
  exit 1
fi

if ! command -v kustomize >/dev/null 2>&1; then
  printf 'kustomize is missing. Follow https://confighub.github.io/helm-expt/site/try.html#install-cub, then re-run this script.\n' >&2
  exit 1
fi

if ! command -v kubectl >/dev/null 2>&1; then
  printf 'kubectl is required for the apply step.\n' >&2
  exit 1
fi

say "Pull the package and render the reuse-existing-secret base variant into ./bitnami-redis-25-5-3-reuse-existing-secret"
cub installer setup --pull oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/bitnami-redis:25.5.3@sha256:a216ce212424e05b341ef5000f1798e6014b72b8bc3dce9f315285871037af2a --base reuse-existing-secret --work-dir ./bitnami-redis-25-5-3-reuse-existing-secret --non-interactive --namespace redis

say "Read what was rendered; nothing has touched the cluster yet"
ls ./bitnami-redis-25-5-3-reuse-existing-secret/out/manifests

say "Ensure the redis namespace exists"
kubectl create namespace redis --dry-run=client -o yaml | kubectl apply -f -

say "Requirement before apply: Secret redis/redis-existing-secret key redis-password"
if ! kubectl -n redis create secret generic redis-existing-secret --from-literal=redis-password="$(openssl rand -base64 32)"; then
  printf '!! The requirement command failed. If the resource already exists, review it and re-run; otherwise fix the error above.\n' >&2
  exit 1
fi

if [ -d ./bitnami-redis-25-5-3-reuse-existing-secret/out/secrets ]; then
  say "Apply rendered Secrets first"
  kubectl apply -f ./bitnami-redis-25-5-3-reuse-existing-secret/out/secrets
fi

say "Apply the rendered objects"
kubectl apply -f ./bitnami-redis-25-5-3-reuse-existing-secret/out/manifests

say "Done. The cluster received exactly the files in ./bitnami-redis-25-5-3-reuse-existing-secret/out."
