apiVersion: "installer.confighub.com/v1alpha1"
kind: "Package"
metadata:
  name: "elastic-filebeat"
  version: "8.5.1"
spec:
  bases:
    -
      default: true
      description: "elastic/filebeat default variant rendered from elastic/filebeat@8.5.1"
      name: "default"
      path: "bases/default"
    -
      default: false
      description: "elastic/filebeat node-or-cluster-collector useful base; aliases the default render with a named user start path"
      name: "node-or-cluster-collector"
      path: "bases/node-or-cluster-collector"
