apiVersion: "helm-expt.confighub.com/v1alpha1"
kind: "InstallerPackageReceipt"
metadata:
  name: "prometheus-community-prometheus-blackbox-exporter-11-10-0"
spec:
  chart:
    name: "prometheus-blackbox-exporter"
    repository: "prometheus-community"
    version: "11.10.0"
  deterministicBundle:
    byteIdenticalAcrossTwoLocalBundles: true
    command: "cub installer package packages/prometheus-community/prometheus-blackbox-exporter/11.10.0 -o <tmp>/prometheus-community-prometheus-blackbox-exporter-11-10-0.tgz"
    sha256: "c79ccb65a4813be3c4eecc663fd8d9b1dce4567f220ce9a13f32dfcdc42e1620"
  package:
    name: "prometheus-community-prometheus-blackbox-exporter"
    path: "packages/prometheus-community/prometheus-blackbox-exporter/11.10.0"
    sourceFiles:
      -
        path: "README.md"
        sha256: "6a69858eb4d65da3e20df9a1705ed563550681dfac76f25fd653cd218df36325"
        bytes: 231
      -
        path: "bases/cluster-metrics-readonly/kustomization.yaml"
        sha256: "44d52637f259f73730afd3a41d7350391387456ab7c418f201eec1ef73720153"
        bytes: 99
      -
        path: "bases/cluster-metrics-readonly/upstream.yaml"
        sha256: "43dbd48cda5a6f5aa85365fdba15a04cb328d513a0123983ec943c505a01730c"
        bytes: 4027
      -
        path: "bases/default/kustomization.yaml"
        sha256: "44d52637f259f73730afd3a41d7350391387456ab7c418f201eec1ef73720153"
        bytes: 99
      -
        path: "bases/default/upstream.yaml"
        sha256: "43dbd48cda5a6f5aa85365fdba15a04cb328d513a0123983ec943c505a01730c"
        bytes: 4027
      -
        path: "installer.yaml"
        sha256: "562857af2abaddbe8437f8e39e634dcc65fad9091ea7ebf5e48df1c6bcaff3a4"
        bytes: 680
    version: "11.10.0"
  setupChecks:
    -
      allowedCubOnlyObjects:
        - "v1|Namespace||default"
      base: "default"
      command: "cub installer setup --pull packages/prometheus-community/prometheus-blackbox-exporter/11.10.0 --base default --work-dir <tmp> --non-interactive --namespace default"
      cubInstallObjectCountIncludingSupport: 5
      helmReleaseObjectCount: 4
      semanticObjectMatches: "4/4"
      separatedSecretCount: 0
      variant: "default"
    -
      allowedCubOnlyObjects:
        - "v1|Namespace||default"
      base: "cluster-metrics-readonly"
      command: "cub installer setup --pull packages/prometheus-community/prometheus-blackbox-exporter/11.10.0 --base cluster-metrics-readonly --work-dir <tmp> --non-interactive --namespace default"
      cubInstallObjectCountIncludingSupport: 5
      helmReleaseObjectCount: 4
      semanticObjectMatches: "4/4"
      separatedSecretCount: 0
      variant: "cluster-metrics-readonly"
