apiVersion: "installer.confighub.com/v1alpha1"
kind: "Package"
metadata:
  name: "prometheus-community-prometheus-adapter"
  version: "5.3.0"
spec:
  bases:
    -
      name: "default"
      path: "bases/default"
      default: true
      description: "prometheus-community/prometheus-adapter default variant rendered from prometheus-community/prometheus-adapter@5.3.0"
