#!/usr/bin/env bash
# grafana/loki 7.0.0 - preset: simple-scalable-minio
# Path: pull the package, render this preset locally, read the objects,
# then apply them with kubectl. No ConfigHub account is needed.
# Generated by scripts/generate-public-site.mjs from the committed package
# data for this preset. Chart page: https://confighub.github.io/helm-expt/site/charts/grafana-loki-7-0-0.html
set -euo pipefail

say() { printf '\n>> %s\n' "$*"; }

if ! command -v cub >/dev/null 2>&1; then
  printf 'cub is not installed. Install it with:\n  curl -fsSL https://hub.confighub.com/cub/install.sh | bash\nthen add ~/.confighub/bin to your PATH and re-run this script.\n' >&2
  exit 1
fi

if ! command -v kubectl >/dev/null 2>&1; then
  printf 'kubectl is required for the apply step.\n' >&2
  exit 1
fi

say "Pull the package and render the simple-scalable-minio preset into ./grafana-loki-7-0-0-simple-scalable-minio"
cub installer setup --pull oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/grafana-loki:7.0.0 --base simple-scalable-minio --work-dir ./grafana-loki-7-0-0-simple-scalable-minio --non-interactive --namespace loki

say "Read what was rendered; nothing has touched the cluster yet"
ls ./grafana-loki-7-0-0-simple-scalable-minio/out/manifests

say "Ensure the loki namespace exists"
kubectl create namespace loki --dry-run=client -o yaml | kubectl apply -f -

if [ -d ./grafana-loki-7-0-0-simple-scalable-minio/out/secrets ]; then
  say "Apply rendered Secrets first"
  kubectl apply -f ./grafana-loki-7-0-0-simple-scalable-minio/out/secrets
fi

say "Apply the rendered objects"
kubectl apply -f ./grafana-loki-7-0-0-simple-scalable-minio/out/manifests

say "Done. The cluster received exactly the files in ./grafana-loki-7-0-0-simple-scalable-minio/out."
