#!/usr/bin/env bash
# argo-cd/argo-workflows 1.0.14 - base variant: default
# Path: render this base variant locally, then upload the objects to your
# ConfigHub Space as Units you can edit, diff, and deliver.
# Needs a ConfigHub account: run cub auth login once before this script.
# Generated by scripts/generate-public-site.mjs from the committed package
# data for this base variant. Chart page: https://confighub.github.io/helm-expt/site/charts/argo-cd-argo-workflows-1-0-14.html
set -euo pipefail

say() { printf '\n>> %s\n' "$*"; }

if ! command -v cub >/dev/null 2>&1; then
  printf 'cub is not installed. Install the cub CLI with:\n  curl -fsSL https://hub.confighub.com/cub/install.sh | bash\nthen add ~/.confighub/bin to your PATH and re-run this script.\n' >&2
  exit 1
fi

# Installer is a cub plugin. Check it before this script does any work.
if ! cub installer --help >/dev/null 2>&1; then
  printf 'The cub installer plugin is missing. Follow https://confighub.github.io/helm-expt/site/try.html#install-cub, then re-run this script.\n' >&2
  exit 1
fi

if ! command -v kustomize >/dev/null 2>&1; then
  printf 'kustomize is missing. Follow https://confighub.github.io/helm-expt/site/try.html#install-cub, then re-run this script.\n' >&2
  exit 1
fi

SPACE="${CUB_SPACE:-helm-argo-workflows-default}"

say "Check ConfigHub auth"
if ! cub auth status >/dev/null 2>&1; then
  printf 'Not logged in. Run: cub auth login\nThen re-run this script.\n' >&2
  exit 1
fi

say "Render the default base variant into ./argo-cd-argo-workflows-1-0-14-default"
cub installer setup --pull oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/argo-cd-argo-workflows:1.0.14@sha256:abbebaeccc07e0583c7ccc5ad0c9d315057e6b4c0a766bd72c167ee92d3f160f --base default --work-dir ./argo-cd-argo-workflows-1-0-14-default --non-interactive --namespace default

say "Upload the rendered objects to Space ${SPACE} (created on first upload)"
cub installer upload --work-dir ./argo-cd-argo-workflows-1-0-14-default --space "${SPACE}"

say "Uploaded. See your Units:"
printf '  cub unit list --space %s\n  or open https://hub.confighub.com and find that Space.\n' "${SPACE}"

say "Next: create an environment variant and promote reviewed changes"
printf '  Walkthrough with the why behind each flag:\n  https://confighub.github.io/helm-expt/site/d/docs/user/variants-after-upload.html\n'

# Before applying this base variant from ConfigHub to a cluster, it still needs:
#   - CRD clusterworkflowtemplates.argoproj.io (included in the package as prerequisites/target-facts/default-crds.yaml)
#   - CRD cronworkflows.argoproj.io (included in the package as prerequisites/target-facts/default-crds.yaml)
#   - CRD workflowartifactgctasks.argoproj.io (included in the package as prerequisites/target-facts/default-crds.yaml)
#   - CRD workfloweventbindings.argoproj.io (included in the package as prerequisites/target-facts/default-crds.yaml)
#   - CRD workflows.argoproj.io (included in the package as prerequisites/target-facts/default-crds.yaml)
#   - CRD workflowtaskresults.argoproj.io (included in the package as prerequisites/target-facts/default-crds.yaml)
#   - CRD workflowtasksets.argoproj.io (included in the package as prerequisites/target-facts/default-crds.yaml)
#   - CRD workflowtemplates.argoproj.io (included in the package as prerequisites/target-facts/default-crds.yaml)
