#!/usr/bin/env bash
# argo-cd/argo-workflows 1.0.14 - base variant: default
# Path: pull the package, render this base variant locally, read the objects,
# then apply them with kubectl. No ConfigHub account is needed.
# Generated by scripts/generate-public-site.mjs from the committed package
# data for this base variant. Chart page: https://confighub.github.io/helm-expt/site/charts/argo-cd-argo-workflows-1-0-14.html
set -euo pipefail

say() { printf '\n>> %s\n' "$*"; }

if ! command -v cub >/dev/null 2>&1; then
  printf 'cub is not installed. Install the cub CLI with:\n  curl -fsSL https://hub.confighub.com/cub/install.sh | bash\nthen add ~/.confighub/bin to your PATH and re-run this script.\n' >&2
  exit 1
fi

# Installer is a cub plugin. Check it before this script does any work.
if ! cub installer --help >/dev/null 2>&1; then
  printf 'The cub installer plugin is missing. Follow https://confighub.github.io/helm-expt/site/try.html#install-cub, then re-run this script.\n' >&2
  exit 1
fi

if ! command -v kustomize >/dev/null 2>&1; then
  printf 'kustomize is missing. Follow https://confighub.github.io/helm-expt/site/try.html#install-cub, then re-run this script.\n' >&2
  exit 1
fi

if ! command -v kubectl >/dev/null 2>&1; then
  printf 'kubectl is required for the apply step.\n' >&2
  exit 1
fi

say "Pull the package and render the default base variant into ./argo-cd-argo-workflows-1-0-14-default"
cub installer setup --pull oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/argo-cd-argo-workflows:1.0.14 --base default --work-dir ./argo-cd-argo-workflows-1-0-14-default --non-interactive --namespace default

say "Read what was rendered; nothing has touched the cluster yet"
ls ./argo-cd-argo-workflows-1-0-14-default/out/manifests

wait_for_crd() {
  crd_name="$1"
  deadline=$(( $(date +%s) + 180 ))
  until kubectl get "crd/${crd_name}" >/dev/null 2>&1; do
    if [ "$(date +%s)" -ge "$deadline" ]; then
      printf "CRD %s did not appear within 180 seconds.\n" "$crd_name" >&2
      return 1
    fi
    sleep 2
  done
  kubectl wait --for=condition=Established --timeout=120s "crd/${crd_name}"
}

say "Ensure the default namespace exists"
kubectl create namespace default --dry-run=client -o yaml | kubectl apply -f -

say "Apply the 8 locked CRDs before the workload"
kubectl apply --server-side --force-conflicts -f ./argo-cd-argo-workflows-1-0-14-default/package/prerequisites/target-facts/default-crds.yaml
wait_for_crd clusterworkflowtemplates.argoproj.io
wait_for_crd cronworkflows.argoproj.io
wait_for_crd workflowartifactgctasks.argoproj.io
wait_for_crd workfloweventbindings.argoproj.io
wait_for_crd workflows.argoproj.io
wait_for_crd workflowtaskresults.argoproj.io
wait_for_crd workflowtasksets.argoproj.io
wait_for_crd workflowtemplates.argoproj.io

if [ -d ./argo-cd-argo-workflows-1-0-14-default/out/secrets ]; then
  say "Apply rendered Secrets first"
  kubectl apply -f ./argo-cd-argo-workflows-1-0-14-default/out/secrets
fi

say "Apply the rendered objects"
kubectl apply -f ./argo-cd-argo-workflows-1-0-14-default/out/manifests

say "Done. The cluster received exactly the files in ./argo-cd-argo-workflows-1-0-14-default/out."
